<div class="venda">
	

       <?php
       if(isset($_SESSION['success'])){
       	echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
       }
	   
	    if(isset($_SESSION['error'])){
       	echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
       }

		 // session_destroy();
		$this->dump($_SESSION);
		
		// if(isset($dependentes))
		// $this->dump($dependentes);
		
       $form->init('form_addClientePF','addClientePF','post');
		
	    $form->input(array(
				'name' =>'cpf_clientePF',
				'type' =>'text',
				'placeholder' => 'CPF do Cliente',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'CPF',
				'value' => '',
				'required' => false
				));
				
		echo '<button type="button" id="bt_findCliente"  data-toggle="modal" data-target="#myModal" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Buscar</button>';
		echo ' ';
		echo '<button type="button" id="bt_addNew" class="btn btn-primary"><i class="glyphicon glyphicon-user"></i> Novo</button>';
		$form->groupClose();

        $form->close(); ?>
       
      	<!-- Modal cliente Pessoa Física -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Cliente Cadastrado</h4>
				</div>
				<div class="modal-body">
						<form method="post" action="/venda/addClientePF">
						<input id="id_PF" name="id_PF" type="hidden">
							<?php foreach($participacao as $part):  ?>
								<input type="radio" name="id_participacao" value="<?=$part['id_participacao']?>"><?=$part['titulo_participacao']?>&nbsp;&nbsp;
							<?php endforeach;  ?>
						<br />
						<hr />
						<div id="nome_PF"></div>
						<div id="cpf_PF"></div>
						<div id="dataNascimento_PF"></div>
						<div id="endereco_PF"></div>
						<div id="telefone_PF"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
					<button type="submit" id="bt_incluir" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	   	<!-- Modal dependente cliente -->
	<div class="modal fade" id="modalDependente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Dependentes</h4>
				</div>
				<div class="modal-body">
				<form method="post" action="/venda/addDependente">
				<div class="dependentePF">	</div>
						
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirDependente" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	   
	
	<br />
	<br />
	<br />
	
	   	<!-- Modal de aluguel de carros -->
	<div class="modal fade" id="modalCarros" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Aluguel de Carros</h4>
				</div>
				<div class="modal-body">
					<div class="carroPF">	
						<?php 
						$form->init('formAddCarro','/carro/saveCarro','post');
						
						$form->groupOpen();
						foreach($locadoras as $loc){
							$opt_loc[$loc['id_locadora']] = $loc['nome_locadora'];
						}
						$form->select($opt_loc,'id_locadora','Locadora',1,2,5);
						$form->groupClose();

						$form->groupOpen();
						foreach($carros as $car){
							$op_car[$car['id_cambio']] = $car['titulo_cambio'];
						}
						$op_car['0'] = 'REAL BR';
						$form->select($op_car,'id_moeda','Moeda',0,2,5);
						$form->groupClose();
						
						
						$form->groupOpen();
						$opt_cli = array();
						if(isset($clientes)){
							foreach($clientes as $key => $value){
								foreach($value as $k => $v){
									$opt_cli[$v['id_clientePF']] = $v['nome_clientePF'];
								}
							}
						}
						$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'dt_inicio_carro',
							'type' =>'date',
							'placeholder' => 'Data de início',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Início',
							'value' => '',
							'required' => true
							));
							
						$form->input(array(
							'name' =>'hora_inicio_carro',
							'type' =>'time',
							'placeholder' => 'Horário de início',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Início',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();	
						$form->input(array(
							'name' =>'dt_devolucao_carro',
							'type' =>'date',
							'placeholder' => 'Data de Devolução',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Fim',
							'value' => '',
							'required' => true
							));	
							
							$form->input(array(
							'name' =>'hora_devolucao_carro',
							'type' =>'time',
							'placeholder' => 'Horário de Devolução',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Fim',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_incio_carro',
							'type' =>'text',
							'placeholder' => 'Local de retirada',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Retirada',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_devolucao_carro',
							'type' =>'text',
							'placeholder' => 'Local de Devolução',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Devolução',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'voucher_carro',
							'type' =>'file',
							'placeholder' => '',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Voucher',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_carro',
							'type' =>'text',
							'placeholder' => 'Valor do Aluguel',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Aluguel',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_casa_carro',
							'type' =>'text',
							'placeholder' => 'Comissão da Casa',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Comissão',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'taxa_carro',
							'type' =>'text',
							'placeholder' => 'Taxas Extras',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Taxas',
							'value' => '',
							'required' => false
							));	
						$form->groupClose();
						 ?>
						 <label>Descrição</label>
						 <textarea name="descricao_carro" class="form-control" rows="3"></textarea>
					</div><!-- div carroPF-->
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirCarro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	   	<!-- Modal de aluguel de carros -->
	   	
	   	
	   	
	   		<!-- Modal Hotel -->
	<div class="modal fade" id="modalHotel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Hotel</h4>
				</div>
				<div class="modal-body">
						<?php
			$form->init('form_hotel','/hotel/saveHotel');
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_hoteis',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => false
				));
			$form->groupClose();

			$form->groupOpen();	
			$opt_bro['0'] = 'NENHUM';
			foreach($brokers as $key => $value){
				$opt_bro[$value['id_brokers']] = $value['nome_brokers'];
			}
			$form->select($opt_bro,'id_brokers','Brokers',0,2,8);
			$form->groupClose();

			$form->groupOpen();
			
			$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
			$form->groupClose();

			$form->groupOpen();	
			$opt_moe['0'] = 'Real BR';
			foreach($moedas as $key => $value){
				$opt_moe[$value['id_cambio']] = $value['titulo_cambio'];
			}
			$form->select($opt_moe,'id_moeda','Moeda',0,2,4);
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'nome_hotel',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Nome',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();
			echo ' <div id="checkbox" class="checkbox"><input type="checkbox" name="is_br" id="is_br" value="nothing"><span>Internacional</span></div>';
			$form->groupClose();
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'cep_hotel',
				'type' =>'text',
				'placeholder' => 'CEP',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'CEP',
				'value' =>'',
				'required' => false
				));
				echo '<div id="msg_cep"></div>';
			$form->groupClose();
		
			$form->groupOpen();	
			$form->input(array(
				'name' =>'endereco_hotel',
				'type' =>'text',
				'placeholder' => 'Endereço',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Endereço',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'numero_hotel',
				'type' =>'text',
				'placeholder' => 'Número',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Número',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();


			$form->groupOpen();	
			$form->input(array(
				'name' =>'cidade_hotel',
				'type' =>'text',
				'placeholder' => 'Cidade',
				'num_label' =>'2',
				'num_input' =>'6',
				'label' =>'Cidade',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'uf_hotel',
				'type' =>'text',
				'placeholder' => 'UF',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'UF',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'telefone_hotel',
				'type' =>'text',
				'placeholder' => 'Telefone',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Telefone',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'email_hotel',
				'type' =>'text',
				'placeholder' => 'Email',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Email',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_hotel',
				'type' =>'file',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'7',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_hotel',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
			// $form->groupClose();
// 
			// $form->groupOpen();	
			$form->input(array(
				'name' =>'valor_casa_hotel',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
		<label>Descrição</label>
		<textarea name="descricao_hotel" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirHotel" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	<!-- Modal Hotel -->
	
	
		   	<!-- Modal Seguro -->
	<div class="modal fade" id="modalSeguro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Seguros</h4>
				</div>
				<div class="modal-body">
			<?php
		$form->init('form_seguro','/seguro/saveSeguro');
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'id_seguro',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
		$form->groupClose();

		$form->groupOpen();	
		foreach($seguradoras as $key => $value){
			$opt_seg[$value['id_seguradora']] = $value['nome_seguradora'];
		}
		$form->select($opt_seg,'id_seguradora','Seguradora',1,2,8);
		$form->groupClose();

		$form->groupOpen();
		foreach($tipoSeguros as $key => $value){
			$opt_tip[$value['id_tipoSeguro']] = $value['nome_tipoSeguro'];
		}	
		$form->select($opt_tip,'id_tipoSeguro','Tipo',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		foreach($continentes as $key => $value){
			$opt_cont[$value['id_continente']] = $value['nome_continente'];
		}
		$form->select($opt_cont,'id_continente','Continente',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		foreach($moedas as $key => $value){
			$opt_moe[$value['id_cambio']] = $value['titulo_cambio'];
		}
		$form->select($opt_moe,'id_moeda','Moeda',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_seguro',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_casa_seguro',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'voucher_seguro',
				'type' =>'file',
				'placeholder' => 'Voucher',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirSeguro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		   	<!-- Modal Seguro -->
	
	
	
	
	<!-- Tela de botoes de produtos-->
	<div class="venda_produtos">
		<div class="vend_produtos_left">
			<br />
			<br />
			<p><a href="#" title="Reserva de Hoteis" data-toggle="modal" data-target="#modalHotel" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> HOTEIS</a></p>
			<br />
			<p><a href="#"  data-toggle="modal" data-target="#modalCarros" title="Aluguel de carros" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CARROS</a></p>
			<br />
			<p><a href="#" title="Reservar passagens aéreas" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> PASSAGENS</a></p>
		</div>
		
		<div class="vend_produtos_right">
			<br />
			<br />
			<p><a href="#" data-toggle="modal" data-target="#modalSeguro" title="Contratar Seguro para viagem" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> SEGURO</a></p>
			<br />
			<p><a href="#" title="Compra de tickets" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> TICKETS</a></p>
			<br />
			<p><a href="#" title="Compra de cruzeiros atlânticos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CRUZEIROS</a></p>
			<br />
			<p><a href="#" title="Outros Produtos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> Outros</a></p>
		</div>
	</div>
	<!-- Tela de botoes de produtos-->
	<hr />
	
	<hr />
	<br />
	<table class="table table-condensed">
		
			<!-- Cliente da Lista de venda -->
		<?php if(isset($clientes)): 
			foreach($clientes as $key => $value):
				foreach($value as $k => $v){
					$nome_cli[$v['id_clientePF']] = $v['nome_clientePF'];
			?>
			<tr class="warning">
				<td><?='Cliente: '.$v['nome_clientePF']?></td>
				<td>Cliente</td>
				<td><a href="#"  class="btn btn-info bt_part" id_cliente="<?=$v['id_clientePF']?>" data-toggle="modal" data-target="#modalDependente"><span class="glyphicon glyphicon-plus-sign"></span> Dependentes</a></td>
				<td><a href="/venda/deleteClientePF/id/<?=$v['id_clientePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_clientePF']?> da lista de venda?')" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
			</tr>
		<?php 
				}
			endforeach;
		endif; 
		///Dependentes da lista de venda
		if(isset($dependentes)):
			foreach($dependentes as $key => $value): 
				foreach($value as $k =>  $v){
			?>
			<tr class="success">
				<td><?='Dependente: '.$v['nome_dependentePF'] ?></td>
				<td>Dependente</td>
				<td><?=$nome_cli[$v['id_clientePF']]?></td>
				<td><a href="/venda/deleteDependente/cli/<?=$v['id_clientePF']?>/id/<?=$v['id_dependentePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_dependentePF']?> da lista de venda?')" class="btn btn-warning"><span class="glyphicon glyphicon-trash"></span></a></td>
			</tr>
			<?php 
				}
			endforeach;	
		endif;
		
		
			### Popula locadoras de carros ###
		if(isset($vCarros) && count($vCarros) != 0):
			foreach($vCarros as $key => $value){
			echo '<tr class="success">';
				$total = 0;
				foreach($value as $k => $v){
					$total += $v['valor_carro'];
					$total += $v['valor_casa_carro'];
					$total += $v['taxa_carro'];
					
					echo '<td>Carro: '.$opt_loc[$v['id_locadora']].'</td>';
					echo '<td>'.$opt_cli[$v['id_clientePF']].'</td>';
					echo '<td>R$ '.number_format($total,2,',','.').'</td>';
			 		echo '<td><a href="/carro/deleteCarro/id/'.$v['id_carros'].'/cli/'.$v['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse carro da lista de venda?\')" class="btn btn-warning"><span class="glyphicon glyphicon-trash"></span></a></td>';
				}
					
			echo '</tr>';
			}
			
		endif;	
			### Popula locadoras de carros ###
			
			
		########## Popula hoteis ##############	
		if(isset($hoteis)){
			foreach($hoteis as $key => $value){
				echo '<tr class="danger">';
				$total = 0;
				foreach($value as $chave => $valor){
					echo '<td>Hotel: '.$valor['nome_hotel'].'</td>';
					echo '<td>'.$opt_cli[$valor['id_clientePF']].'</td>';
					$total += $valor['valor_hotel'];
					$total += $valor['valor_casa_hotel'];
					echo '<td>R$ '.number_format($total,2,',','.').'</td>';
			 		echo '<td><a href="/hotel/deleteHotel/id/'.$valor['id_hoteis'].'/cli/'.$valor['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Hotel da lista de venda?\')" class="btn btn-warning"><span class="glyphicon glyphicon-trash"></span></a></td>';
				}
				echo '</tr>';
			}
		}
		########## Popula hoteis ##############	
		
		
		########## Popula Seguros ##############
		if(isset($seguros)){
			foreach($seguros as $key => $value){
			echo '<tr class="warning">';
					$total = 0;
				foreach($value as $chave => $valor){
					echo '<td> Seguradora: '.$opt_seg[$valor['id_seguradora']].' - '.$opt_tip[$valor['id_tipoSeguro']].'</td>';
					echo '<td>'.$opt_cli[$valor['id_clientePF']].'</td>';
					$total += $valor['valor_seguro'];
					$total += $valor['valor_casa_seguro'];
					echo '<td>R$ '.number_format($total,2,',','.').'</td>';
					echo '<td><a href="/seguro/deleteSeguro/id/'.$valor['id_seguro'].'/cli/'.$valor['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Seguro da lista de venda?\')" class="btn btn-warning"><span class="glyphicon glyphicon-trash"></span></a></td>';
				}	
			echo '</tr>';	
			}
		}	
		########## Popula Seguros ##############	
		?>
	</table>
       
      </div>
        
   
<script>
	jQuery(function(){
		
		//Eventos de cliques
		jQuery('#bt_addNew').click(function(){
			location.href="/cliente/cadfisica";
		});
		
		
		//evento de buscar cliente montar o modal 
		jQuery('#bt_findCliente').click(function(){
			var nomeCli = jQuery('#nome_clientePF').val();
			var cpfCli = jQuery('#cpf_clientePF').val();
			
			jQuery.ajax({
				url: '/venda/findClientePF',
				type: 'post',
				dataType: 'json',
				data: {nome: nomeCli, cpf: cpfCli},
				success: function(data){
					if(data == ''){
						jQuery(".modal-body").html('<h2>Cliente não foi encontrado!</h2>');
						jQuery("#bt_incluir").attr('disabled',true);
					}
						jQuery('#id_PF').val(data[0].id_clientePF);
						jQuery('#cpf_PF').html('CPF: ' +data[0].cpf_clientePF);
						jQuery('#dataNascimento_PF').html('Data de Nasc: ' +format_data(data[0].dataNascimento_clientePF));
						jQuery('#nome_PF').html('Nome: ' +data[0].nome_clientePF);
						jQuery('#endereco_PF').html('Endereço: ' +data[0].endereco_clientePF);
						jQuery('#telefone_PF').html('Telefone: ' +data[0].telefone_clientePF);
						jQuery("#bt_incluir").attr('disabled',false);
				}
			});
		});
		//evento de buscar cliente montar o modal 
		
		
			//Evento para desabilitar botão de busca
			jQuery('#bt_findCliente').attr('disabled',true);
		
			
			//Evento para bloquear botão de busca enquanto campo cpf estiver vázio			
			jQuery('#cpf_clientePF').keypress(function(){
				if(jQuery(this).val().length > 0){
					jQuery('#bt_findCliente').attr('disabled',false);
				}
			});
		
			//Evento para buscar dependentes do cliente pessoa física
			jQuery('.bt_part').click(function(){
				var id_cliente = jQuery(this).attr('id_cliente');
				jQuery.ajax({
					url: '/venda/findDependente',
					type: 'post',
					dataType: 'json',
					data: {id_cliente : id_cliente},
					success: function(data){
						jQuery("#bt_incluirDependente").attr('disabled',false);
						if(data.length){
							jQuery('.dependentePF').html('');
							jQuery('.dependentePF').append('<input type="hidden" name="id_clientePF" value="'+data[0].id_clientePF+'"/>');
							for(var i = 0; i < data.length; i++ ){
								jQuery('.dependentePF').append('<input type="checkbox" name="id_dependentePF[]" value="'+data[i].id_dependentePF+'"/> '+data[i].nome_dependentePF + '<br />');
							}
						}else{
							jQuery(".dependentePF").html('<h3>Esse cliente não tem dependente!</h3>');
							jQuery("#bt_incluirDependente").attr('disabled',true);
						}
						
					}
				});
			});
		
		jQuery('#bt_sairDependente').click(function(){
			
		});
		
		//Mascarando campos
		jQuery('#cpf_clientePF').mask('999.999.999-99');
		
		
		//Funções para o modal Carros
		
		// jQuery('#dt_inicio_carro').mask('99/99/9999');
		// jQuery('#dt_devolucao_carro').mask('99/99/9999');
		// jQuery('#hora_inicio_carro').mask('99:99');
		// jQuery('#hora_devolucao_carro').mask('99:99');
		jQuery("#valor_carro").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_carro").maskMoney({thousands:'', decimal:'.'});
		jQuery("#taxa_carro").maskMoney({thousands:'', decimal:'.'});
		
			if(jQuery('[name=id_clientePF]').find('option').length == 0){
				jQuery('#bt_incluirCarro').attr('disabled',true);
			}else{
				jQuery('#bt_incluirCarro').attr('disabled',false);
			}
		//Funções para o modal Carros
		
		
		//Funções do modal de hotel
		jQuery('#cep_hotel').mask('99999-999');
		jQuery('#checkbox').css('margin-left','17%');
		jQuery("#valor_hotel").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_hotel").maskMoney({thousands:'', decimal:'.'});
		jQuery('#is_br').click(function(){
			if(jQuery('#is_br:checked').length > 0){
				jQuery('#cep_hotel').attr('disabled',true);
			}else{
				jQuery('#cep_hotel').attr('disabled',false);
			}
		});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirHotel').attr('disabled',true);
		}else{
			jQuery('#bt_incluirHotel').attr('disabled',false);
		}
		
		jQuery("#cep_hotel").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#endereco_hotel').val(data.endereco);
		 			jQuery('#cidade_hotel').val(data.cidade	);
		 			jQuery('#uf_hotel').val(data.uf);
		 			jQuery('#numero_hotel').focus();
		 			}else{
		 				jQuery('#msg_cep').html('CEP Não encontrado!');
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		
		//Funções do modal de hotel
		
		
		//Funções do modal de Seguro
		jQuery('#valor_seguro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_casa_seguro').maskMoney({thousands:'', decimal:'.'});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirSeguro').attr('disabled',true);
		}else{
			jQuery('#bt_incluirSeguro').attr('disabled',false);
			
		}
		//Funções do modal de Seguro
		
		
		
		//Função para formatar data no padrão brasileiro
		function format_data(data){
					var dia = data.split("-")[2];
					var mes = data.split("-")[1];
					var ano = data.split('-')[0];
					
					return dia + '/' + mes + '/' + ano;
				}
		
	});
</script>