<div class="venda">
	

       <?php
       if(isset($_SESSION['success'])){
       	echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
       }
	   
	    if(isset($_SESSION['error'])){
       	echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
       }
		
		
       $form->init('form_addClientePF','addClientePF','post');
		
	    $form->input(array(
				'name' =>'cpf_clientePF',
				'type' =>'text',
				'placeholder' => 'CPF do Cliente',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'CPF',
				'value' => '',
				'required' => false
				));
				
				
		echo '<button type="button" id="bt_findCliente"  data-toggle="modal" data-target="#myModal" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Buscar</button>';
		echo ' ';
		echo '<button type="button" id="bt_addNew" class="btn btn-primary"><i class="glyphicon glyphicon-user"></i> Novo</button>';
		$form->groupClose();

        $form->close(); ?>
       
      	<!-- Modal cliente Pessoa Física -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Cliente Cadastrado</h4>
				</div>
				<div class="modal-body">
						<form method="post" action="/venda/addClientePF">
						<input id="id_PF" name="id_PF" type="hidden">
							<?php foreach($participacao as $part): 
							if($part['id_participacao'] == 3){
								$ckecked = 'checked';
							}else{
								$ckecked = null;
							}
							 ?>
								<input type="radio" name="id_participacao" <?=$ckecked; ?> value="<?=$part['id_participacao']?>"><?=$part['titulo_participacao']?>&nbsp;&nbsp;
							<?php endforeach;  ?>
						<br />
						<hr />
						<div id="nome_PF"></div>
						<div id="cpf_PF"></div>
						<div id="dataNascimento_PF"></div>
						<div id="endereco_PF"></div>
						<div id="telefone_PF"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
					<button type="submit" id="bt_incluir" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	   	<!-- Modal dependente cliente -->
	<div class="modal fade" id="modalDependente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Dependentes</h4>
				</div>
				<div class="modal-body">
				<form method="post" action="/venda/addDependente">
				<div class="dependentePF">	</div>
						
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirDependente" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
		   
	
	<br />
	<br />
	<br />
	
	   	<!-- Modal de aluguel de carros -->
	<div class="modal fade" id="modalCarros" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Aluguel de Carros</h4>
				</div>
				<div class="modal-body">
					<div class="carroPF">	
						<?php 
						$form->init('formAddCarro','/carro/saveCarro','post');
						
						$form->groupOpen();
						foreach($locadoras as $loc){
							$opt_loc[$loc['id_locadora']] = $loc['nome_locadora'];
						}
						$form->select($opt_loc,'id_locadora','Locadora',1,2,5);
						$form->groupClose();

						$form->groupOpen();
						foreach($carros as $car){
							$op_car[$car['id_cambio']] = $car['titulo_cambio'];
						}
						$op_car['0'] = 'REAL BR';
						$form->select($op_car,'id_moeda','Moeda',0,2,5);
						$form->input(array(
							'name' =>'valor_cambio_carro',
							'type' =>'text',
							'placeholder' => 'Valor',
							'num_label' =>'2',
							'num_input' =>'2',
							'label' =>'Cambio',
							'value' => '',
							'required' => true
							));
						$form->groupClose();
						
						
						$form->groupOpen();
						$opt_cli = array();
						if(isset($clientes)){
							foreach($clientes as $key => $value){
								foreach($value as $k => $v){
									$opt_cli[$v['id_clientePF']] = $v['nome_clientePF'];
								}
							}
						}
						$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'dt_inicio_carro',
							'type' =>'date',
							'placeholder' => 'Data de início',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Início',
							'value' => '',
							'required' => true
							));
							
						$form->input(array(
							'name' =>'hora_inicio_carro',
							'type' =>'time',
							'placeholder' => 'Horário de início',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Início',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();	
						$form->input(array(
							'name' =>'dt_devolucao_carro',
							'type' =>'date',
							'placeholder' => 'Data de Devolução',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Fim',
							'value' => '',
							'required' => true
							));	
							
							$form->input(array(
							'name' =>'hora_devolucao_carro',
							'type' =>'time',
							'placeholder' => 'Horário de Devolução',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Fim',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_incio_carro',
							'type' =>'text',
							'placeholder' => 'Local de retirada',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Retirada',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_devolucao_carro',
							'type' =>'text',
							'placeholder' => 'Local de Devolução',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Devolução',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'voucher_carro',
							'type' =>'file',
							'placeholder' => '',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Voucher',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_carro',
							'type' =>'text',
							'placeholder' => 'Valor do Aluguel',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Aluguel',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_casa_carro',
							'type' =>'text',
							'placeholder' => 'Comissão da Casa',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Comissão',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'taxa_carro',
							'type' =>'text',
							'placeholder' => 'Taxas Extras',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Taxas',
							'value' => '',
							'required' => false
							));	
						$form->groupClose();
						 ?>
						 <label>Descrição</label>
						 <textarea name="descricao_carro" class="form-control" rows="3"></textarea>
					</div><!-- div carroPF-->
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirCarro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	   	<!-- Modal de aluguel de carros -->
	   	
	   	
	   	
	   		<!-- Modal Hotel -->
	<div class="modal fade" id="modalHotel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Hotel</h4>
				</div>
				<div class="modal-body">
						<?php
			$form->init('form_hotel','/hotel/saveHotel');
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_hoteis',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => false
				));
			$form->groupClose();

			$form->groupOpen();	
			$opt_bro['0'] = 'NENHUM';
			foreach($brokers as $key => $value){
				$opt_bro[$value['id_brokers']] = $value['nome_brokers'];
			}
			$form->select($opt_bro,'id_brokers','Brokers',0,2,8);
			$form->groupClose();

			$form->groupOpen();
			
			$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
			$form->groupClose();

			$form->groupOpen();	
			$opt_moe['0'] = 'Real BR';
			foreach($moedas as $key => $value){
				$opt_moe[$value['id_cambio']] = $value['titulo_cambio'];
			}
			$form->select($opt_moe,'id_moeda','Moeda',0,2,4);
			$form->input(array(
				'name' =>'valor_cambio_hotel',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Cambio',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'nome_hotel',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Nome',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();
			echo ' <div id="checkbox" class="checkbox"><input type="checkbox" name="is_br" id="is_br" value="nothing"><span>Internacional</span></div>';
			$form->groupClose();
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'cep_hotel',
				'type' =>'text',
				'placeholder' => 'CEP',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'CEP',
				'value' =>'',
				'required' => false
				));
				echo '<div id="msg_cep"></div>';
			$form->groupClose();
		
			$form->groupOpen();	
			$form->input(array(
				'name' =>'endereco_hotel',
				'type' =>'text',
				'placeholder' => 'Endereço',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Endereço',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'numero_hotel',
				'type' =>'text',
				'placeholder' => 'Número',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Número',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();


			$form->groupOpen();	
			$form->input(array(
				'name' =>'cidade_hotel',
				'type' =>'text',
				'placeholder' => 'Cidade',
				'num_label' =>'2',
				'num_input' =>'6',
				'label' =>'Cidade',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'uf_hotel',
				'type' =>'text',
				'placeholder' => 'UF',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'UF',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'telefone_hotel',
				'type' =>'text',
				'placeholder' => 'Telefone',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Telefone',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'email_hotel',
				'type' =>'text',
				'placeholder' => 'Email',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Email',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_hotel',
				'type' =>'file',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'7',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_hotel',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));

			$form->input(array(
				'name' =>'valor_casa_hotel',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
		<label>Descrição</label>
		<textarea name="descricao_hotel" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirHotel" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	<!-- Modal Hotel -->
	
	
		   	<!-- Modal Seguro -->
	<div class="modal fade" id="modalSeguro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Seguros</h4>
				</div>
				<div class="modal-body">
			<?php
		$form->init('form_seguro','/seguro/saveSeguro');
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'id_seguro',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
		$form->groupClose();

		$form->groupOpen();	
		foreach($seguradoras as $key => $value){
			$opt_seg[$value['id_seguradora']] = $value['nome_seguradora'];
		}
		$form->select($opt_seg,'id_seguradora','Seguradora',1,2,8);
		$form->groupClose();

		$form->groupOpen();
		foreach($tipoSeguros as $key => $value){
			$opt_tip[$value['id_tipoSeguro']] = $value['nome_tipoSeguro'];
		}	
		$form->select($opt_tip,'id_tipoSeguro','Tipo',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		foreach($continentes as $key => $value){
			$opt_cont[$value['id_continente']] = $value['nome_continente'];
		}
		$form->select($opt_cont,'id_continente','Continente',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		foreach($moedas as $key => $value){
			$opt_moe[$value['id_cambio']] = $value['titulo_cambio'];
		}
		$form->select($opt_moe,'id_moeda','Moeda',1,2,5);
		$form->input(array(
				'name' =>'valor_cambio_seguro',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Cambio',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'dt_inicio_seguro',
				'type' =>'date',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Inicio',
				'value' =>'',
				'required' => true
				));
		// $form->groupClose();
// 		
		// $form->groupOpen();	
		$form->input(array(
				'name' =>'dt_fim_seguro',
				'type' =>'date',
				'placeholder' => '',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Fim',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_seguro',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_casa_seguro',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'voucher_seguro',
				'type' =>'file',
				'placeholder' => 'Voucher',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
		
		<label>Descrição</label>
		<textarea name="descricao_seguro" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirSeguro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		   	<!-- Modal Seguro -->
		   
		   
		   
		   
		   
		   	<!-- Modal Tickets -->
	<div class="modal fade" id="modalTicket" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Tickets</h4>
				</div>
				<div class="modal-body">
						<?php
			$form->init('form_compraticket','/compraTicket/saveCompraTicket');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_compraTicket',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();	
			$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
			$form->groupClose();

			$form->groupOpen();
			foreach($tickets as $key => $value){
				$opt_tic[$value['id_ticket']] = $value['nome_ticket'];
			}	
			$form->select($opt_tic,'id_ticket','Ticket',1,2,8);
			$form->groupClose();


			$form->groupOpen();	
			foreach($moedas as $key => $value){
				$opt_moe[$value['id_cambio']] = $value['titulo_cambio'];
			}
			$form->select($opt_moe,'id_moeda','Moeda',1,2,5);
			$form->input(array(
				'name' =>'valor_cambio_compraTicket',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Cambio',
				'value' =>'',
				'required' => false
				));
			$form->groupClose();


			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_compraTicket',
				'type' =>'text',
				'placeholder' => 'Valor da compra',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'comissao_compraTicket',
				'type' =>'text',
				'placeholder' => 'Comissão em porcentagem',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_compraTicket',
				'type' =>'file',
				'placeholder' => 'Voucher',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'fornecedor_compraTicket',
				'type' =>'text',
				'placeholder' => 'Nome Fornecedor',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Fornecedor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
						?>
		<label>Descrição</label>
		<textarea name="descricao_compraTicket" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirTicket" class="btn btn-primary">
						<i class="glyphicon glyphicon-plus-sign"></i> Incluir
					</button>
					<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

		   	<!-- Modal Tickets -->
		   	
		   	
		   	
		   	<!-- Modal Cruzeiros -->
	<div class="modal fade" id="modalCruzeiro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Cruzeiro</h4>
				</div>
				<div class="modal-body">
				<?php
				
				$form->init('form_cruzeiro','/cruzeiro/saveCruzeiro');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_cruzeiro',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();
			$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
			$form->groupClose();

			$form->groupOpen();	
			foreach($companiasCruzeiro as $comp){
				$opt_comp[$comp['id_compania_cruzeiro']] = $comp['nome_compania_cruzeiro'];
			}
			$form->select($opt_comp,'id_compania_cruzeiro','Companias',1,2,8);
			$form->groupClose();

			$form->groupOpen();	
			$form->select($opt_moe,'id_moeda','Moeda',0,2,4);
			$form->input(array(
				'name' =>'valor_cambio_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Cambio',
				'value' =>'',
				'required' => false
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'navio_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Navio',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'navio',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'dt_inicio_cruzeiro',
				'type' =>'date',
				'placeholder' => 'Inicio',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Início',
				'value' =>'',
				'required' => true
				));
				
				
		$form->input(array(
				'name' =>'dt_fim_cruzeiro',
				'type' =>'date',
				'placeholder' => 'Fim',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Fim',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'rota_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Rota',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Rota',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'nm_confirmacao_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Número de Confirmação',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Número',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'tipo_cabine_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Tipo de Cabine',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Cabine',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Valor do Cruzeiro',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
				$form->input(array(
						'name' =>'comissao_cruzeiro',
						'type' =>'text',
						'placeholder' => 'Comissão',
						'num_label' =>'2',
						'num_input' =>'5',
						'label' =>'Comissão',
						'value' =>'',
						'required' => true
						));
				$form->groupClose();
				
				
				$form->groupOpen();	
				$form->input(array(
						'name' =>'voucher_cruzeiro',
						'type' =>'file',
						'placeholder' => 'Voucher',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'Voucher',
						'value' =>'',
						'required' => false
						));
				$form->groupClose();
				
				?>
				<label>Descrição</label>
				<textarea name="descricao_cruzeiro" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirCruzeiro" class="btn btn-primary">
						<i class="glyphicon glyphicon-plus-sign"></i> Incluir
					</button>
					<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

		   	<!-- Modal Cruzeiros -->
		   	
		   	
		   	
		<!-- Modal Outros Produtos -->
	<div class="modal fade" id="modalProdutos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Outros Produtos</h4>
				</div>
				<div class="modal-body">
		<?php 
		$form->init('form_produtooutros','/produtoOutros/saveProdutoOutros');
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_produto',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_moe,'id_moeda','Moeda',0,2,4);
		$form->input(array(
			'name' =>'valor_cambio_produto',
			'type' =>'text',
			'placeholder' => 'Valor',
			'num_label' =>'2',
			'num_input' =>'2',
			'label' =>'Cambio',
			'value' =>'',
			'required' => false
			));
		$form->groupClose();
		
		$form->groupOpen();
		$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'titulo_produto',
			'type' =>'text',
			'placeholder' => 'Título',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Título',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'valor_produto',
			'type' =>'text',
			'placeholder' => 'Valor',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Valor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
				
		$form->groupOpen();	
		$form->input(array(
			'name' =>'comissao_produto',
			'type' =>'text',
			'placeholder' => 'Comissão',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Comissão',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'fornecedor_produto',
			'type' =>'text',
			'placeholder' => 'Fornecedor',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Fornecedor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'dt_inicio_produto',
			'type' =>'date',
			'placeholder' => 'Início',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Início',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'dt_final_produto',
			'type' =>'date',
			'placeholder' => 'Final',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Final',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
				?>
				<label>Descrição</label>
				<textarea name="descricao_produto" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirProdutos" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		<!-- Modal Outros Produtos -->
		
		
	  	<!-- Modal Passagens -->
	<div class="modal fade" id="modalPassagens" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Passagem Aérea</h4>
				</div>
				<div class="modal-body">
				<?php
		$form->init('form_passagens','/passagens/savePassagens');
		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_passagens',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		

		$form->groupOpen();
		$form->select($opt_cli,'id_clientePF','Cliente',1,2,8);
		$form->groupClose();

		$form->groupOpen();	
		foreach($companias as $comp){
			$opt_comp[$comp['id_compania']] = $comp['nome_compania'];
		}
		$form->select($opt_comp,'id_compania','Compania',1,2,8);
		echo '<td><a href="/compania/cadCompania" title="Adicionar nova Compania caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();


		$form->groupOpen();	
		foreach($classes as $class){
			$opt_class[$class['id_classe']] = $class['titulo_classe'];
		}
		$form->select($opt_class,'id_classe','Classe',1,2,8);
		echo '<td><a href="/classe/cadClasse" title="Adicionar nova classe caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();

		
		
		$form->groupOpen();	
		foreach($origens as $orig){
			$opt_orig[$orig['id_origem']] = $orig['nome_origem'];
		}
		$form->select($opt_orig,'id_origem','Origem',1,2,6);	
		echo '<td><a href="/origem/cadOrigem" title="Adicionar novo origem caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();
		
		
		
		$form->groupOpen();	
		foreach($destinos as $dest){
		$opt_dest[$dest['id_destino']] = $dest['nome_destino'];
		}
		$form->select($opt_dest,'id_destino','Destino',1,2,6);
		echo '<td><a href="/destino/cadDestino" title="Adicionar novo destino caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
				
		$form->groupClose();


		$form->groupOpen();	
		$form->select($opt_moe,'id_moeda','Moeda',0,2,4);
		$form->input(array(
			'name' =>'valor_cambio_passagens',
			'type' =>'text',
			'placeholder' => 'Valor',
			'num_label' =>'2',
			'num_input' =>'2',
			'label' =>'Cambio',
			'value' =>'',
			'required' => false
			));
		$form->groupClose();

		echo '<input type="checkbox" id="somente_ida" /> <strong>Somente ida</strong>';
		echo '<fieldset id="fs_ida">';
		echo '<legend><strong>IDA</strong></legend>';
		$form->groupOpen();	
		$form->input(array(
			'name' =>'dataIda_passagens',
			'type' =>'date',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'4',
			'label' =>'Data',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'saidaIda_passagens',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Saida',
			'value' =>'',
			'required' => true
			));

		$form->input(array(
			'name' =>'chegadaIda_passagens',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Chegada',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		echo '</fieldset>';
		
		
		echo '<fieldset id="fs_volta">';
		echo '<legend><strong>Volta</strong></legend>';
		$form->groupOpen();	
		$form->input(array(
			'name' =>'dataVolta_passagens',
			'type' =>'date',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'4',
			'label' =>'Data',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'saidaVolta_passagens',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Saida',
			'value' =>'',
			'required' => true
			));
			
		$form->input(array(
			'name' =>'chegadaVolta_passagens',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Chegada',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		echo '</fieldset>';
		echo '<hr>';

		$form->groupOpen();	
		$form->input(array(
			'name' =>'voo_passagens',
			'type' =>'text',
			'placeholder' => 'Voo',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Voo',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();


		$form->groupOpen();	
		$form->input(array(
			'name' =>'voucher_passagens',
			'type' =>'file',
			'placeholder' => 'Voucher',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Voucher',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

			 $form->groupOpen();	
			 $form->input(array(
				'name' =>'tarifa_passagens',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		
			$form->input(array(
				'name' =>'ticket_passagens',
				'type' =>'text',
				'placeholder' => 'Ticket',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Ticket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_casa_passagens',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
				
			$form->input(array(
				'name' =>'tx_embarque_passagens',
				'type' =>'text',
				'placeholder' => 'Taxa de Enbarque',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Embarque',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tx_outras_passagens',
				'type' =>'text',
				'placeholder' => 'Taxa Extra',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Extra',
				'value' =>'',
				'required' => false
				));
				
			$form->input(array(
				'name' =>'tx_repasse_passagens',
				'type' =>'text',
				'placeholder' => 'Taxa de Repasse',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Repasse',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		?>
		<label>Descrição</label>
		<textarea name="descricao_passagens" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirPassagens" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	  	<!-- Modal Passagens -->
		   	
		   	
	
	
	
		<!-- Modal Finalização de Venda -->
	<div class="modal fade" id="modalFinaliza" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog" style="width: 50%;">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Finalizar Venda</h4>
				</div>
				<div class="modal-body">
					<label style="color: #797676;" class="col-sm-2 control-label">Agencia</label> 
					<form method="post" action="/venda/saveVenda">
						<select class="form-control" name="id_agencia">
							<option value="0">7 Brasil</option>
							<?php foreach($agencias as $age): ?>
							<option value="<?=$age['id_agencia']?>"><?=$age['nomefantasia_agencia']?></option>
							<?php endforeach; ?>
						</select>
						<br />
						
						<label id="lb_vl_agencia" style="color: #797676;">Valor Agência</label>
						<br />
						<input type="text" name="valor_agencia" />
						<br />
						<label id="lb_agente" style="color: #797676;" class="col-sm-2 control-label">Agente</label> 
						<select class="form-control" name="id_agente" id="id_agente"></select>
						<br />
						<label id="lb_valor_agente" style="color: #797676;">Valor Agente</label>
						<br />
						<input type="text" name="valor_agente" />
						<br />
						<div class="faturado">
						<input type="radio"  name="faturado_venda" value="1"/> Faturado
						<input type="radio"  name="faturado_venda" value="2"/> Não Faturado
						</div>
						<br />
						<br />
					<!-- Todos os Produtos -->
					<div id="painel_cliente">
					<div class="panel-group" id="accordion">
						<!-- Aba de cliente-->
						<?php
						
						//Setando os contadores para total e comissão
						$total_tudo = 0;
						$total_comissao = 0;
						
						
						 if(isset($_SESSION['id_clientePF']) && count($_SESSION['id_clientePF']) > 0): ?>
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Clientes</a>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in">
					      <div class="panel-body">
					       <?php 
					       	$arrayClientePF = array();
						   foreach($_SESSION['id_clientePF']['id'] as $id){
						   		$arrayClientePF[] = $clientesPF->lista_one($id);
						   }
							foreach($arrayClientePF as $cliente):
					       ?>
					       <div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading"><?=$cliente['nome_clientePF']?></h4>
							    <p class="list-group-item-text">DATA NASC.: <?=date('d/m/Y',strtotime($cliente['dataNascimento_clientePF']))?></p>
					       
							    <p class="list-group-item-text">CPF: <?=$cliente['cpf_clientePF']?></p>
							    <p class="list-group-item-text">RG: <?=$cliente['rg_clientePF']?></p>
							    <p class="list-group-item-text">TELEFONE: <?=$cliente['telefone_clientePF']?></p>
							    <p class="list-group-item-text">ENDEREÇO: <?=$cliente['endereco_clientePF']?></p>
							  </a>
							</div>
						<?php endforeach; ?>	
							
					      </div>
					    </div>
					  </div>
					  <?php endif; ?>
						<!-- Aba de cliente-->
					  
					  <?php if(isset($dependentes) && count($dependentes) > 0): 
					  	$arrayDependentes = array();
						foreach($dependentes as $key => $value){
							foreach($value as $dep){
								$arrayDependentes[] = $dep;
							}
						}
					  	?>
						<!-- Aba de Dependentes-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Dependentes</a>
					      </h4>
					    </div>
					    <div id="collapseTwo" class="panel-collapse collapse">
					      <div class="panel-body">
					    
					    <?php foreach($arrayDependentes as $key => $value): 
					    	$hoje = new DateTime();
							$niver = new DateTime($value['dt_nascimento_dependentePF']);
							$anos = $niver->diff($hoje);
					    	?>
					    <!-- lista de Dependentes -->
					      	 <div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading"><?=$value['nome_dependentePF']?></h4>
							    <p class="list-group-item-text">CPF: <?=$value['cpf_dependentePF']?></p>
							    <p class="list-group-item-text">RG: <?=$value['rg_dependentePF']?></p>
							    <p class="list-group-item-text">DATA NASC.: <?=date('d/m/Y',strtotime($value['dt_nascimento_dependentePF']))?></p>
							    <p class="list-group-item-text">IDADE: <?=$anos->format('%y')?> Anos</p>
							    <p class="list-group-item-text">DEPENDENTE DE: <?=$opt_cli[$value['id_clientePF']]?></p>
							  </a>
							</div>
					    <?php endforeach; ?>
					       </div>
					    </div>
					    <!-- lista de Dependentes -->
					  </div>
						<!-- Aba de Dependentes-->
					  <?php endif; ?>
					  
					  <!-- Todos Produtos -->
					  <div id="todos_produtos">
					  
					  <?php if(isset($passagens) && count($passagens) > 0): ?>
					  <!-- Aba de Passagens-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTen">Passagens<a>
					      </h4>
					    </div>
					    <div id="collapseTen" class="panel-collapse collapse">
					      <div class="panel-body">
					      <?php foreach($passagens as $key => $value): 
					      	$total_passagens = 0;
					      	?>
							<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">COMPANIA AÉREA: <strong><?=$opt_comp[$value['id_compania']]?></strong></h4>
							    <p class="list-group-item-text">CLIENTE: <strong><?=$opt_cli[$value['id_clientePF']]?></strong></p>
							    <p class="list-group-item-text">CLASSE: <strong><?=$opt_class[$value['id_classe']]?></strong></p>
							    <p class="list-group-item-text">DESTINO: <strong><?=$opt_dest[$value['id_destino']]?></strong></p>
							    <p class="list-group-item-text">ORIGEM: <strong><?=$opt_orig[$value['id_origem']]?></strong></p>
							    <p class="list-group-item-text">MOEDA: <strong><?=$opt_moe[$value['id_moeda']]?></strong></p>
							    <p class="list-group-item-text">VOO: <strong><?=$value['voo_passagens']?></strong></p>
							    <p class="list-group-item-text">DATA IDA: <strong><?=date('d/m/Y',strtotime($value['dataIda_passagens']))?></strong></p>
							    <p class="list-group-item-text">HORA DE SAIDA IDA: <strong><?=$value['saidaIda_passagens']?>hs</strong></p>
							    <p class="list-group-item-text">HORA DE CHEGADA IDA <strong><?=$value['chegadaIda_passagens']?>hs</strong></p>
							    							<?php if($value['dataVolta_passagens']): ?>
							    <p class="list-group-item-text">DATA DE VOLTA: <strong><?=date('d/m/Y',strtotime($value['dataVolta_passagens']))?></strong></p>
							    <p class="list-group-item-text">HORA DE SAIDA VOLTA: <strong><?=$value['saidaVolta_passagens']?>hs</strong></p>
							    <p class="list-group-item-text">HORA DE CHEGADA VOLTA: <strong><?=$value['chegadaVolta_passagens']?>hs</strong></p>
							    							<?php endif; ?>
							    <p class="list-group-item-text">TICKET: <strong><?=$value['ticket_passagens']?></strong></p>
							    <?php 
							    $total_passagens += $value['tarifa_passagens'] + $value['valor_casa_passagens'] + $value['tx_embarque_passagens'] + $value['tx_outras_passagens'] + $value['tx_repasse_passagens'];
							    $total_tudo += $total_passagens;
								$total_comissao += $value['valor_casa_passagens'];
								 ?>
							    <p class="list-group-item-text">TOTAL: R$ <strong><?=number_format($total_passagens,2,',','.')?></strong></p>
							  </a>
							</div>
					      <?php endforeach; ?>


					      </div>
					    </div>
					  </div>
						<!-- Aba de Passagens-->
					  <?php endif; ?>
					  
					  
					  
					  
					  
					  
					  <?php if(isset($hoteis)){ 
					  	$arrayHotel = array();
						foreach($hoteis as $key => $value){
							foreach($value as $hot){
								$arrayHotel[] = $hot;
							}
						}
					  	?>
						<!-- Aba de Hoteis-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Hoteis</a>
					      </h4>
					    </div>
					    <div id="collapseThree" class="panel-collapse collapse">
					      <div class="panel-body">
					       <?php foreach($arrayHotel as $hotel): 
					       	$total_hotel = 0;
					       	?>
								<div class="list-group">
								  <a href="#" class="list-group-item">
								    <h4 class="list-group-item-heading">HOTEL: <?=$hotel['nome_hotel']?></h4>
								    <p class="list-group-item-text">ENDEREÇO: <strong><?=$hotel['endereco_hotel']?></strong></p>
								    <p class="list-group-item-text">UF: <strong><?=$hotel['uf_hotel']?></strong></p>
								    <p class="list-group-item-text">TEL.: <strong><?=$hotel['telefone_hotel']?></strong></p>
								    <p class="list-group-item-text">BROKERS:<strong> <?=$hotel['id_brokers'] != 0 ? $opt_bro[$hotel['id_brokers']] : 'NENHUM' ?></strong></p>
								    <p class="list-group-item-text">CAMBIO: <strong><?=$hotel['id_moeda'] == 0 ? 'REAL BR' : $opt_moe[$hotel['id_moeda']] ?></strong></p>
								    <p class="list-group-item-text">RESERVADO PARA: <strong><?=$opt_cli[$hotel['id_clientePF']]?></strong></p>
								    <?php $total_hotel += $hotel['valor_hotel'] + $hotel['valor_casa_hotel']; 
								    	  $total_tudo += $total_hotel;
										  $total_comissao += $hotel['valor_casa_hotel'];
								    ?>
								    <p class="list-group-item-text">TOTAL: R$ <strong><?=number_format($total_hotel,2,',','.'); ?></strong></p>
								  </a>
								</div>
							<?php endforeach; ?>
					       </div>
					    </div>
					  </div>
						<!-- Aba de Hoteis-->
						<?php } ?>
						
						
						
						
						
						<?php if(isset($vCarros)): 
						$arrayCarros = array();
						foreach($vCarros as $key => $value){
							$arrayCarros[] = $value;
						}	
							?>
						<!-- Aba de Carros-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">Carros<a>
					      </h4>
					    </div>
					    <div id="collapseFour" class="panel-collapse collapse">
					      <div class="panel-body">
							<?php foreach($arrayCarros as $value):
								foreach($value as $car){
									$total_carro = 0;
							 ?>
							<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">LOCADORA: <?=$opt_loc[$car['id_locadora']]?></h4>
							    <p class="list-group-item-text">INICIO: <strong><?=date('d/m/Y - H:i',strtotime($car['dt_inicio_carro']))?>hs</strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y - H:i',strtotime($car['dt_devolucao_carro']))?>hs</strong></p>
							    <p class="list-group-item-text">LOCAL INICIO: <strong><?=$car['local_incio_carro']?></strong></p>
							    <p class="list-group-item-text">LOCAL DEVOLUÇÃO: <strong><?=$car['local_devolucao_carro']?></strong></p>
							    <?php $total_carro += $car['valor_carro'] + $car['valor_casa_carro'] + $car['taxa_carro']; 
							    		$total_tudo += $total_carro;
										$total_comissao += $car['valor_casa_carro'];
							    ?>
							    <p class="list-group-item-text">TOTAL R$ <strong><?=number_format($total_carro,2,',','.')?></strong></p>
							    <p class="list-group-item-text">LOCADO PARA: <strong><?=$opt_cli[$car['id_clientePF']]?></strong></p>
							  </a>
							</div>
					      <?php 
							}
					      endforeach; ?>

					      </div>
					    </div>
					  </div>
						<!-- Aba de Carros-->
						<?php endif; ?>
						
						<?php if(isset($seguros)): 
						$arraySeguro = array();
							foreach($seguros as $key => $value){
								foreach($value as $seguro){
									$arraySeguro[] = $seguro;
								}
							}
						?>
						<!-- Aba de Seguro-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">Seguros<a>
					      </h4>
					    </div>
					    <div id="collapseSix" class="panel-collapse collapse">
					      <div class="panel-body">
					      
					      <?php foreach($arraySeguro as $seg): 
					      	$total_seguro = 0;
					      	?>
					      	<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">SEGURADORA: <?=$opt_seg[$seg['id_seguradora']]?></h4>
							    <p class="list-group-item-text">TIPO DE SEGURO: <strong><?=$opt_tip[$seg['id_tipoSeguro']]?></strong></p>
							    <p class="list-group-item-text">CONTINENTE: <strong><?=$opt_cont[$seg['id_continente']]?></strong></p>
							    <p class="list-group-item-text">MOEDA: <strong><?=$opt_moe[$seg['id_moeda']]?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($seg['dt_inicio_seguro']))?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($seg['dt_fim_seguro']))?></strong></p>
							  	<?php $total_seguro += $seg['valor_seguro'] + $seg['valor_casa_seguro'];
										$total_tudo += $total_seguro;
										$total_comissao += $seg['valor_casa_seguro'];
								 ?>
							    <p class="list-group-item-text">TOTAL R$: <strong><?=number_format($total_seguro,2,',','.')?></strong></p>
							  </a>
							</div>
					      <?php endforeach; ?>
					      
					      
					      </div>
					    </div>
					  </div>
						<!-- Aba de Seguro-->
					  <?php endif; ?>
					  
					  <?php if(isset($compraTickets) && count($compraTickets) > 0): ?>
					  <!-- Aba de Tickets-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">Tickets<a>
					      </h4>
					    </div>
					    <div id="collapseSeven" class="panel-collapse collapse">
					      <div class="panel-body">
					      <?php foreach($compraTickets as $key => $value): 
					      	$total_ticket = 0;
					      	?>
							<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">TICKET: <strong><?=$opt_tic[$value['id_ticket']]?></strong></h4>
							    <p class="list-group-item-text">MOEDA: <strong><?=$opt_moe[$value['id_moeda']]?></strong></p>
							    <p class="list-group-item-text">FORNECEDOR: <strong><?=$value['fornecedor_compraTicket']?></strong></p>
							    <?php $total_ticket += $value['valor_compraTicket'] + $value['comissao_compraTicket'];
										$total_tudo += $total_ticket;
										$total_comissao += $value['comissao_compraTicket'];
								 ?>
							    <p class="list-group-item-text">TOTAL: R$ <strong><?=number_format($total_ticket,2,',','.')?></strong></p>
							    <p class="list-group-item-text">CLIENTE: <strong><?=$opt_cli[$value['id_clientePF']]?></strong></p>
							  </a>
							</div>
						 <?php endforeach; ?>
					      </div>
					    </div>
					  </div>
						<!-- Aba de Tickets-->
						<?php endif; ?>
						
						<?php if(isset($cruzeiros)): ?>
						<!-- Aba de Cruzeiros-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseEight">Cruzeiros<a>
					      </h4>
					    </div>
					    <div id="collapseEight" class="panel-collapse collapse">
					      <div class="panel-body">
					      <?php foreach($cruzeiros as $key => $value):
					      	$total_cruzeiro = 0;
					      	?>
							<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">COMPANIA: <strong><?=$opt_comp[$value['id_compania_cruzeiro']]?></strong></h4>
							    <p class="list-group-item-text">MOEDA: <strong><?=$opt_moe[$value['id_moeda']]?></strong></p>
							    <p class="list-group-item-text">CLIENTE: <strong><?=$opt_cli[$value['id_clientePF']]?></strong></p>
							    <p class="list-group-item-text">NAVIO: <strong><?=$value['navio_cruzeiro']?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_cruzeiro']));?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($value['dt_fim_cruzeiro']));?></strong></p>
							    <p class="list-group-item-text">ROTA: <strong><?=$value['rota_cruzeiro']?></strong></p>
							    <p class="list-group-item-text">CABINE: <strong><?=$value['tipo_cabine_cruzeiro']?></strong></p>
							    <?php $total_cruzeiro += $value['valor_cruzeiro'] + $value['comissao_cruzeiro']; 
							    	$total_tudo += $total_cruzeiro;
							    	$total_comissao += $value['comissao_cruzeiro']; 
							    ?>
							    <p class="list-group-item-text">TOTAL: R$ <strong><?=number_format($total_cruzeiro,2,',','.')?></strong></p>
							  </a>
							</div>
					      <?php endforeach; ?>


					      </div>
					    </div>
					  </div>
						<!-- Aba de Cruzeiros-->
						<?php endif; ?>
						
						<?php if(isset($produtos)): ?>
						<!-- Aba de Outros-->
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseNine">Outros<a>
					      </h4>
					    </div>
					    <div id="collapseNine" class="panel-collapse collapse">
					      <div class="panel-body">
					      <?php foreach($produtos as $key => $value): 
						  	$total_outros = 0;
						  ?>
							<div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading">PRODUTO: <strong><?=$value['titulo_produto']?></strong></h4>
							    <p class="list-group-item-text">FORNECEDOR: <strong><?=$value['fornecedor_produto']?></strong></p>
							    <p class="list-group-item-text">INICIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_produto']))?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($value['dt_final_produto']))?></strong></p>
							    <p class="list-group-item-text">CLIENTE: <strong><?=$opt_cli[$value['id_clientePF']]?></strong></p>
							    <p class="list-group-item-text">MOEDA: <strong><?=$value['id_moeda'] !=0 ? $opt_moe[$value['id_moeda']] : 'Real BR'?></strong></p>
							    <?php $total_outros += $value['valor_produto'] + $value['comissao_produto']; 
							    	  $total_tudo += $total_outros;
									  $total_comissao += $value['comissao_produto'];
							    ?>
							    <p class="list-group-item-text">TOTAL: R$ <strong><?=number_format($total_outros,2,',','.');?></strong></p>
							  </a>
							</div>
					      <?php endforeach; ?>


					      </div>
					    </div>
					  </div>
						<!-- Aba de Cruzeiros-->
						<?php endif; ?>
					 </div> <!-- Todos Produtos -->
					  
					</div>
				</div><!-- End div painel_cliente -->
					<!-- Todos os Produtos -->
					
					<br />
					    <!-- Total de todos os produtos  -->
						
					    <!-- Total de todos os produtos  -->
					    
					    <label>Descrição de venda</label>
						<textarea name="descricao_venda" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<input type="hidden" name="total_venda" value="<?=$total_tudo?>" />
					<input type="hidden" name="total_comissao" value="<?=$total_comissao?>" />
					<button type="button" data-dismiss="modal" id="bt_cancel" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-down"></i> Cancelar</button>
					<button type="submit" id="bt_finalizaVenda" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-up"></i> Confirmar</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	   
		   	<!-- Modal Finalização de Venda -->
	
	
	
		   	<!-- Modal Rateio Venda -->
	<div class="modal fade" id="modalRateio" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Rateio Venda   -   <strong>R$ <?=number_format($total_tudo,2,',','.')?></strong></h4>
				</div>
				<div class="modal-body">
					<?php 
					foreach($tipoPagamento as $tipo){
						 $opt_tipo[$tipo['id_tipoPagamento']] = $tipo['titulo_tipoPagamento'];
					}
					?>
				<form method="post" name="rateio" action="/venda/cadTipoPagamento">
				<input type="hidden" name="id_clientePF" value="" />
				<table class="table">
							    <p class="list-group-item-text"><h3 id="nome_cliente"></h3></p>
							    	<?php foreach($tipoPagamento as $key => $value){ ?>
										<tr>						    			
							    		<?php if($value['titulo_tipoPagamento'] != 'CARTÃO DE CRÉDITO'): ?>
							    			<td><?=$value['titulo_tipoPagamento']?></td>
							    			<td><input type="text" class="fmpgto" name="<?=$value['id_tipoPagamento']?>[]" />
							    				X <input type="text" maxlength="2" style="width:20%" name="vezes_<?=$value['id_tipoPagamento']?>[]" />
							    			</td>
							    		<?php else: ?>
							    			<table id="cartoes_credito" class="table table-bordered"></table>
							    		<?php endif; ?>
							    		</tr>
							    	<?php } ?>
							    		</table>
							</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
								</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		   	<!-- Modal Rateio Venda -->
	
	
	
	
	<!-- Tela de botoes de produtos-->
	<div class="venda_produtos">
		<div class="vend_produtos_left">
			<br />
			<br />
			<p><a href="#" title="Reserva de Hoteis" data-toggle="modal" data-target="#modalHotel" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> HOTEIS</a></p>
			<br />
			<p><a href="#"  data-toggle="modal" data-target="#modalCarros" title="Aluguel de carros" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CARROS</a></p>
			<br />
			<p><a href="#"  data-toggle="modal" data-target="#modalPassagens" title="Reservar passagens aéreas" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> PASSAGENS</a></p>
		</div>
		
		<div class="vend_produtos_right">
			<br />
			<br />
			<p><a href="#" data-toggle="modal" data-target="#modalSeguro" title="Contratar Seguro para viagem" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> SEGURO</a></p>
			<br />
			<p><a href="#" title="Compra de tickets" data-toggle="modal" data-target="#modalTicket" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> TICKETS</a></p>
			<br />
			<p><a href="#" data-toggle="modal" data-target="#modalCruzeiro" title="Compra de cruzeiros atlânticos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CRUZEIROS</a></p>
			<br />
			<p><a href="#" data-toggle="modal" data-target="#modalProdutos" title="Outros Produtos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> Outros</a></p>
		</div>
	</div>
	<!-- Tela de botoes de produtos-->
	<hr />
	
	<hr />
	<br />
	<table class="table table-condensed">
		<?php $total_geral = 0 ?>
			<!-- Cliente da Lista de venda -->
		<?php if(isset($clientes)): 
			foreach($clientes as $key => $value):
				foreach($value as $k => $v){
					$nome_cli[$v['id_clientePF']] = $v['nome_clientePF'];
			?>
			<tr class="warning" id="tr_clientePF">
				<td><?='Cliente: '.$v['nome_clientePF']?></td>
				<!-- <td>Cliente</td> -->
				<td><a href="#"  class="btn btn-info bt_part" id_cliente="<?=$v['id_clientePF']?>" data-toggle="modal" data-target="#modalDependente"><span class="glyphicon glyphicon-plus-sign"></span> Dependentes</a></td>
				<td><a href="#" data-toggle="modal" title="Rateio do cliente" data-target="#modalRateio" id_clientePF="<?=$v['id_clientePF']?>" class="btn btn-info bt_rateio"><span class="glyphicon glyphicon-plus-sign"></span> Rateio</a></td>
				<td><a href="/venda/deleteClientePF/id/<?=$v['id_clientePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_clientePF']?> da lista de venda?')" class="btn btn-danger">Remover</a></td>
			</tr>
		<?php 
				}
			endforeach;
		endif; 
		///Dependentes da lista de venda
		if(isset($dependentes)):
			foreach($dependentes as $key => $value): 
				foreach($value as $k =>  $v){
			?>
			<tr class="warning">
				<?php
				$hoje = new DateTime();
				$niver = new DateTime($v['dt_nascimento_dependentePF']);
				
				$anos = $niver->diff($hoje);
				 ?>
				<td><?='Dependente: '.$v['nome_dependentePF'].' -  '.$anos->format('%y').' Anos de idade' ?></td>
				<td>Dependente</td>
				<td><?=$nome_cli[$v['id_clientePF']]?> </td>
				<td><a href="/venda/deleteDependente/cli/<?=$v['id_clientePF']?>/id/<?=$v['id_dependentePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_dependentePF']?> da lista de venda?')" class="btn btn-danger">Remover</a></td>
			</tr>
			<?php 
				}
			endforeach;	
		endif;
		
		
			### Popula locadoras de carros ###
		if(isset($vCarros) && count($vCarros) != 0):
			foreach($vCarros as $key => $value){
			echo '<tr class="warning">';
				$total_carro = 0;
				foreach($value as $k => $v){
					$total_carro += $v['valor_carro'] + $v['valor_casa_carro'] + $v['taxa_carro'];
					$total_geral += $total_carro;
					echo '<td>Carro: '.$opt_loc[$v['id_locadora']].'</td>';
					echo '<td>'.$opt_cli[$v['id_clientePF']].'</td>';
					echo '<td>R$ '.number_format($total_carro,2,',','.').'</td>';
			 		echo '<td><a href="/carro/deleteCarro/id/'.$v['id_carros'].'/cli/'.$v['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse carro da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				}
					
			echo '</tr>';
			}
			
		endif;	
			### Popula locadoras de carros ###
			
			
		########## Popula hoteis ##############	
		if(isset($hoteis)){
			foreach($hoteis as $key => $value){
				echo '<tr class="warning">';
				$total_hotel = 0;
				foreach($value as $chave => $valor){
					echo '<td>Hotel: '.$valor['nome_hotel'].'</td>';
					echo '<td>'.$opt_cli[$valor['id_clientePF']].'</td>';
					$total_hotel += $valor['valor_hotel'] + $valor['valor_casa_hotel'];
					$total_geral += $total_hotel;
					echo '<td>R$ '.number_format($total_hotel,2,',','.').'</td>';
			 		echo '<td><a href="/hotel/deleteHotel/id/'.$valor['id_hoteis'].'/cli/'.$valor['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Hotel da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				}
				echo '</tr>';
			}
		}
		########## Popula hoteis ##############	
		
		
		########## Popula Seguros ##############
		if(isset($seguros)){
			foreach($seguros as $key => $value){
			echo '<tr class="warning">';
					$total_seguro = 0;
				foreach($value as $chave => $valor){
					echo '<td> Seguradora: '.$opt_seg[$valor['id_seguradora']].' - '.$opt_tip[$valor['id_tipoSeguro']].'</td>';
					echo '<td>'.$opt_cli[$valor['id_clientePF']].'</td>';
					$total_seguro += $valor['valor_seguro'] + $valor['valor_casa_seguro'];
					$total_geral += $total_seguro;
					echo '<td>R$ '.number_format($total_seguro,2,',','.').'</td>';
					echo '<td><a href="/seguro/deleteSeguro/id/'.$valor['id_seguro'].'/cli/'.$valor['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Seguro da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				}	
			echo '</tr>';	
			}
		}	
		########## Popula Seguros ##############
			
		########## Popula Tickets ##############	
		if(isset($compraTickets)){
			foreach($compraTickets as $key => $value){
			$total_tickets = 0;
				echo '<tr class="warning">';
					echo '<td> Tickets: '.$opt_tic[$value['id_ticket']].'</td>';
					echo '<td>'.$opt_cli[$value['id_clientePF']].'</td>';
					$total_tickets += $value['valor_compraTicket'] + $value['comissao_compraTicket'];
					$total_geral += $total_tickets;
					echo '<td>R$ '.number_format($total_tickets,2,',','.').'</td>';
					echo '<td><a href="/compraTicket/deleteCompraTicket/id/'.$value['id_compraTicket'].'/cli/'.$value['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Ticket da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				
				echo '</tr>';
			}
		}
		########## Popula Tickets ##############
		
		
		########## Popula Cruzeiro ##############
		if(isset($cruzeiros)){
			$total_cruzeiro = 0;
			foreach($cruzeiros as $key => $value){
				echo '<tr class="warning">';
				
				echo '<td> Cruzeiro: '.$opt_comp[$value['id_compania_cruzeiro']].' - De: '.date('d/m/Y',strtotime($value['dt_inicio_cruzeiro'])).' Até: '.date('d/m/Y',strtotime($value['dt_fim_cruzeiro'])).' </td>';
				echo '<td>'.$opt_cli[$value['id_clientePF']].'</td>';
				$total_cruzeiro += $value['valor_cruzeiro'] + $value['comissao_cruzeiro'];
				$total_geral += $total_cruzeiro;
				echo '<td>R$ '.number_format($total_cruzeiro,2,',','.').'</td>';
				echo '<td><a href="/cruzeiro/deleteCruzeiro/id/'.$value['id_cruzeiro'].'/cli/'.$value['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Cruzeiro da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				
				echo '</tr>';
			}
		}
		########## Popula Cruzeiro ##############
		
		
		
		########## Popula Produtos ##############
		if(isset($produtos)){
			foreach($produtos as $key => $value){
			$total_produto = 0;
				echo '<tr class="warning">';
				echo '<td>Produto: '.$value['titulo_produto'].' -  '.$opt_cli[$value['id_clientePF']].'</td>';
				echo '<td>De: '.date('d/m/Y',strtotime($value['dt_inicio_produto'])).' Àté: '.date('d/m/Y',strtotime($value['dt_final_produto'])).'</td>';
				$total_produto += $value['valor_produto'] + $value['comissao_produto'];
				$total_geral += $total_produto;
				echo '<td> R$ '.number_format($total_produto,2,',','.').'</td>';
				echo '<td><a href="/produtoOutros/deleteprodutoOutros/id/'.$value['id_produto'].'/cli/'.$value['id_clientePF'].'" onclick="return confirm(\'Deseja remover esse Produto da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				echo '</tr>';
			}
		}
		########## Popula Produtos ##############
		
		
		########## Popula Passagens ##############
		if(isset($passagens)){
			foreach($passagens as $key => $value){
				$total_passagem = 0;
				echo '<tr class="warning">';
				echo '<td>Passagens: '.$opt_comp[$value['id_compania']].'  -   '.$opt_class[$value['id_classe']].'</td>';
				echo '<td>  '.$opt_cli[$value['id_clientePF']].'</td>';
				$total_passagem += $value['tarifa_passagens'] + $value['valor_casa_passagens'] + $value['tx_embarque_passagens'] + $value['tx_outras_passagens'] + $value['tx_repasse_passagens'];
				$total_geral += $total_passagem; 
				echo '<td>'.number_format($total_passagem,2,',','.').'</td>';
				echo '<td><a href="/passagens/deletePassagens/id/'.$value['id_passagens'].'/cli/'.$value['id_clientePF'].'" onclick="return confirm(\'Deseja remover essa passagem da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				echo '</tr>';
			}
		}
		########## Popula Passagens ##############
		
		if(isset($formas)){
			foreach ($formas as $key => $value) {
				$nome = explode(' ', $opt_cli[$value['id_clientePF']]);
				$total_formas = 0;
				echo '<tr class="warning">';
				echo '<td>Rateio:  '.$opt_tipo[$value['id_tipoPagamento']].' - '.$nome[0].'</td>';
				echo '<td> R$ '.number_format($value['valor_formaPagamento'],2,',','.').'</td>';
				echo '<td>'.$value['vezes_formaPagamento'].' X</td>';
				echo '<td><a href="/venda/deleteFormaPagamento/id/'.$value['id_formaPagamento'].'" onclick="return confirm(\'Deseja remover esse Rateio da lista de venda?\')" class="btn btn-danger">Remover</a></td>';
				echo '</tr>';
			}
		}
			
		?>
		<tr class="success">
			<td><strong style="font-size: 20px;">Total Geral:</strong></td>
			<td></td>
			<td></td>
			<td><strong style="font-size: 20px;">R$ <?=number_format($total_geral,2,',','.')?></strong></td>
		</tr>
	</table>
       <button  id="btn_finaliza_venda" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalFinaliza">Finalizar Venda</button>
      </div>
       <br /> 
       <br /> 
       <br /> 
   
<script>
	jQuery(function(){
		
		//Eventos de cliques
		jQuery('#bt_addNew').click(function(){
			location.href="/cliente/cadfisica";
		});
		
		
		
		//evento de buscar cliente montar o modal 
		jQuery('#bt_findCliente').click(function(){
			var nomeCli = jQuery('#nome_clientePF').val();
			var cpfCli = jQuery('#cpf_clientePF').val();
			
			jQuery.ajax({
				url: '/venda/findClientePF',
				type: 'post',
				dataType: 'json',
				data: {nome: nomeCli, cpf: cpfCli},
				success: function(data){
					if(!data.length){
						jQuery(".modal-body").html('<h2>Cliente não foi encontrado!</h2>');
						jQuery("#bt_incluir").attr('disabled',true);
						setTimeout(function(){location.href="/venda/cadVendaPF";},4000);
						
					}else{
						jQuery('#id_PF').val(data[0].id_clientePF);
						jQuery('#cpf_PF').html('CPF: ' +data[0].cpf_clientePF);
						jQuery('#dataNascimento_PF').html('Data de Nasc: ' +format_data(data[0].dataNascimento_clientePF));
						jQuery('#nome_PF').html('Nome: ' +data[0].nome_clientePF);
						jQuery('#endereco_PF').html('Endereço: ' +data[0].endereco_clientePF);
						jQuery('#telefone_PF').html('Telefone: ' +data[0].telefone_clientePF);
						jQuery("#bt_incluir").attr('disabled',false);
					}
				}
			});
		});
		//evento de buscar cliente montar o modal 
		
		
			//Evento para desabilitar botão de busca
			jQuery('#bt_findCliente').attr('disabled',true);
		
			
			//Evento para bloquear botão de busca enquanto campo cpf estiver vázio			
			jQuery('#cpf_clientePF').keypress(function(){
				if(jQuery(this).val().length > 0){
					jQuery('#bt_findCliente').attr('disabled',false);
				}
			});
		
			//Evento para buscar dependentes do cliente pessoa física
			jQuery('.bt_part').click(function(){
				var id_cliente = jQuery(this).attr('id_cliente');
				jQuery.ajax({
					url: '/venda/findDependente',
					type: 'post',
					dataType: 'json',
					data: {id_cliente : id_cliente},
					success: function(data){
						jQuery("#bt_incluirDependente").attr('disabled',false);
						if(data.length){
							jQuery('.dependentePF').html('');
							jQuery('.dependentePF').append('<input type="hidden" name="id_clientePF" value="'+data[0].id_clientePF+'"/>');
							for(var i = 0; i < data.length; i++ ){
								jQuery('.dependentePF').append('<input type="checkbox" name="id_dependentePF[]" value="'+data[i].id_dependentePF+'"/> '+data[i].nome_dependentePF + '<br />');
							}
						}else{
							jQuery(".dependentePF").html('<h3>Esse cliente não tem dependente!</h3>');
							jQuery("#bt_incluirDependente").attr('disabled',true);
						}
						
					}
				});
			});
		
		
		//Mascarando campos
		jQuery('#cpf_clientePF').mask('999.999.999-99');
		
		
		//Funções para o modal Carros
		jQuery("#valor_carro").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_carro").maskMoney({thousands:'', decimal:'.'});
		jQuery("#taxa_carro").maskMoney({thousands:'', decimal:'.'});
		
			if(jQuery('[name=id_clientePF]').find('option').length == 0){
				jQuery('#bt_incluirCarro').attr('disabled',true);
			}else{
				jQuery('#bt_incluirCarro').attr('disabled',false);
			}
			
			jQuery('#valor_cambio_carro').maskMoney({thousands:'', decimal:'.'});
			jQuery('#valor_cambio_carro').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_carro').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_carro').attr('disabled',true);
		 	}
		 });
		//Funções para o modal Carros
		
		
		//Funções do modal de hotel
		jQuery('#cep_hotel').mask('99999-999');
		jQuery('#checkbox').css('margin-left','17%');
		jQuery("#valor_hotel").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_hotel").maskMoney({thousands:'', decimal:'.'});
		jQuery('#is_br').click(function(){
			if(jQuery('#is_br:checked').length > 0){
				jQuery('#cep_hotel').attr('disabled',true);
			}else{
				jQuery('#cep_hotel').attr('disabled',false);
			}
		});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirHotel').attr('disabled',true);
		}else{
			jQuery('#bt_incluirHotel').attr('disabled',false);
		}
		
		jQuery("#cep_hotel").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#endereco_hotel').val(data.endereco);
		 			jQuery('#cidade_hotel').val(data.cidade	);
		 			jQuery('#uf_hotel').val(data.uf);
		 			jQuery('#numero_hotel').focus();
		 			}else{
		 				jQuery('#msg_cep').html('CEP Não encontrado!');
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		 
		 jQuery('#valor_cambio_hotel').maskMoney({thousands:'', decimal:'.'});
		 jQuery('#valor_cambio_hotel').attr('disabled',true);
		 jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_hotel').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_hotel').attr('disabled',true);
		 	}
		 });
		
		//Funções do modal de hotel
		
		
		//Funções do modal de Seguro
		jQuery('#valor_seguro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_casa_seguro').maskMoney({thousands:'', decimal:'.'});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirSeguro').attr('disabled',true);
		}else{
			jQuery('#bt_incluirSeguro').attr('disabled',false);
			
		}
		
		jQuery('#valor_cambio_seguro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_seguro').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_seguro').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_seguro').attr('disabled',true);
		 	}
		 });
		//Funções do modal de Seguro
		
		
		//Funções do Modal de Tickets
		jQuery('#valor_compraTicket').maskMoney({thousands:'', decimal:'.'});
		jQuery('#comissao_compraTicket').maskMoney({thousands:'', decimal:'.'});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirTicket').attr('disabled',true);
		}else{
			jQuery('#bt_incluirTicket').attr('disabled',false);
			
		}
		
		jQuery('#valor_cambio_compraTicket').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_compraTicket').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_compraTicket').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_compraTicket').attr('disabled',true);
		 	}
		 });
		//Funções do Modal de Tickets
		
		
		//Funções do Modal de Cruzeiro
		jQuery('#valor_cruzeiro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#comissao_cruzeiro').maskMoney({thousands:'', decimal:'.'});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirCruzeiro').attr('disabled',true);
		}else{
			jQuery('#bt_incluirCruzeiro').attr('disabled',false);
			
		}
		
		jQuery('#valor_cambio_cruzeiro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_cruzeiro').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_cruzeiro').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_cruzeiro').attr('disabled',true);
		 	}
		 });
		//Funções do Modal de Cruzeiro
		
		//Funções do Modal de Outros Produtos
		jQuery('#valor_produto').maskMoney({thousands:'', decimal:'.'});
		jQuery('#comissao_produto').maskMoney({thousands:'', decimal:'.'});
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirProdutos').attr('disabled',true);
		}else{
			jQuery('#bt_incluirProdutos').attr('disabled',false);
		}
		
		jQuery('#valor_cambio_cruzeiro').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_cruzeiro').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_cruzeiro').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_cruzeiro').attr('disabled',true);
		 	}
		 });
		//Funções do Modal de Outros Produtos
		
		
		
		//Funções do Modal de passagens
		jQuery('#tarifa_passagens').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_casa_passagens').maskMoney({thousands:'', decimal:'.'});
		jQuery('#tx_embarque_passagens').maskMoney({thousands:'', decimal:'.'});
		jQuery('#tx_outras_passagens').maskMoney({thousands:'', decimal:'.'});
		jQuery('#tx_repasse_passagens').maskMoney({thousands:'', decimal:'.'});
		
		
		
		if(jQuery('[name=id_clientePF]').find('option').length == 0){
			jQuery('#bt_incluirPassagens').attr('disabled',true);
		}else{
			jQuery('#bt_incluirPassagens').attr('disabled',false);
		}
		
		jQuery('#somente_ida').click(function(){
			if(jQuery(this).attr('checked')){
				jQuery('#fs_volta').attr('disabled',true);
				jQuery('#fs_volta').hide('slow');
			}else{
				jQuery('#fs_volta').attr('disabled',false);
				jQuery('#fs_volta').show('slow');
			}
		});
		//Iniciar somente ida selecionado
		jQuery('#somente_ida').attr('checked',true);
		jQuery('#fs_volta').hide('slow');
		
		
		jQuery('#valor_cambio_passagens').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_passagens').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_passagens').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_passagens').attr('disabled',true);
		 	}
		 });
		//Funções do Modal de passagens
		
		
		//Funções de todos produtos
		if(jQuery('#todos_produtos').find('.panel').length){
			jQuery('#bt_finalizaVenda').attr('disabled',false);
		}else{
			jQuery('#bt_finalizaVenda').attr('disabled',true);
			
		}
		
		jQuery('#valor_cambio_produto').maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio_produto').attr('disabled',true);
		 	jQuery('[name=id_moeda]').change(function(){
		 	if(jQuery(this).val() != 0){
		 		jQuery('#valor_cambio_produto').attr('disabled',false);
		 	}else{
		 		jQuery('#valor_cambio_produto').attr('disabled',true);
		 	}
		 });
		
		
		//Popula agentes
		jQuery('#id_agente').hide();
		jQuery('#lb_agente').hide();
		jQuery('[name=id_agencia]').change(function(){
			var id_agencia = jQuery(this).val();
			jQuery.ajax({
				url: '/venda/getAgente',
				type: 'post',
				dataType: 'json',
				data: {id_agencia: id_agencia},
				success: function(data){
					if(data.length){
						jQuery('#id_agente').show();
						jQuery('#id_agente').html('');
						
						for(var i = 0; i < data.length; i++){
							jQuery('#lb_agente').show();
							jQuery('#id_agente').append('<option value="'+data[i].id_agente+'">'+data[i].nome_agente+'</option>');
						}
					}else{
						jQuery('#lb_agente').hide();
						jQuery('#id_agente').hide();
					}
				}
			});
		});
		
			var total_geral = jQuery('#total_geral').text();
			jQuery('.fmpgto').maskMoney({thousands:'', decimal:'.'});
			
			
			if(jQuery('.table').find('#tr_clientePF').length){
				jQuery('#btn_finaliza_venda').attr('disabled',false);
			}else{
				jQuery('#btn_finaliza_venda').attr('disabled',true);
				
			}
			
			
			
			//############# Botão para montagem do formulário de Rateio ###########
			jQuery('.bt_rateio').click(function(){
				var id_clientePF = jQuery(this).attr('id_clientePF');
				jQuery.ajax({
					url: '/venda/getClientePF',
					type: 'post',
					dataType: 'json',
					data: {id_clientePF : id_clientePF},
					success: function(data){
						jQuery('#nome_cliente').html(data.nome_clientePF);
						jQuery('[name=id_clientePF]').val(id_clientePF);
					},
					complete: function(){
						jQuery.ajax({
							url: '/venda/getTipoCartao',
							type: 'post',
							dataType: 'json',
							data:{id_clientePF : id_clientePF},
							success:function(data){
								jQuery('#cartoes_credito').html('');
								for(var i = 0; i < data.length; i++){
									jQuery('#cartoes_credito').append('<tr><td>'+data[i].titulo_tipoCartao+'</td><td><input type="text" class="fmpgto" name="3_'+data[i].id_tipoCartao+'" /></td>  <td> <input type="text" class="fmpgto" name="3_'+ data[i].id_tipoCartao+'_vezes_pgto" maxlength="2" style="width: 30%" /> Vezes</td></tr>');
									jQuery('[name=3_'+data[i].id_tipoCartao+']').maskMoney({thousands:'', decimal:'.'});
								}
							}
						});
					}
				});
				
			});
			//############# Botão para montagem do formulário de Rateio ###########
			
			jQuery('#bt_finalizaVenda').click(function(){
				if(confirm('As informações mostradas estão corretas?')){
					return true;
				}else{
					return false;
				}
			});
			
			
		//Funções de todos produtos
		
		//Efeito de finaliza venda
				jQuery('#lb_vl_agencia').hide();
				jQuery('[name=valor_agencia]').hide();
				jQuery('[name=valor_agencia]').maskMoney({thousands:'', decimal:'.'});
				jQuery('#lb_valor_agente').hide();
				jQuery("[name=valor_agente]").hide();
				jQuery('[name=valor_agente]').maskMoney({thousands:'', decimal:'.'});
				jQuery('.faturado').hide();
		
		jQuery('[name=id_agencia]').change(function(){
			if(jQuery(this).val() == '0'){
				jQuery('#lb_vl_agencia').hide();
				jQuery('[name=valor_agencia]').hide();
				jQuery('#lb_valor_agente').hide();
				jQuery("[name=valor_agente]").hide();
				jQuery('.faturado').hide();
			}else{
				jQuery('#lb_vl_agencia').show();
				jQuery('[name=valor_agencia]').show();
				jQuery('#lb_valor_agente').show();
				jQuery("[name=valor_agente]").show();
				jQuery('.faturado').show();
			}
		});
		
		
		
		//Função para formatar data no padrão brasileiro
		function format_data(data){
					var dia = data.split("-")[2];
					var mes = data.split("-")[1];
					var ano = data.split('-')[0];
					
					return dia + '/' + mes + '/' + ano;
				}
		
	});
</script>