<div class="venda">
	

       <?php
       if(isset($_SESSION['success'])){
       	echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
       }
	   
	    if(isset($_SESSION['error'])){
       	echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
       }

		 // session_destroy();
		$this->dump($_SESSION);
		
		// if(isset($dependentes))
		// $this->dump($dependentes);
		
       $form->init('form_addClientePF','addClientePF','post');
		
	    $form->input(array(
				'name' =>'cpf_clientePF',
				'type' =>'text',
				'placeholder' => 'CPF do Cliente',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'CPF',
				'value' => '',
				'required' => false
				));
				
		echo '<button type="button" id="bt_findCliente"  data-toggle="modal" data-target="#myModal" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Buscar</button>';
		echo ' ';
		echo '<button type="button" id="bt_addNew" class="btn btn-primary"><i class="glyphicon glyphicon-user"></i> Novo</button>';
		$form->groupClose();

        $form->close(); ?>
       
      	<!-- Modal cliente Pessoa Física -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Cliente Cadastrado</h4>
				</div>
				<div class="modal-body">
						<form method="post" action="/venda/addClientePF">
						<input id="id_PF" name="id_PF" type="hidden">
						<!-- <select name="id_participacao"> -->
							<?php foreach($participacao as $part):  ?>
								<input type="radio" name="id_participacao" value="<?=$part['id_participacao']?>"><?=$part['titulo_participacao']?>&nbsp;&nbsp;
								<!--<option value="<?=$part['id_participacao']?>"><?=$part['titulo_participacao']?></option> -->
							<?php endforeach;  ?>
						<!-- </select> -->
						<br />
						<hr />
						<div id="nome_PF"></div>
						<div id="cpf_PF"></div>
						<div id="dataNascimento_PF"></div>
						<div id="endereco_PF"></div>
						<div id="telefone_PF"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
					<button type="submit" id="bt_incluir" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	   	<!-- Modal dependente cliente -->
	<div class="modal fade" id="modalDependente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Dependentes</h4>
				</div>
				<div class="modal-body">
				<form method="post" action="/venda/addDependente">
				<div class="dependentePF">	</div>
						
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirDependente" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	<br />
	<br />
	<br />
	<table class="table table-condensed">
		<?php if(isset($clientes)): 
			foreach($clientes as $key => $value):
				
				foreach($value as $k => $v){
					$nome_cli[$v['id_clientePF']] = $v['nome_clientePF'];
			?>
			<tr class="warning">
				<td><?=$v['nome_clientePF']?></td>
				<td>Cliente</td>
				<td><a href="#"  class="btn btn-info bt_part" id_cliente="<?=$v['id_clientePF']?>" data-toggle="modal" data-target="#modalDependente"><span class="glyphicon glyphicon-plus-sign"></span> Dependentes</a></td>
				<td><a href="/venda/deleteClientePF/id/<?=$v['id_clientePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_clientePF']?> da lista de venda?')" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
			</tr>
		<?php 
				}
			endforeach;
		endif; 
		
		if(isset($dependentes)):
			foreach($dependentes as $key => $value): 
				foreach($value as $k =>  $v){
			?>
			<tr class="success">
				<td><?=$v['nome_dependentePF'] ?></td>
				<td>Dependente</td>
				<td><?=$nome_cli[$v['id_clientePF']]?></td>
				<td><a href="/venda/deleteDependente/cli/<?=$v['id_clientePF']?>/id/<?=$v['id_dependentePF']?>" onclick="return confirm('Deseja remover <?=$v['nome_dependentePF']?> da lista de venda?')" class="btn btn-warning"><span class="glyphicon glyphicon-trash"></span></a></td>
			</tr>
			<?php 
				}
			endforeach;	
		endif;	
		?>
	</table>
       
      </div>
        
   
<script>
	jQuery(function(){
		
		//Eventos de cliques
		jQuery('#bt_addNew').click(function(){
			location.href="/cliente/cadfisica";
		});
		
		
		//evento de buscar cliente montar o modal 
		jQuery('#bt_findCliente').click(function(){
			var nomeCli = jQuery('#nome_clientePF').val();
			var cpfCli = jQuery('#cpf_clientePF').val();
			
			jQuery.ajax({
				url: '/venda/findClientePF',
				type: 'post',
				dataType: 'json',
				data: {nome: nomeCli, cpf: cpfCli},
				success: function(data){
					if(data == ''){
						jQuery(".modal-body").html('<h2>Cliente não foi encontrado!</h2>');
						jQuery("#bt_incluir").attr('disabled',true);
					}
						jQuery('#id_PF').val(data[0].id_clientePF);
						jQuery('#cpf_PF').html('CPF: ' +data[0].cpf_clientePF);
						jQuery('#dataNascimento_PF').html('Data de Nasc: ' +format_data(data[0].dataNascimento_clientePF));
						jQuery('#nome_PF').html('Nome: ' +data[0].nome_clientePF);
						jQuery('#endereco_PF').html('Endereço: ' +data[0].endereco_clientePF);
						jQuery('#telefone_PF').html('Telefone: ' +data[0].telefone_clientePF);
						jQuery("#bt_incluir").attr('disabled',false);
				}
			});
		});
		
		
			//Evento para desabilitar botão de busca
			jQuery('#bt_findCliente').attr('disabled',true);
		
			
			//Evento para bloquear botão de busca enquanto campo cpf estiver vázio			
			jQuery('#cpf_clientePF').keypress(function(){
				if(jQuery(this).val().length > 0){
					jQuery('#bt_findCliente').attr('disabled',false);
				}
			});
		
			//Evento para buscar dependentes do cliente pessoa física
			jQuery('.bt_part').click(function(){
				var id_cliente = jQuery(this).attr('id_cliente');
				jQuery.ajax({
					url: '/venda/findDependente',
					type: 'post',
					dataType: 'json',
					data: {id_cliente : id_cliente},
					success: function(data){
						jQuery("#bt_incluirDependente").attr('disabled',false);
						if(data.length){
							jQuery('.dependentePF').html('');
							jQuery('.dependentePF').append('<input type="hidden" name="id_clientePF" value="'+data[0].id_clientePF+'"/>');
							for(var i = 0; i < data.length; i++ ){
								jQuery('.dependentePF').append('<input type="checkbox" name="id_dependentePF[]" value="'+data[i].id_dependentePF+'"/> '+data[i].nome_dependentePF + '<br />');
							}
						}else{
							jQuery(".dependentePF").html('<h3>Esse cliente não tem dependente!</h3>');
							jQuery("#bt_incluirDependente").attr('disabled',true);
						}
						
					}
				});
			});
		
		jQuery('#bt_sairDependente').click(function(){
			
		});
		
		//Mascarando campos
		jQuery('#cpf_clientePF').mask('999.999.999-99');
		
		//Função para formatar data no padrão brasileiro
		function format_data(data){
					var dia = data.split("-")[2];
					var mes = data.split("-")[1];
					var ano = data.split('-')[0];
					
					return dia + '/' + mes + '/' + ano;
				}
		
	});
</script>