<div class="container">
	<div class="content_form">
		<center>
		<div class="logo_login">
			<img src="/skin/img/logo-sys.png" width="150" height="120" />
		</div>
		<div class="label_login">
			<label>LOGIN</label>
		</div>
		</center>
		<form name="form_login" method="post" action="/login/validar" id="form_login">
			<input type="text" name="usuario_login" value=""  id="usuario_login" placeholder="Usuário"/>
			<input type="password" name="senha_login" value=""  id="senha_login" placeholder="Senha"/>
			<br />
			<center>
				<button type="submit" class="btn btn-primary" id="submit_login">
					Entrar
				</button>
			</center>
		</form>
	</div>
	<br />
	<br />
 <?php 
	  if(isset($_SESSION['error'])){
       	echo '<div class="alert alert-danger"><center>'.$this->session->getFlashMessage('error').'</center></div>';
       }
 ?>
</div>

<script>
	jQuery(function(){
		var w = jQuery(window).width();
		if(w < 1000){
			jQuery('.content_form').css('width','50%');
		}else if(w < 400){
			jQuery('.content_form').css('width','100%');
			jQuery('#submit_login').css('padding','10%');
		}
	});
</script>