<?php
$id = isset($companiaCruzeiros) ? $companiaCruzeiros['id_compania_cruzeiro'] : null;
			$form->init('form_companiacruzeiro','/companiaCruzeiro/saveCompaniaCruzeiro');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_compania_cruzeiro',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $id,
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'nome_compania_cruzeiro',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Nome',
				'value' => isset($companiaCruzeiros) ? $companiaCruzeiros['nome_compania_cruzeiro'] : null,
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();
			$form->select(array('1'=>'Ativo','0'=>'Inativo'),'status_compania_cruzeiro','Status',isset($companiaCruzeiros) ? $companiaCruzeiros['status_compania_cruzeiro'] : 1);
			$form->groupClose();
		
			$form->textarea('descricao_compania_cruzeiro','Descriçao',isset($companiaCruzeiros) ? $companiaCruzeiros['descricao_compania_cruzeiro'] : null,'Descriçao',2,5);
			echo str_repeat('<br />',3);
			$form->groupOpen();		
			$form->submit('Salvar','style="padding:5% 13%"');
			$form->groupClose();
			$form->close();