<?php
	$form->init('form_compraticket','/compraticket/saveCompraTicket');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_compraTicket',
				'type' =>'hidden',
				'placeholder' => 'id_compraTicket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_compraTicket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_ticket',
				'type' =>'hidden',
				'placeholder' => 'id_ticket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_ticket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_moeda',
				'type' =>'hidden',
				'placeholder' => 'id_moeda',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_moeda',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'comissao_compraTicket',
				'type' =>'hidden',
				'placeholder' => 'comissao_compraTicket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'comissao_compraTicket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_compraTicket',
				'type' =>'text',
				'placeholder' => 'valor_compraTicket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'valor_compraTicket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_compraTicket',
				'type' =>'text',
				'placeholder' => 'voucher_compraTicket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'voucher_compraTicket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'fornecedor_compraTicket',
				'type' =>'text',
				'placeholder' => 'fornecedor_compraTicket',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'fornecedor_compraTicket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
echo str_repeat('<br />',3);
								$form->groupOpen();		
								$form->submit('Salvar','style="padding:5% 13%"');
								$form->groupClose();
$form->close();