<div class="cli_fisica">
<form name="form_clifisica" action="post" action="#" id="form_clifisico" role="form" class="form-horizontal">
	 <fieldset id="fs_form_pf">
	 	
	 
	<div class="form-group">
    <label for="nome_clientePF" style="color: #797676;" class="col-sm-1 control-label">*Nome</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="nome_clientePF">
    </div>
  </div>
  
  
  
  
  
 
 
	
	 </fieldset>
	 
	 <br />
	  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
	
</form>
</div>