<center>
	
<div class="row">
	  <div class="col-md-6">
	  	<h3>Cliente Pessoa Física</h3>
		<a href="/cliente/fisica" class="btn btn-success btn-lg" id="btn_pf">Pessoa Física</a>
		<a href="/dependente/dependentePF" class="btn btn-info btn-lg" id="btn_pf">Dependente</a>
	  </div>

	<div class="col-md-6">
	  	<h3>Cliente Pessoa Jurídica</h3>
		<a href="/cliente/juridica" class="btn btn-primary btn-lg" id="btn_pj">Pessoa Jurídica</a>
		<a href="/funcionario" class="btn btn-info btn-lg" id="btn_pj">Funcionário</a>
		<a href="/departamento" class="btn btn-warning btn-lg" id="btn_pj">Departamento</a>
	</div>
</div>
</center>
