<div class="form_cli_pj">
	<fieldset id="form_clientePJ">
		<h3 style="color: #c7187d">Cadastro de Empresa</h3>
		<br />
<?php

	$form->init('form_cli_pj','/cliente/saveJuridica');	
	
		######## Logotipo ##########
		$form->groupOpen();	
		$form->input(array(
						'name' =>'logotipo_clientePJ',
						'type' =>'file',
						'placeholder' => 'Logotipo',
						'num_label' =>'2',
						'num_input' =>'5',
						'label' =>'Logotipo',
						'value' =>'',
						'required' => false
						));
		$form->groupClose();					
					
						
		########## Razão Social ############
		$form->groupOpen();	
		$form->input(array(
					'name' =>'razaosocial_ClientePJ',
					'type' =>'text',
					'placeholder' => 'Razão Social',
					'num_label' =>'2',
					'num_input' =>'8',
					'label' =>'Razão Social',
					'value' =>'',
					'required' => false
					));
		$form->groupClose();		
		
		
		######### Nome Fantasia	############	
		$form->groupOpen();		
		$form->input(array(
						'name' =>'nomefantasia_clientePJ',
						'type' =>'text',
						'placeholder' => 'Razão Social',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Nome Fantasia',
						'value' =>'',
						'required' => true
						));
		$form->groupClose();
	
	
		######### CNPJ	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'cnpj_clientePJ',
						'type' =>'text',
						'placeholder' => 'CNPJ',
						'num_label' =>'2',
						'num_input' =>'5',
						'label' =>'* CNPJ',
						'value' =>'',
						'required' => true
						));		
		$form->groupClose();		
				
		######### CEP	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'cep_clientePJ',
						'type' =>'text',
						'placeholder' => 'CEP',
						'num_label' =>'2',
						'num_input' =>'2',
						'label' =>'* CEP',
						'value' =>'',
						'required' => true
						));		
		$form->groupClose();
		
						
		######### Endereço	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'endereco_clientePJ',
						'type' =>'text',
						'placeholder' => 'Endereço',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Endereço',
						'value' =>'',
						'required' => true
						));		
		$form->groupClose();		
										
										
		######### Número e Complemento ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'numero_clientePJ',
						'type' =>'text',
						'placeholder' => 'Número',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Número',
						'value' =>'',
						'required' => false
						));
		$form->input(array(
						'name' =>'complemento_clientePJ',
						'type' =>'text',
						'placeholder' => 'Complemento',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' Complemento',
						'value' =>'',
						'required' => false
						));
		$form->groupClose();
		
		
		######### Bairro e cidade ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'bairro_clientePJ',
						'type' =>'text',
						'placeholder' => 'Bairro',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Bairro',
						'value' =>'',
						'required' => true
						));
		$form->input(array(
						'name' =>'cidade_clientePJ',
						'type' =>'text',
						'placeholder' => 'Cidade',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' Cidade',
						'value' =>'',
						'required' => false
						));
		$form->groupClose();
		
		
		######### UF - Pais ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'uf_clientePJ',
						'type' =>'text',
						'placeholder' => 'UF',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' UF',
						'value' =>'',
						'required' => false
						));
		$form->input(array(
						'name' =>'pais_clientePJ',
						'type' =>'text',
						'placeholder' => 'País',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' País',
						'value' =>'',
						'required' => false
						));
		$form->groupClose();
				
										
		######### Telefone	############		
		$form->groupOpen();		
		$form->input(array(
								'name' =>'telefone_clientePJ',
								'type' =>'text',
								'placeholder' => 'Telefone',
								'num_label' =>'2',
								'num_input' =>'3',
								'label' =>'* Telefone',
								'value' =>'',
								'required' => true
								));
		$form->input(array(
								'name' =>'telefone2_clientePJ',
								'type' =>'text',
								'placeholder' => 'Telefone',
								'num_label' =>'2',
								'num_input' =>'3',
								'label' =>' Telefone 2',
								'value' =>'',
								'required' => FALSE
								));	
		$form->groupClose();		
								
								
		######### email	############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'email_clientePJ',
						'type' =>'text',
						'placeholder' => 'E-mail',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* E-mail',
						'value' =>'',
						'required' => true
						));	
		$form->groupClose();		
								
		echo '<hr>';						
		
		######### Nome responsavel	############	
		$form->groupOpen();		
		$form->input(array(
						'name' =>'nomeresponsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'Nome Responsável',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Nome Responsável',
						'value' =>'',
						'required' => true
						));
						$form->groupClose();
						
		$form->groupOpen();		
		$form->input(array(
						'name' =>'email_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'Email Responsável',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Email Responsável',
						'value' =>'',
						'required' => true
						));
		$form->groupClose();
		
		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'rg_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'RG Responsável',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* RG Responsável',
						'value' =>'',
						'required' => true
						));
		$form->input(array(
						'name' =>'cpf_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'CPF Responsável',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* CPF Responsável',
						'value' =>'',
						'required' => true
						));
		$form->groupClose();


		$form->groupOpen();	
		$form->input(array(
						'name' =>'credito_clientePJ',
						'type' =>'text',
						'placeholder' => 'Créditos R$:',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Créditos',
						'value' =>'',
						'required' => true
						));	
		$form->select(array('1' =>'Ativo','0' =>'Inativo'),'status_clientePJ','Status','1');
		$form->groupClose();

		$form->groupOpen();		
		$form->textarea('descricao_clientePJ','Descrição','','Descrição',2,8);
		$form->groupClose();

		
				
	echo str_repeat('<br />',3);

	$form->groupOpen();		
	$form->submit('Salvar','style="padding:5% 13%"');
	$form->groupClose();		
	
	$form->close();	
	
?>
</fieldset>
</div>
<script>
	jQuery(function(){
		jQuery('#nomefantasia_clientePJ').css('text-transform','uppercase');
		
		jQuery("#credito_clientePJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#cep_clientePJ").mask('99999-999');
		jQuery("#telefone_clientePJ").mask('(99)9999-9999');
		jQuery("#telefone2_clientePJ").mask('(99)9999-9999');
		jQuery("#cnpj_clientePJ").mask('99.999.999/9999-99');
		jQuery("#rg_responsavel_clientePJ").mask('99.999.999-9');
		jQuery("#cpf_responsavel_clientePJ").mask('999.999.999-99');
		
		
		jQuery("#cep_clientePJ").blur(function(){
			if(jQuery(this).val() != ''){
				jQuery.ajax({
					url: '/cliente/findCep',
					type: 'post',
					dataType: 'json',
					data: {cep: jQuery(this).val()},
					beforeSend: function(){
						jQuery('#form_clientePJ').attr('disabled',true);
					},
					success: function(data){
						jQuery('#form_clientePJ').attr('disabled',false);
						jQuery('#endereco_clientePJ').val(data.endereco);
						jQuery('#bairro_clientePJ').val(data.bairro);
						jQuery('#cidade_clientePJ').val(data.cidade);
						jQuery('#uf_clientePJ').val(data.uf);
						jQuery('#pais_clientePJ').val('Brasil');
						jQuery('#numero_clientePJ').focus();
					}
				});
			}
		});
		
		
	});
</script>