<h3 style="color: #C7187D">Cadastro de Funcionário</h3>
<br />
<div class="form_dependentePJ">
	<fieldset>
<?php 

// $this->dump($empresas);
$form->init('form_func','/funcionario/saveFuncionario');	

foreach($empresas as $cli){
	if($cli['tipo_cliente'] == '2'){
		$opt_cli[$cli['id_clientePF']] = $cli['nomefantasia_clientePJ'];
	}
}
// 
foreach($classificacao as $clas){
	$opt_class[$clas['id_classificacao']] = $clas['titulo_classificacao'];
}

$form->groupOpen();
$form->select($opt_cli,'id_clientePF','Cliente','1',2,4);
$form->groupClose();

$form->groupOpen();
$form->select(array(),'id_departamento','Departamento','1',2,2);
$form->groupClose();

$form->groupOpen();
$form->select($opt_class,'id_classificacao','Classificação','1',2,2);
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'nome_dependente',
		'type' =>'text',
		'placeholder' => 'Nome',
		'num_label' =>'2',
		'num_input' =>'5',
		'label' =>'Nome',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'dt_nascimento_dependente',
		'type' =>'text',
		'placeholder' => 'Data de Nasc.',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'Data de Nasc.',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'cpf_dependente',
		'type' =>'text',
		'placeholder' => 'CPF',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'CPF',
		'value' =>'',
		'required' => true
		));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
		'name' =>'rg_dependente',
		'type' =>'text',
		'placeholder' => 'RG',
		'num_label' =>'1',
		'num_input' =>'3',
		'label' =>'RG',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'telefone_dependente',
		'type' =>'text',
		'placeholder' => 'Telefone',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'Telefone',
		'value' =>'',
		'required' => true
		));
// $form->groupClose();
// // 
// $form->groupOpen();	
$form->input(array(
		'name' =>'celular_dependente',
		'type' =>'text',
		'placeholder' => 'Celular',
		'num_label' =>'1',
		'num_input' =>'3',
		'label' =>'Celular',
		'value' =>'',
		'required' => false
		));
$form->groupClose();


$form->groupOpen();	
$form->input(array(
		'name' =>'cep_dependente',
		'type' =>'text',
		'placeholder' => 'CEP',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'CEP',
		'value' =>'',
		'required' => false
		));
echo '<div class="msg_cep"></div>';
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'endereco_dependente',
		'type' =>'text',
		'placeholder' => 'Endereço',
		'num_label' =>'2',
		'num_input' =>'5',
		'label' =>'Endereço',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'numero_dependente',
		'type' =>'text',
		'placeholder' => 'Número',
		'num_label' =>'2',
		'num_input' =>'2',
		'label' =>'Número',
		'value' =>'',
		'required' => true
		));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
		'name' =>'complemento_dependente',
		'type' =>'text',
		'placeholder' => 'Complemento',
		'num_label' =>'2',
		'num_input' =>'2',
		'label' =>'Complemento',
		'value' =>'',
		'required' => false
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'bairro_dependente',
		'type' =>'text',
		'placeholder' => 'Bairro',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'Bairro',
		'value' =>'',
		'required' => true
		));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
		'name' =>'cidade_dependente',
		'type' =>'text',
		'placeholder' => 'Cidade',
		'num_label' =>'1',
		'num_input' =>'3',
		'label' =>'Cidade',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'uf_dependente',
		'type' =>'text',
		'placeholder' => 'UF',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'UF',
		'value' =>'',
		'required' => true
		));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
		'name' =>'pais_dependente',
		'type' =>'text',
		'placeholder' => 'Pais',
		'num_label' =>'1',
		'num_input' =>'3',
		'label' =>'Pais',
		'value' =>'',
		'required' => true
		));
$form->groupClose();


$form->groupOpen();	
$form->input(array(
		'name' =>'email_dependente',
		'type' =>'text',
		'placeholder' => 'Email',
		'num_label' =>'2',
		'num_input' =>'5',
		'label' =>'Email',
		'value' =>'',
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'numero_passaporte_dependente',
		'type' =>'text',
		'placeholder' => 'Nº Passaporte',
		'num_label' =>'2',
		'num_input' =>'3',
		'label' =>'Nº Passaporte',
		'value' =>'',
		'required' => false
		));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
				'name' =>'dt_validade_passaporte_dependente',
				'type' =>'text',
				'placeholder' => 'Data Validade',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'Validade',
				'value' =>'',
				'required' => false
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'foto_dependente',
				'type' =>'file',
				'placeholder' => 'Foto',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Foto',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'copia_rg_dependente',
				'type' =>'file',
				'placeholder' => 'Cópia RG',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Cópia RG',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'copia_cpf_dependente',
				'type' =>'file',
				'placeholder' => 'Cópia CPF',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Cópia CPF',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();



$form->groupOpen();
$form->select(array('1'=>'ATIVO','0'=>'INATIVO'),'status_dependente','Status','1',2,2);
$form->groupClose();

$form->textarea('descricao_dependente','Descrição','','Descrição',2,5);

echo str_repeat('<br />',3);

	$form->groupOpen();		
	$form->submit('Salvar','style="padding:5% 13%"');
	$form->groupClose();

$form->close();
?>
</fieldset>
</div>
<script>
	jQuery(function(){
		jQuery('#nome_dependentePF').css('text-transform','uppercase');
		jQuery('#dt_nascimento_dependente').mask('99/99/9999');
		jQuery('#cpf_dependente').mask('999.999.999-99');
		jQuery('#rg_dependente').mask('99.999.999-9');
		jQuery('#telefone_dependente').mask('(99) 9999-9999');
		jQuery('#celular_dependente').mask('(99) 9999-9999');
		jQuery('#dt_validade_passaporte_dependente').mask('99/99/9999');
		jQuery('#cep_dependente').mask('99999-999');
		
		jQuery("#cep_dependente").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		beforeSend: function(){
		 			jQuery('#form_dependentePJ').attr('disabled',true);
		 		},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#form_dependentePJ').attr('disabled',false);
		 			jQuery('#endereco_dependente').val(data.endereco);
		 			jQuery('#bairro_dependente').val(data.bairro);
		 			jQuery('#cidade_dependente').val(data.cidade	);
		 			jQuery('#uf_dependente').val(data.uf);
		 			jQuery('#pais_dependente').val('Brasil');
		 			jQuery('#numero_dependente').focus();
		 				
		 			}else{
			 			jQuery('#form_dependentePJ').attr('disabled',false);
		 				jQuery('.msg_cep').html('CEP Não encontrado!');
		 				jQuery('#endereco_clientePF').focus();
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		 
		 //Popular departamento ao carregar página
		 var id_clientePJ = jQuery('[name=id_clientePF]').val();
		 jQuery.ajax({
		 	url:'/funcionario/getDepartamento',
		 	type:'post',
		 	dataType: 'json',
		 	data: {id_clientePF : id_clientePJ},
		 	success: function(data){
		 		if(data){
		 			jQuery('[name=id_departamento]').html('');
		 			for(var i = 0; i < data.length; i++){
		 				jQuery('[name=id_departamento]').append('<option value="'+data[i].id_departamento+'">'+data[i].nome_departamento+'</option>');
		 			}
		 		}
		 	}
		 });
		 
		 
		 //Popular Página ao mudar de empresa
		 jQuery('[name=id_clientePJ]').change(function(){
			 	 jQuery.ajax({
		 	url:'/funcionario/getDepartamento',
		 	type:'post',
		 	dataType: 'json',
		 	data: {id_clientePF : id_clientePJ},
		 	success: function(data){
		 		if(data){
		 			jQuery('[name=id_departamento]').html('');
		 			for(var i = 0; i < data.length; i++){
		 				jQuery('[name=id_departamento]').append('<option value="'+data[i].id_departamento+'">'+data[i].nome_departamento+'</option>');
		 			}
		 		}
		 	}
			 });
		 });
		 
		 
	});
</script>