<?php 
if(isset($_SESSION['success'])){
	echo '<div class="alert alert-success">'.$session->getFlashMessage('success').'</div>';
}

if(isset($_SESSION['error'])){
	echo '<div class="alert alert-danger">'.$session->getFlashMessage('error').'</div>';
}
?>
<div class="list_dependente_pf">
<h3 style="color: #C7187D">Cadastrado de Funcionario</h3>
<br />
	<a href="/funcionario/cadFuncionario" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	
	<form class="navbar-form navbar-right" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Nome" name="nome_funcionario">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" placeholder="CPF" name="cpf_funcionario">
  </div>
  <div class="form-group">
   <select name="id_cliente" class="form-control">
   	<option>TODOS</option>
   	<?php
   	foreach($empresas as $dep){
   		echo '<option value="'.$dep['id_clientePJ'].'">'.$dep['nomefantasia_clientePJ'].'</option>';
   	}
	?>
   </select>
  </div>
  <div class="form-group">
  	<select name="status_funcionario" class="form-control">
  		<option value="1">Ativo</option>
  		<option value="0">Inativo</option>
  	</select>
  </div>
  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
</form>
<br>
	<?php
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','CPF','Empresa','Editar','Excluir'));
	
	foreach($dependentes as $dep){
		$table->t_row(array(
			$dep['nome_dependentePJ'],
			$dep['cpf_dependentePJ'],
			$dep['nomefantasia_clientePJ'],
			'<center><a href="/funcionario/updateFuncionario/id/'.$dep['id_dependentePJ'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
			'<center><a href="/funcionario/removeFuncionario/id/'.$dep['id_dependentePJ'].'" onclick="return confirm(\'Deseja Realmente remover '.$dep['nome_dependentePJ'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>')
			);
	}
	$table->generate();
	?>
</div>
<script>
	jQuery(function(){
		jQuery('[name=cpf_dependente]').mask('999.999.999-99');
	});
</script>