<?php 
if(isset($_SESSION['success'])){
	echo '<div class="alert alert-success">'.$session->getFlashMessage('success').'</div>';
}

if(isset($_SESSION['error'])){
	echo '<div class="alert alert-danger">'.$session->getFlashMessage('error').'</div>';
}
?>
<div class="list_dependente_pf">
<h3 style="color: #C7187D">Cadastrado de Funcionario</h3>
<br />
	<a href="/funcionario/cadFuncionario" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
	
	<!-- <form class="navbar-form navbar-right" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Nome" name="nome_funcionario">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" placeholder="CPF" name="cpf_funcionario">
  </div>
  <div class="form-group">
   <select name="id_cliente" class="form-control">
   	<option>TODOS</option>
   	<?php
   	foreach($empresas as $dep){
   		if($dep['tipo_cliente'] == '2'){
	   		echo '<option value="'.$dep['id_clientePF'].'">'.$dep['nomefantasia_clientePJ'].'</option>';
   		}
   	}
	
	foreach ($empresa as $key => $value) {
		if($value['tipo_cliente'] == '2')
		$opt_cliente[$value['id_clientePF']] = $value['nomefantasia_clientePJ'];
	}
	?>
   </select>
  </div>
  <div class="form-group">
  	<select name="status_funcionario" class="form-control">
  		<option value="1">Ativo</option>
  		<option value="0">Inativo</option>
  	</select>
  </div>
  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
</form> -->
<br>
	<?php
	$table->t_init('class="table table-bordered" id="tbl_dep"');
	$table->t_head(array('Nome','CPF','Empresa','Status','Editar','Excluir'));
	
	
	foreach($dependentes as $dep){
		if($dep['id_departamento'] != null)
		$table->t_row(array(
			$dep['nome_dependente'],
			$dep['cpf_dependente'],
			$opt_cliente[$dep['id_clientePF']],
			$dep['status_dependente'] == 1 ? 'Ativo' : 'Inativo',
			'<center><a href="/funcionario/updateFuncionario/id/'.$dep['id_dependentePF'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
			'<center><a href="/funcionario/removeFuncionario/id/'.$dep['id_dependentePF'].'" onclick="return confirm(\'Deseja Realmente remover '.$dep['nome_dependente'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>')
			);
	}
	$table->generate();
	?>
</div>
<script>
	jQuery(function(){
		jQuery('[name=cpf_dependente]').mask('999.999.999-99');
		jQuery('#tbl_dep').dataTable();
	});
</script>