<h3 style="color: #C7187D">Atualizar de Funcionário</h3>
<br />
<div class="form_dependentePJ">
	<fieldset>
<?php 


$form->init('form_func','/funcionario/alterFuncionario');	

echo '<input type="hidden" name="id_dependentePF" value="'.$funcionarios[0]['id_dependentePF'].'">';
foreach($empresas as $cli){
	if($cli['tipo_cliente'] == '2'){
		$opt_cli[$cli['id_clientePF']] = $cli['nomefantasia_clientePJ'];
	}
}

foreach($classificacao as $clas){
	$opt_class[$clas['id_classificacao']] = $clas['titulo_classificacao'];
}

foreach ($departamentos as $key => $value) {
		$opt_dep[$value['id_departamento']] = $value['nome_departamento'];
}

$form->groupOpen();
$form->select($opt_cli,'id_clientePF','Cliente',$funcionarios[0]['id_clientePF'],2,4);
$form->groupClose();

$form->groupOpen();
$form->select($opt_dep,'id_departamento','Departamento',$funcionarios[0]['id_departamento'],2,2);
$form->groupClose();

$form->groupOpen();
$form->select($opt_class,'id_classificacao','Classificação',$funcionarios[0]['id_classificacao'],2,2);
$form->groupClose();

$form->groupOpen();	
$form->input(array(
		'name' =>'nome_dependente',
		'type' =>'text',
		'placeholder' => 'Nome',
		'num_label' =>'2',
		'num_input' =>'5',
		'label' =>'Nome',
		'value' =>$funcionarios[0]['nome_dependente'],
		'required' => true
		));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'dt_nascimento_dependente',
				'type' =>'date',
				'placeholder' => 'Data de Nasc.',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Data de Nasc.',
				'value' => $funcionarios[0]['dt_nascimento_dependente'],
				'required' => true
				));
$form->groupClose();
$form->groupOpen();	
$form->input(array(
				'name' =>'cpf_dependente',
				'type' =>'text',
				'placeholder' => 'CPF',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'CPF',
				'value' =>$funcionarios[0]['cpf_dependente'],
				'required' => true
				));


	
$form->input(array(
				'name' =>'rg_dependente',
				'type' =>'text',
				'placeholder' => 'RG',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'RG',
				'value' =>$funcionarios[0]['rg_dependente'],
				'required' => true
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'telefone_dependente',
				'type' =>'text',
				'placeholder' => 'Telefone',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Telefone',
				'value' =>$funcionarios[0]['telefone_dependente'],
				'required' => true
				));

	
$form->input(array(
				'name' =>'celular_dependente',
				'type' =>'text',
				'placeholder' => 'Celular',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'Celular',
				'value' =>$funcionarios[0]['celular_dependente'],
				'required' => false
				));
$form->groupClose();


$form->groupOpen();	
$form->input(array(
				'name' =>'cep_dependente',
				'type' =>'text',
				'placeholder' => 'CEP',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'CEP',
				'value' =>$funcionarios[0]['cep_dependente'],
				'required' => false
				));
echo '<div class="msg_cep"></div>';
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'endereco_dependente',
				'type' =>'text',
				'placeholder' => 'Endereço',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Endereço',
				'value' =>$funcionarios[0]['endereco_dependente'],
				'required' => true
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'numero_dependente',
				'type' =>'text',
				'placeholder' => 'Número',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Número',
				'value' =>$funcionarios[0]['numero_dependente'],
				'required' => true
				));

$form->input(array(
				'name' =>'complemento_dependente',
				'type' =>'text',
				'placeholder' => 'Complemento',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Complemento',
				'value' =>$funcionarios[0]['complemento_dependente'],
				'required' => false
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'bairro_dependente',
				'type' =>'text',
				'placeholder' => 'Bairro',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Bairro',
				'value' =>$funcionarios[0]['bairro_dependente'],
				'required' => true
				));
// $form->groupClose();
// 
// $form->groupOpen();	
$form->input(array(
				'name' =>'cidade_dependente',
				'type' =>'text',
				'placeholder' => 'Cidade',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'Cidade',
				'value' =>$funcionarios[0]['cidade_dependente'],
				'required' => true
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'uf_dependente',
				'type' =>'text',
				'placeholder' => 'UF',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'UF',
				'value' =>$funcionarios[0]['uf_dependente'],
				'required' => true
				));

$form->input(array(
				'name' =>'pais_dependente',
				'type' =>'text',
				'placeholder' => 'Pais',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'Pais',
				'value' =>$funcionarios[0]['pais_dependente'],
				'required' => true
				));
$form->groupClose();


$form->groupOpen();	
$form->input(array(
				'name' =>'email_dependente',
				'type' =>'text',
				'placeholder' => 'Email',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Email',
				'value' =>$funcionarios[0]['email_dependente'],
				'required' => true
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'numero_passaporte_dependente',
				'type' =>'text',
				'placeholder' => 'Nº Passaporte',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Nº Passaporte',
				'value' =>$funcionarios[0]['numero_passaporte_dependente'],
				'required' => false
				));
	
$form->input(array(
				'name' =>'dt_validade_passaporte_dependente',
				'type' =>'date',
				'placeholder' => 'Data Validade',
				'num_label' =>'1',
				'num_input' =>'3',
				'label' =>'Validade',
				'value' =>$funcionarios[0]['dt_validade_passaporte_dependente'] == '0000-00-00' ? null : $funcionarios[0]['dt_validade_passaporte_dependente'],
				'required' => false
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'foto_dependente',
				'type' =>'file',
				'placeholder' => 'Foto',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Foto',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'copia_rg_dependente',
				'type' =>'file',
				'placeholder' => 'Cópia RG',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Cópia RG',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();

$form->groupOpen();	
$form->input(array(
				'name' =>'copia_cpf_dependente',
				'type' =>'file',
				'placeholder' => 'Cópia CPF',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Cópia CPF',
				'value' =>'',
				'required' => FALSE
				));
$form->groupClose();



$form->groupOpen();
$form->select(array('1'=>'ATIVO','0'=>'INATIVO'),'status_dependente','Status',$funcionarios[0]['status_dependente'],2,2);
$form->groupClose();

$form->textarea('descricao_dependente','Descrição',$funcionarios[0]['descricao_dependente'],'Descrição',2,5);

echo str_repeat('<br />',3);



	$form->groupOpen();		
	$form->submit('Atualizar','style="padding:5% 13%"');
	$form->groupClose();

$form->close();
?>

</fieldset>
</div>

<script>
	jQuery(function(){
		jQuery('#nome_dependentePF').css('text-transform','uppercase');
		// jQuery('#dt_nascimento_dependente').mask('99/99/9999');
		jQuery('#cpf_dependente').mask('999.999.999-99');
		jQuery('#rg_dependente').mask('99.999.999-9');
		jQuery('#telefone_dependente').mask('(99) 9999-9999');
		jQuery('#celular_dependente').mask('(99) 9999-9999');
		// jQuery('#dt_validade_passaporte_dependente').mask('99/99/9999');
		jQuery('#cep_dependente').mask('99999-999');
		
		jQuery("#cep_dependente").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		beforeSend: function(){
		 			jQuery('#form_dependentePJ').attr('disabled',true);
		 		},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#form_dependente').attr('disabled',false);
		 			jQuery('#endereco_dependente').val(data.endereco);
		 			jQuery('#bairro_dependente').val(data.bairro);
		 			jQuery('#cidade_dependente').val(data.cidade	);
		 			jQuery('#uf_dependente').val(data.uf);
		 			jQuery('#pais_dependente').val('Brasil');
		 			jQuery('#numero_dependente').focus();
		 				
		 			}else{
			 			jQuery('#form_dependentePJ').attr('disabled',false);
		 				jQuery('.msg_cep').html('CEP Não encontrado!');
		 				jQuery('#endereco_clientePF').focus();
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		 
		 
		 //Popular Página ao mudar de empresa
		 jQuery('[name=id_clientePJ]').change(function(){
			 	jQuery.ajax({
			 	url:'/funcionario/getDepartamento',
			 	type:'post',
			 	dataType: 'json',
			 	data: {id_clientePJ : jQuery(this).val()},
			 	success: function(data){
			 		if(data){
			 			jQuery('[name=id_departamento]').html('');
			 			for(var i = 0; i < data.length; i++){
			 				jQuery('[name=id_departamento]').append('<option value="'+data[i].id_departamento+'">'+data[i].nome_departamento+'</option>');
			 			}
			 		}
			 	}
			 });
		 });
		 
	});
</script>