<?php
			$id = isset($continentes) ? $continentes[0]['id_continente'] : null;
			
			$form->init('form_continente','/continente/saveContinente');
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_continente',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $id,
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'nome_continente',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Nome',
				'value' => isset($continentes) ? $continentes[0]['nome_continente'] : null,
				'required' => true
				));
		  $form->groupClose();
		  
		  
		  $form->textarea('descricao_continente','Descrição',isset($continentes) ? $continentes[0]['descricao_continente'] : null,'Descrição',2,8);
		  
		  echo str_repeat('<br />',3);
		 
		  $form->groupOpen();		
	      $form->submit('Salvar','style="padding:5% 13%"');
		  $form->groupClose();
$form->close();