<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/continente/cadContinente" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','Editar','Remover'));
	foreach($continentes as $con){
		$table->t_row(array(
				$con['nome_continente'],
				'<center><a href="/continente/cadContinente/id/'.$con['id_continente'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
				'<center><a href="/continente/deleteContinente/id/'.$con['id_continente'].'" onclick=" return confirm(\'Deseja realmente remover '.$con['nome_continente'].' ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
				));
	}
	$table->generate();
	?>
</div>
