<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/tipoCartao/cadTipoCartao" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<!-- <form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Teste" name="teste">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form> -->
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Titulo','Status','Editar','Remover'));
	foreach ($tipocartaos as $key => $value):
	$table->t_row(array(
			$value['titulo_tipoCartao'],
			$value['status_tipoCartao'] == 1 ? 'Ativo' : 'Inativo',
			'<center><a href="/tipoCartao/cadTipoCartao/id/'.$value['id_tipoCartao'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
			'<center><a href="/tipoCartao/deleteTipoCartao/id/'.$value['id_tipoCartao'].'" onclick=" return confirm(\'Deseja realmente remover TIpo de Cartão ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
			));
	endforeach;
	$table->generate();
	?>
</div>
