<?php

?>
	<form class="navbar-form navbar-right" role="search" method="post" action="/resultado">
		<div class="form-group">
			<input type="date" class="form-control" name="dt_de">
		</div>
		<div class="form-group">
			<input type="date" class="form-control" name="dt_ate">
		</div>
		<div class="form-group">
			<select name="id_filial" class="form-control">
				<option value="0">Todas</option>
				<?php foreach ($filial as $key => $value): ?>
				<option value="<?=$value['id_filial']?>"><?=$value['nome_filial']?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form>
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Teste','Teste','Status','Editar','Remover'));
	$table->t_row(array(
						'teste',
						'teste',
						'Ativo',
						'<center><a href="#"><span class="glyphicon glyphicon-pencil"></span></a></center>',
						'<center><a href="#" onclick=" return confirm(\'Deseja realmente remover ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
						));
	$table->generate();
	?>
</div>