<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/classificacao/cadClassificacao" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Título','Status','Editar','Remover'));
	foreach ($classificacao as $key => $value) {
		$table->t_row(array(
							$value['titulo_classificacao'],
							$value['status_classificacao'] == '1' ? 'Ativo' : 'Inativo',
							'<center><a href="/classificacao/cadClassificacao/id/'.$value['id_classificacao'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
							'<center><a href="/classificacao/deleteClassificacao/id/'.$value['id_classificacao'].'" onclick=" return confirm(\'Deseja realmente remover classificação?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
							));
	}
						
	$table->generate();
	?>
</div>
