<?php 
$action = "/cliente/saveFisica";
if(isset($_GET['id'])){
	$cliente = $model->list_all($_GET['id']);
	$action = "/cliente/updateFisica";
} ?>
<div class="cli_fisica">
<form name="form_clifisica" method="post" action="<?=$action?>" id="form_clifisico" role="form" class="form-horizontal" enctype="multipart/form-data">
	 <fieldset id="fs_form_pf">
	 	
	 <div class="form-group">
    <label for="id_classificacao" style="color: #797676;" class="col-sm-2 control-label">*Classificação</label>
    <div class="col-sm-2">
     <select class="form-control" name="id_classificacao">
     	<option value="1">Sr</option>
     	<option value="2">Sra</option>
     	<option value="3">Mrs</option>
     	<option value="4">Miss</option>
     	<option value="5">Mstr</option>
     </select>
    </div>
  </div>
	 
	 
	<div class="form-group">
    <label for="nome_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Nome</label>
    <div class="col-sm-9">
      <input type="text" style="text-transform: uppercase;" required class="form-control" id="nome_clientePF" placeholder="Nome" name="nome_clientePF" value="<?=@$cliente[0]['nome_clientePF']?>">
    </div>
  </div>
  
  <div class="form-group">
    <label for="dataNascimento_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Data Nasc.</label>
    <div class="col-sm-3">
    	
      <input type="text" class="form-control" id="dataNascimento_clientePF" required name="dataNascimento_clientePF" value="<?=@date('d/m/Y',strtotime($cliente[0]['dataNascimento_clientePF']))?>">
    </div>
  </div>
  
   <div class="form-group">
    <label for="rg_clientePF" style="color: #797676;" class="col-sm-2 control-label">*RG</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" required id="rg_clientePF" name="rg_clientePF" placeholder="RG" value="<?=@$cliente[0]['rg_clientePF']?>">
    </div>
    
    <label for="cpf_clientePF" style="color: #797676;"  class="col-sm-2 control-label">*CPF</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cpf_clientePF" required name="cpf_clientePF" placeholder="CPF" value="<?=@$cliente[0]['cpf_clientePF']?>">
    </div>
  </div>
  
  
   <div class="form-group">
   <label for="cep_clientePF" style="color: #797676;"  class="col-sm-2 control-label">*CEP</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cep_clientePF" required name="cep_clientePF" placeholder="CEP" value="<?=@$cliente[0]['cep_clientePF']?>"><div id="msg_cep"></div>
    </div>
  </div>
  
  	<div class="form-group">
    <label for="endereco_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Endereço</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="endereco_clientePF" required placeholder="Endereço" name="endereco_clientePF" value="<?=@$cliente[0]['endereco_clientePF']?>">
    </div>
    
  </div>
  
   <div class="form-group">
    <label for="numero_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Número</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="numero_clientePF" required placeholder="Número" name="numero_clientePF" value="<?=@$cliente[0]['numero_clientePF']?>">
    </div>
    
     <label for="complemento_clientePF" style="color: #797676;" class="col-sm-2 control-label">Complemento</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="complemento_clientePF" name="complemento_clientePF" placeholder="Complemento" value="<?=@$cliente[0]['complemento_clientePF']?>">
    </div>
  </div>
  
    <div class="form-group">
    <label for="bairro_clientePF" style="color: #797676;" class="col-sm-2 control-label">Bairro</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="bairro_clientePF" name="bairro_clientePF" placeholder="Bairro" value="<?=@$cliente[0]['bairro_clientePF']?>">
    </div>
    
    <label for="cidade_clientePF" style="color: #797676;" class="col-sm-1 control-label">Cidade</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cidade_clientePF" name="cidade_clientePF" placeholder="CIdade" value="<?=@$cliente[0]['cidade_clientePF']?>">
    </div>
     
  </div>
  
  
  <div class="form-group">
  	<label for="uf_clientePF" style="color: #797676;" class="col-sm-2 control-label">UF</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="uf_clientePF" name="uf_clientePF" placeholder="UF" value="<?=@$cliente[0]['uf_clientePF']?>">
    </div>
    
    	<label for="pais_clientePF" style="color: #797676;" class="col-sm-2 control-label">País</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="pais_clientePF" name="pais_clientePF" placeholder="País" value="<?=@$cliente[0]['pais_clientePF']?>">
    </div>
  </div>	
  	
  <div class="form-group">
    <label for="email_clientePF" style="color: #797676;" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="email_clientePF" placeholder="Email" name="email_clientePF" value="<?=@$cliente[0]['email_clientePF']?>">
    </div>
  </div>
  
   <div class="form-group">
    <label for="telefone_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Telefone</label>
    <div class="col-sm-4">
      <input type="text"  class="form-control" id="telefone_clientePF" required placeholder="Telefone" name="telefone_clientePF" value="<?=@$cliente[0]['telefone_clientePF']?>">
    </div>
    
    <label for="celular_clientePF" style="color: #797676;" class="col-sm-2 control-label">Celular</label>
    <div class="col-sm-3">
      <input type="text"  class="form-control" id="celular_clientePF" placeholder="Celular" name="celular_clientePF" value="<?=@$cliente[0]['celular_clientePF']?>">
    </div>
    
  </div>
  
   <div class="form-group">
   	<label for="numero_passaporte_clientePF" style="color: #797676;" class="col-sm-2 control-label">Passaporte</label>
    <div class="col-sm-4">
      <input type="text"  class="form-control" id="numero_passaporte_clientePF" placeholder="Passaporte" name="numero_passaporte_clientePF" value="<?=@$cliente[0]['passaporte_clientePF']?>">
    </div>
   	
   
   	 <label for="dt_validadePassaporte_clientePF" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
    	<div class="col-sm-3">
      <input type="text" class="form-control" id="dt_validadePassaporte_clientePF" name="dt_validadePassaporte_clientePF" value="	<?=@date('d/m/Ỹ',strtotime($cliente[0]['td_validade_clientePF']))?>">
    	</div>
    	
   	</div> 
 
	 <div class="form-group">
	 	 <label for="numero_fidelidade_clientePF" style="color: #797676;" class="col-sm-2 control-label">Nº Fidelidade</label>
    	<div class="col-sm-4">
      <input type="text" class="form-control" id="numero_fidelidade_clientePF" name="numero_fidelidade_clientePF" placeholder="Número Fidelidade" value="	<?=@$cliente[0]['numero_fidelidade_clientePF']?>">
    	</div>
	
	 </div>
	 
	  <div class="form-group">
	 	 <label for="copia_rg_clientePF" style="color: #797676;" class="col-sm-2 control-label">Cópia RG</label>
    	<div class="col-sm-5">
     	 <input type="file" class="form-control" id="copia_rg_clientePF" name="copia_rg_clientePF" value="<?=@$cliente[0]['copia_rg_clientePF']?>">
    	</div>
	 </div>

	  <div class="form-group">
	      	 <label for="copia_cpf_clientePF" style="color: #797676;" class="col-sm-2 control-label">Cópia CPF</label>
    	<div class="col-sm-5">
    	  <input type="file" class="form-control" id="copia_cpf_clientePF" name="copia_cpf_clientePF" <?=@$cliente[0]['copia_cpf_clientePF']?>">
    	</div>
	  </div>

	  <div class="form-group">
    	<label for="foto_clientePF" style="color: #797676;" class="col-sm-2 control-label">Foto</label>
    	<div class="col-sm-5">
     	 <input type="file" class="form-control" id="foto_clientePF" name="foto_clientePF">
    	</div>
	  </div>	

	  
	  <div class="form-group">
    	<label for="descricao_clientePF" style="color: #797676;" class="col-sm-2 control-label">Descrição</label>
		<div class="col-sm-9">
		<textarea class="form-control" name="descricao_clientePF" placeholder="Descrição" rows="3"><?=@$cliente[0]['descricao_clientePF']?></textarea>
		</div>
		
		<label for="status_clientePF" style="color: #797676;" class="col-sm-2 control-label">Status</label>
	    <div class="col-sm-3">
	     <select class="form-control" name="status_clientePF">
	     	<option value="1">ATIVO</option>
	     	<option value="0">INATIVO</option>
	     </select>
	    </div>
	  </div>	
	 
	 
	 </fieldset>
	 
	 <br />
	  <div class="form-group">
    	<div class="col-sm-offset-5 col-sm-10">
      <button type="submit" style="padding:20px 40px" class="btn btn-default">Salvar</button>
    </div>
  </div>
	
</form>
</div>
<script>
	jQuery(function(){
		
		 jQuery("#cep_clientePF").mask("99999-999");
		 jQuery("#rg_clientePF").mask("99.999.999-9");
		 jQuery("#cpf_clientePF").mask("999.999.999-99");
		 jQuery("#telefone_clientePF").mask("(99) 9999-9999");
		 jQuery("#celular_clientePF").mask("(99) 9999-9999");
		 jQuery("#dataNascimento_clientePF").mask("99/99/9999");
		 jQuery("#dt_validadePassaporte_clientePF").mask("99/99/9999");
		
	
		 jQuery("#cep_clientePF").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		beforeSend: function(){
		 			jQuery('#fs_form_pf').attr('disabled',true);
		 		},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#fs_form_pf').attr('disabled',false);
		 			jQuery('#endereco_clientePF').val(data.endereco);
		 			jQuery('#bairro_clientePF').val(data.bairro);
		 			jQuery('#cidade_clientePF').val(data.cidade	);
		 			jQuery('#uf_clientePF').val(data.uf);
		 			jQuery('#pais_clientePF').val('Brasil');
		 			jQuery('#numero_clientePF').focus();
		 				
		 			}else{
			 			jQuery('#fs_form_pf').attr('disabled',false);
		 				jQuery('#msg_cep').html('CEP Não encontrado!');
		 				jQuery('#endereco_clientePF').focus();
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		
			jQuery('#nome_clientePF').submit(function(){
				jQuery(this).val().toUpperCase();
			});
			
	});
</script>