<div class="container">
	<!--<nav class="navbar navbar-default" role="navigation">
		<!-- Collect the nav links, forms, and other content for toggling -->
		 <!--<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<form class="navbar-form navbar-left" role="search" method="post">
				<div class="form-group">
					<input type="text" name="nome_clientePF" class="form-control" placeholder="Nome">
				</div>
				<div class="form-group">
					<input type="text" name="cpf_clientePF" class="form-control" placeholder="CPF">
				</div>
				<div class="form-group">
					<input type="text" name="uf_clientePF" class="form-control" placeholder="UF">
				</div>
				<button type="submit" class="btn btn-info">Buscar</button>
			</form> 
		</div> 
		
	</nav> -->
	<br />
	<?php
		if(isset($_SESSION['success'])){
			echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
		}
		
		if(isset($_SESSION['error'])){
			echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
		}
 ?>
	<a href="/cliente/cadfisica" class="btn btn-success"><span class="glyphicon glyphicon-plus"> Novo</span></a>
	<br />
	<br />
	<div class="table-responsive">
		<?php 
			$table->t_init('class="table table-bordered" id="tbl_clientePF"');
			$table->t_head(array('<strong>Nome</strong>','<strong>CPF</strong>','<strong>UF</strong>','<strong>TELEFONE</strong>','<strong>Editar</strong>','<strong>Excluir</strong>'));
			foreach($clientes as $cliente){
			$table->t_row(array($cliente['nome_clientePF'],
								$cliente['cpf_clientePF'],
								$cliente['uf_clientePF'],
								$cliente['telefone_clientePF'],
								'<center><a href="/cliente/updateFisica/id/'.$cliente['id_clientePF'].'"><span  class="glyphicon glyphicon-pencil"></span></a></center>',
								'<center><a href="/cliente/deleteClientePF/id/'.$cliente['id_clientePF'].'" onclick=" return confirm(\'Deseja realmente remover '.$cliente['nome_clientePF'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
								)
						  );
			}
			$table->generate();
		?>
	</div>
</div>
<script>
	jQuery(function(){
		jQuery('#tbl_clientePF').dataTable();
	});
</script>