
<div class="cli_fisica">
<form name="form_clifisica" method="post" action="/cliente/saveUpdatePF" id="form_clifisico" role="form" class="form-horizontal" enctype="multipart/form-data">
	 <fieldset id="fs_form_pf">
	 	<input type="hidden" name="id_clientePF" value="<?=$clientes[0]['id_clientePF']?>" />
	 <?php
	 foreach($classif as $class){
	 	$opt_cl[$class['id_classificacao']] = $class['titulo_classificacao'];
	 }
	 
	 $form->groupOpen();
	 $form->select($opt_cl,'id_classificacao','Classificação',$clientes[0]['id_classificacao']);
	 $form->groupClose();
	 ?>	 
	 
	<div class="form-group">
    <label for="nome_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Nome</label>
    <div class="col-sm-9">
      <input type="text" style="text-transform: uppercase;" required class="form-control" value="<?=utf8_encode($clientes[0]['nome_clientePF'])?>" id="nome_clientePF" placeholder="Nome" name="nome_clientePF">
    </div>
  </div>
  
  <div class="form-group">
    <label for="dataNascimento_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Data Nasc.</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="dataNascimento_clientePF" value="<?=date('d/m/Y',strtotime($clientes[0]['dataNascimento_clientePF']))?>" required name="dataNascimento_clientePF">
    </div>
  </div>
  
   <div class="form-group">
    <label for="rg_clientePF" style="color: #797676;" class="col-sm-2 control-label">*RG</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" required value="<?=$clientes[0]['rg_clientePF']?>" id="rg_clientePF" name="rg_clientePF" placeholder="RG">
    </div>
    
    <label for="cpf_clientePF" style="color: #797676;"  class="col-sm-2 control-label">*CPF</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cpf_clientePF" value="<?=$clientes[0]['cpf_clientePF']?>" required name="cpf_clientePF" placeholder="CPF">
    </div>
  </div>
  
  
   <div class="form-group">
   <label for="cep_clientePF" style="color: #797676;"  class="col-sm-2 control-label">*CEP</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cep_clientePF" value="<?=$clientes[0]['cep_clientePF']?>" required name="cep_clientePF" placeholder="CEP"><div id="msg_cep"></div>
    </div>
  </div>
  
  	<div class="form-group">
    <label for="endereco_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Endereço</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="endereco_clientePF" value="<?=utf8_encode($clientes[0]['endereco_clientePF'])?>" required placeholder="Endereço" name="endereco_clientePF">
    </div>
    
  </div>
  
   <div class="form-group">
    <label for="numero_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Número</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="numero_clientePF" value="<?=$clientes[0]['numero_clientePF']?>" required placeholder="Número" name="numero_clientePF">
    </div>
    
     <label for="complemento_clientePF" style="color: #797676;" class="col-sm-2 control-label">Complemento</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="complemento_clientePF" value="<?=$clientes[0]['complemento_clientePF']?>" name="complemento_clientePF" placeholder="Complemento">
    </div>
  </div>
  
    <div class="form-group">
    <label for="bairro_clientePF" style="color: #797676;" class="col-sm-2 control-label">Bairro</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="bairro_clientePF" name="bairro_clientePF" value="<?=($clientes[0]['bairro_clientePF'])?>" placeholder="Bairro">
    </div>
    
    <label for="cidade_clientePF" style="color: #797676;" class="col-sm-1 control-label">Cidade</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="cidade_clientePF" value="<?=($clientes[0]['cidade_clientePF'])?>" name="cidade_clientePF" placeholder="CIdade">
    </div>
     
  </div>
  
  
  <div class="form-group">
  	<label for="uf_clientePF" style="color: #797676;" class="col-sm-2 control-label">UF</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="uf_clientePF" value="<?=$clientes[0]['uf_clientePF']?>" name="uf_clientePF" placeholder="UF">
    </div>
    
    	<label for="pais_clientePF" style="color: #797676;" class="col-sm-2 control-label">País</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="pais_clientePF" name="pais_clientePF" value="<?=$clientes[0]['pais_clientePF']?>" placeholder="País">
    </div>
  </div>	
  	
  <div class="form-group">
    <label for="email_clientePF" style="color: #797676;" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="email_clientePF" placeholder="Email" value="<?=$clientes[0]['email_clientePF']?>" name="email_clientePF">
    </div>
  </div>
  
   <div class="form-group">
    <label for="telefone_clientePF" style="color: #797676;" class="col-sm-2 control-label">*Telefone</label>
    <div class="col-sm-4">
      <input type="text"  class="form-control" id="telefone_clientePF" required placeholder="Telefone" value="<?=$clientes[0]['telefone_clientePF']?>" name="telefone_clientePF">
    </div>
    
    <label for="celular_clientePF" style="color: #797676;" class="col-sm-2 control-label">Celular</label>
    <div class="col-sm-3">
      <input type="text"  class="form-control" id="celular_clientePF" placeholder="Celular" value="<?=$clientes[0]['celular_clientePF']?>" name="celular_clientePF">
    </div>
    
  </div>
  
   <div class="form-group">
   	<label for="numero_passaporte_clientePF" style="color: #797676;" class="col-sm-2 control-label">Passaporte</label>
    <div class="col-sm-4">
      <input type="text"  class="form-control" id="numero_passaporte_clientePF" placeholder="Passaporte" value="<?=$clientes[0]['numero_passaporte_clientePF']?>" name="numero_passaporte_clientePF">
    </div>
   	
   	
   	 <label for="dt_validadePassaporte_clientePF" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
    	<div class="col-sm-3">
      <input type="text" class="form-control" id="dt_validadePassaporte_clientePF" value="<?=date('d/m/Y',strtotime($clientes[0]['dt_validadePassaporte_clientePF']))?>" name="dt_validadePassaporte_clientePF">
    	</div>
    	
   	</div> 
 
	 <div class="form-group">
	 	 <label for="numero_fidelidade_clientePF" style="color: #797676;" class="col-sm-2 control-label">Nº Fidelidade</label>
    	<div class="col-sm-4">
      <input type="text" class="form-control" id="numero_fidelidade_clientePF" name="numero_fidelidade_clientePF" value="<?=$clientes[0]['numero_fidelidade_clientePF']?>" placeholder="Número Fidelidade">
    	</div>
	
	 </div>
	 
	  <div class="form-group">
	 	 <label for="copia_rg_clientePF" style="color: #797676;" class="col-sm-2 control-label">Cópia RG</label>
    	<div class="col-sm-5">
     	 <input type="file" class="form-control" id="copia_rg_clientePF" name="copia_rg_clientePF">
    	</div>
	 </div>

	  <div class="form-group">
	      	 <label for="copia_cpf_clientePF" style="color: #797676;" class="col-sm-2 control-label">Cópia CPF</label>
    	<div class="col-sm-5">
    	  <input type="file" class="form-control" id="copia_cpf_clientePF" name="copia_cpf_clientePF">
    	</div>
	  </div>

	  <div class="form-group">
    	<label for="foto_clientePF" style="color: #797676;" class="col-sm-2 control-label">Foto</label>
    	<div class="col-sm-5">
     	 <input type="file" class="form-control" id="foto_clientePF" name="foto_clientePF">
    	</div>
	  </div>	
	<hr />
		<fieldset id="cartao_credito">
	<center><h3>Cartões de Crédito</h3></center>
	<br>
	<?php 
	$num = 0;
	foreach($cartoes as $cartao): 
		$num++;
		?>
		<div id="cloneDiv<?=$num?>" class="cartoes">
			<div class="form-group">
				<input type="hidden" name="id_cartaoPF[]" value="<?=$cartao['id_cartaoPF']?>" id="id_cartaoPF<?=$num?>" class="id_cartaoPF" />
				<label for="numero_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Número Cartão</label>
				<div class="col-sm-3">
				<input type="text" class="form-control numero_cartaoPF" value="<?=$cartao['numero_cartaoPF']?>" id="numero_cartaoPF<?=$num?>" placeholder="Número Cartão" name="numero_cartaoPF[]">
				</div>
				
				<label for="codigo_seguranca_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Código Segurança</label>
				<div class="col-sm-3">
				<input type="text" class="form-control codigo_seguranca_cartaoPF" value="<?=$cartao['codigo_seguranca_cartaoPF']?>" id="codigo_seguranca_cartaoPF<?=$num?>" placeholder="Número Cartão" name="codigo_seguranca_cartaoPF[]">
				</div>
			</div>
			
			<div class="form-group">
				
				 <?php
				  foreach($tipoCartoes as $cart){
				  	$opt_cart[$cart['id_tipoCartao']] = $cart['titulo_tipoCartao'];
				  }
				  
					 $form->select($opt_cart,'id_tipoCartao[]','Bandeira',$cartao['id_tipoCartao'],2,3);
				  ?>

				
				<label for="dt_validade_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
				<div class="col-sm-3">
				<input type="text" class="form-control dt_validade_cartaoPF" value="<?=date('d/m/Y',strtotime($cartao['dt_validade_cartaoPF']))?>" id="dt_validade_cartaoPF<?=$num?>" placeholder="Bandeira do Cartão" name="dt_validade_cartaoPF[]">
				</div>
			</div>
			<hr />
			</div>
		<?php endforeach; 
		if(!$cartoes): ?>
			<div id="cloneDiv1" class="cartoes">
			<div class="form-group">
				<input type="hidden" name="id_cartaoPF" value="" id="id_cartaoPF" class="id_cartaoPF" />
				<label for="numero_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Número Cartão</label>
				<div class="col-sm-3">
				<input type="text" class="form-control numero_cartaoPF" value="" id="numero_cartaoPF" placeholder="Número Cartão" name="numero_cartaoPF[]">
				</div>
				
				<label for="codigo_seguranca_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Código Segurança</label>
				<div class="col-sm-3">
				<input type="text" class="form-control codigo_seguranca_cartaoPF" value="" id="codigo_seguranca_cartaoPF" placeholder="Número Cartão" name="codigo_seguranca_cartaoPF[]">
				</div>
			</div>
			
			<div class="form-group">
				<?php
				  foreach($tipoCartoes as $cart){
				  	$opt_cart[$cart['id_tipoCartao']] = $cart['titulo_tipoCartao'];
				  }
				  
					 $form->select($opt_cart,'id_tipoCartao[]','Bandeira','1',2,3);
				  ?>

				
				<label for="dt_validade_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
				<div class="col-sm-3">
				<input type="text" class="form-control dt_validade_cartaoPF" value="" id="dt_validade_cartaoPF" placeholder="Bandeira do Cartão" name="dt_validade_cartaoPF[]">
				</div>
			</div>
			<hr />
			</div>
		<?php endif; ?>	
			<div class="form-group">
				<div class="col-sm-offset-5 col-sm-10">
				<button type="button" style="padding: 5px 20px"  id="bt_add_ct" title="Adicionar novo Cartão de Crédito" class="btn btn-warning bt_add_ct"><span class="glyphicon glyphicon-plus"></span></button>
				<button type="button" style="padding: 5px 20px"  id="bt_del_ct" title="Remover Cartão de Crédito" class="btn btn-danger bt_del_ct"><span class="glyphicon glyphicon-remove"></span></button>
				</div>
				</div>
			
	</fieldset>
	<hr />
	  
	  <div class="form-group">
    	<label for="descricao_clientePF" style="color: #797676;" class="col-sm-2 control-label">Descrição</label>
		<div class="col-sm-9">
		<textarea class="form-control" name="descricao_clientePF" placeholder="Descrição" rows="3"><?=($clientes[0]['descricao_clientePF'])?></textarea>
		</div>
		
	    <?php $form->select(array('1'=>'ATIVO','0'=>'INATIVO'),'status_clientePF','Status',$clientes[0]['status_clientePF']); ?>
	    
	  </div>	
	 
	 
	 </fieldset>
	 
	 <br />
	  <div class="form-group">
    	<div class="col-sm-offset-5 col-sm-10">
      <button type="submit" style="padding:20px 40px" class="btn btn-default">Atualizar</button>
    </div>
  </div>
	
</form>
</div>
<script>
	jQuery(function(){
		
		 jQuery("#cep_clientePF").mask("99999-999");
		 jQuery("#rg_clientePF").mask("99.999.999-9");
		 jQuery("#cpf_clientePF").mask("999.999.999-99");
		 jQuery("#telefone_clientePF").mask("(99) 9999-9999");
		 jQuery("#celular_clientePF").mask("(99) 9999-9999");
		 jQuery("#dataNascimento_clientePF").mask("99/99/9999");
		 jQuery("#dt_validadePassaporte_clientePF").mask("99/99/9999");
		jQuery('#dt_validade_cartaoPF').mask('99/99/9999');
	
		 jQuery("#cep_clientePF").blur(function(){
		 var cep = jQuery(this).val();
		 if(cep != ''){
		 	jQuery.ajax({
		 		url: '/cliente/findCep',
		 		type: 'post',
		 		dataType: 'json',
		 		data: {cep:jQuery(this).val()},
		 		beforeSend: function(){
		 			jQuery('#fs_form_pf').attr('disabled',true);
		 		},
		 		success: function(data){
		 			if(data != '0'){
		 			jQuery('#fs_form_pf').attr('disabled',false);
		 			jQuery('#endereco_clientePF').val(data.endereco);
		 			jQuery('#bairro_clientePF').val(data.bairro);
		 			jQuery('#cidade_clientePF').val(data.cidade	);
		 			jQuery('#uf_clientePF').val(data.uf);
		 			jQuery('#pais_clientePF').val('Brasil');
		 			jQuery('#numero_clientePF').focus();
		 				
		 			}else{
			 			jQuery('#fs_form_pf').attr('disabled',false);
		 				jQuery('#msg_cep').html('CEP Não encontrado!');
		 				jQuery('#endereco_clientePF').focus();
		 			}
		 			
		 		}
		 	});
		 }
		 	
		 });
		
			
			jQuery('#bt_add_ct').click(function(){
				
				num = jQuery('.cartoes').length;
				newNum = new Number(num + 1);

				var newElem = jQuery('#cloneDiv'+num).clone().attr('id','cloneDiv'+newNum).fadeIn('slow');

				newElem.find('.numero_cartaoPF').attr('id','numero_cartaoPF'+newNum).val('');
				newElem.find('.codigo_seguranca_cartaoPF').attr('id','codigo_seguranca_cartaoPF'+newNum).val('');
				newElem.find('.bandeira_cartaoPF').attr('id','bandeira_cartaoPF'+newNum).val('');
				newElem.find('.dt_validade_cartaoPF').attr('id','dt_validade_cartaoPF'+newNum).val('');
				newElem.find('.id_cartaoPF').attr('id','id_cartaoPF'+newNum).val('');
				
				jQuery('#cloneDiv'+num).after(newElem);
				jQuery('#bt_del_ct').attr('disabled',false);
				jQuery('#dt_validade_cartaoPF'+newNum).mask('99/99/9999');
				
			});

			jQuery('#bt_del_ct').click(function(){
			    num = jQuery('.cartoes').length;
				
				if(confirm('Deseja realmente remover esse cartão ?')){
				
				id_cartaoPF = jQuery('#cloneDiv'+num).find("#id_cartaoPF"+num).val();
				
				jQuery.ajax({
					url: '/cliente/delAjaxCartaoPF',
					type: 'post',
					dataType: 'html',
					data: {id_cartaoPF : id_cartaoPF},
					success: function(data){
						
					}
				});
				
				jQuery('#cloneDiv'+num).slideUp('slow',function(){
					jQuery('#cloneDiv'+num).remove();
					if(num - 1 === 1){
						jQuery('#bt_del_ct').attr('disabled',true);
					}else{
						jQuery('#bt_del_ct').attr('disabled',false);
						}
					});
				}
			});
			
			// jQuery('#bt_del_ct').attr('disabled',true);
			
	});
</script>