<?php
	$form->init('form_passagens','/passagens/savePassagens');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_passagens',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_clientePF',
				'type' =>'hidden',
				'placeholder' => 'id_clientePF',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_clientePF',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_compania',
				'type' =>'hidden',
				'placeholder' => 'id_compania',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_compania',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_classe',
				'type' =>'hidden',
				'placeholder' => 'id_classe',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_classe',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_destino',
				'type' =>'hidden',
				'placeholder' => 'id_destino',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_destino',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_origem',
				'type' =>'hidden',
				'placeholder' => 'id_origem',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_origem',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_moeda',
				'type' =>'hidden',
				'placeholder' => 'id_moeda',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'id_moeda',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'bagagem_passagens',
				'type' =>'hidden',
				'placeholder' => 'bagagem_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'bagagem_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voo_passagens',
				'type' =>'text',
				'placeholder' => 'voo_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'voo_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'assento_passagens',
				'type' =>'text',
				'placeholder' => 'assento_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'assento_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_passagens',
				'type' =>'text',
				'placeholder' => 'voucher_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'voucher_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'ticket_passagens',
				'type' =>'text',
				'placeholder' => 'ticket_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'ticket_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tarifa_passagens',
				'type' =>'text',
				'placeholder' => 'tarifa_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'tarifa_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_casa_passagens',
				'type' =>'text',
				'placeholder' => 'valor_casa_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'valor_casa_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tx_embarque_passagens',
				'type' =>'text',
				'placeholder' => 'tx_embarque_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'tx_embarque_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tx_outras_passagens',
				'type' =>'text',
				'placeholder' => 'tx_outras_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'tx_outras_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tx_repasse_passagens',
				'type' =>'text',
				'placeholder' => 'tx_repasse_passagens',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'tx_repasse_passagens',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
echo str_repeat('<br />',3);
								$form->groupOpen();		
								$form->submit('Salvar','style="padding:5% 13%"');
								$form->groupClose();
$form->close();