<div class="lista_filial">
<?php
	if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/filial/cadFilial" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	<form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Teste" name="teste">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form>
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','UF','País','Status','Editar','Remover'));
	foreach($filiais as $fil){
		$table->t_row(array(
				$fil['nome_filial'],
				$fil['uf_filial'],
				$fil['pais_filial'],
				$fil['status_filial'] == 1 ? 'Ativo': 'Inativo',
				'<center><a href="/filial/cadFilial/id/'.$fil['id_filial'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
				'<center><a href="/filial/deleteFilial/id/'.$fil['id_filial'].'"" onclick=" return confirm(\'Deseja realmente remover '.$fil['nome_filial'].' ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
				));

	}
	$table->generate();
	?>
</div>
