<div class="container">
	<nav class="navbar navbar-default" role="navigation">
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<form class="navbar-form navbar-left" role="search" method="post">
				<div class="form-group">
					<input type="text" name="nomefantasia_clientePJ" class="form-control" placeholder="Nome Fantasia">
				</div>
				<div class="form-group">
					<input type="text" name="cnpj_clientePJ" class="form-control" placeholder="CNPJ">
				</div>
				<div class="form-group">
					<input type="text" name="uf_clientePJ" class="form-control" placeholder="UF">
				</div>
				<button type="submit" class="btn btn-info">Buscar</button>
			</form>
		</div><!-- /.navbar-collapse -->
	</nav>
	<br />
	<?php
		if(isset($_SESSION['success'])){
			echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
		}
		
		if(isset($_SESSION['error'])){
			echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
		}
 ?>
	<a href="/cliente/cadjuridica" class="btn btn-success"><span class="glyphicon glyphicon-plus"> Novo</span></a>
	<br />
	<br />
	<div class="table-responsive">
		<?php 
			$table->t_init('class="table table-bordered"');
			$table->t_head(array('<strong>Nome Fantasia</strong>','<strong>CNPJ</strong>','<strong>UF</strong>','<strong>TELEFONE</strong>','<strong>Editar</strong>','<strong>Excluir</strong>'));
			foreach($clientes as $cliente){
			$table->t_row(array($cliente['nomefantasia_clientePJ'],
								$cliente['cnpj_clientePJ'],
								$cliente['uf_clientePJ'],
								$cliente['telefone_clientePJ'],
								'<center><a href="#"><span class="glyphicon glyphicon-pencil"></span></a></center>',
								'<center><a href="#"><span class="glyphicon glyphicon-remove"></span></a></center>'
								)
						  );
			}
			$table->generate();
		?>
	</div>
</div>