<div class="form_cli_pj">
	<fieldset id="form_clientePJ">
		<h3 style="color: #c7187d">Atualizar dados de Empresa</h3>
		<br />
<?php
	// $this->dump($cards);
	$form->init('form_cli_pj','/cliente/saveUpdateJuridica');	
		echo '<input type="hidden" name="id_clientePF" value="'.$clientes[0]['id_clientePF'].'">';
		######## Logotipo ##########
		$form->groupOpen();	
		$form->input(array(
						'name' =>'logotipo_clientePJ',
						'type' =>'file',
						'placeholder' => 'Logotipo',
						'num_label' =>'2',
						'num_input' =>'5',
						'label' =>'Logotipo',
						'value' =>'',
						'required' => false
						));
		$form->groupClose();					
					
						
		########## Razão Social ############
		$form->groupOpen();	
		$form->input(array(
					'name' =>'razaosocial_ClientePJ',
					'type' =>'text',
					'placeholder' => 'Razão Social',
					'num_label' =>'2',
					'num_input' =>'8',
					'label' =>'Razão Social',
					'value' =>isset($clientes) ? $clientes[0]['razaosocial_ClientePJ'] : null,
					'required' => false
					));
		$form->groupClose();		
		
		
		######### Nome Fantasia	############	
		$form->groupOpen();		
		$form->input(array(
						'name' =>'nomefantasia_clientePJ',
						'type' =>'text',
						'placeholder' => 'Razão Social',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Nome Fantasia',
						'value' => $clientes[0]['nomefantasia_clientePJ'],
						'required' => true
						));
		$form->groupClose();
	
	
		######### CNPJ	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'cnpj_clientePJ',
						'type' =>'text',
						'placeholder' => 'CNPJ',
						'num_label' =>'2',
						'num_input' =>'5',
						'label' =>'* CNPJ',
						'value' =>$clientes[0]['cnpj_clientePJ'],
						'required' => true
						));		
		$form->groupClose();		
				
		######### CEP	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'cep_cliente',
						'type' =>'text',
						'placeholder' => 'CEP',
						'num_label' =>'2',
						'num_input' =>'2',
						'label' =>'* CEP',
						'value' =>$clientes[0]['cep_cliente'],
						'required' => true
						));		
		$form->groupClose();
		
						
		######### Endereço	############
		$form->groupOpen();		
		$form->input(array(
						'name' =>'endereco_cliente',
						'type' =>'text',
						'placeholder' => 'Endereço',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Endereço',
						'value' =>$clientes[0]['endereco_cliente'],
						'required' => true
						));		
		$form->groupClose();		
										
										
		######### Número e Complemento ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'numero_cliente',
						'type' =>'text',
						'placeholder' => 'Número',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Número',
						'value' => $clientes[0]['numero_cliente'],
						'required' => false
						));
		$form->input(array(
						'name' =>'complemento_cliente',
						'type' =>'text',
						'placeholder' => 'Complemento',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' Complemento',
						'value' => $clientes[0]['complemento_cliente'],
						'required' => false
						));
		$form->groupClose();
		
		
		######### Bairro e cidade ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'bairro_cliente',
						'type' =>'text',
						'placeholder' => 'Bairro',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Bairro',
						'value' => $clientes[0]['bairro_cliente'],
						'required' => true
						));
		$form->input(array(
						'name' =>'cidade_cliente',
						'type' =>'text',
						'placeholder' => 'Cidade',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' Cidade',
						'value' => $clientes[0]['cidade_cliente'],
						'required' => false
						));
		$form->groupClose();
		
		
		######### UF - Pais ############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'uf_cliente',
						'type' =>'text',
						'placeholder' => 'UF',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' UF',
						'value' => $clientes[0]['uf_cliente'],
						'required' => false
						));
		$form->input(array(
						'name' =>'pais_cliente',
						'type' =>'text',
						'placeholder' => 'País',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' País',
						'value' => $clientes[0]['pais_cliente'],
						'required' => false
						));
		$form->groupClose();
				
										
		######### Telefone	############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'telefone1_clientePJ',
						'type' =>'text',
						'placeholder' => 'Telefone',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Telefone',
						'value' => $clientes[0]['telefone1_clientePJ'],
						'required' => true
						));
		$form->input(array(
						'name' =>'telefone2_clientePJ',
						'type' =>'text',
						'placeholder' => 'Telefone',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>' Telefone 2',
						'value' => $clientes[0]['telefone2_clientePJ'],
						'required' => FALSE
						));	
		$form->groupClose();		
								
								
		######### email	############		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'email_cliente',
						'type' =>'text',
						'placeholder' => 'E-mail',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* E-mail',
						'value' =>$clientes[0]['email_cliente'],
						'required' => true
						));	
		$form->groupClose();		
			$num = 0;	
				echo '<hr>';
		?>
		<fieldset id="cartao_credito">
	<center><h3>Cartões de Crédito</h3></center>
	<br>
	<?php foreach($cards as $cli): 
		$num ++;
		?>
		<div id="cloneDiv<?=$num?>" class="cartoes">
			<div class="form-group">
				<input type="hidden" class="id_cartaoPJ" name="id_cartaoPF[]" value="<?=$cli['id_cartaoPF']?>" id="id_cartaoPJ<?=$num?>"/>
				<label for="numero_cartaoPJ" style="color: #797676;" class="col-sm-2 control-label">Número Cartão</label>
				<div class="col-sm-3">
				<input type="text" class="form-control numero_cartaoPJ" id="numero_cartaoPJ<?=$num?>" placeholder="Número Cartão" name="numero_cartaoPF[]" value="<?=$cli['numero_cartaoPF']?>">
				</div>
				
				<label for="codigo_seguranca_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Código Segurança</label>
				<div class="col-sm-3">
				<input type="text" class="form-control codigo_seguranca_cartaoPJ" id="codigo_seguranca_cartaoPJ<?=$num?>" placeholder="Número Cartão" name="codigo_seguranca_cartaoPF[]" value="<?=$cli['codigo_seguranca_cartaoPF']?>">
					</div>
			</div>
			
			<div class="form-group">
				 	<?php 
				  	foreach($cartao as $cart){
				  		$opt_cart[$cart['id_tipoCartao']] = $cart['titulo_tipoCartao'];
				  	}
				  	$form->select($opt_cart,'id_tipoCartao[]','Tipo Cartão',$cli['id_tipoCartao'],2,3);
				  	?>			
				  		
				  	<label for="dt_validade_cartaoPJ" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
				<div class="col-sm-3">
				<input type="text" class="form-control dt_validade_cartaoPJ" id="dt_validade_cartaoPJ<?=$num?>" placeholder="Data de Validade" name="dt_validade_cartaoPF[]" value="<?=date('d/m/Y',strtotime($cli['dt_validade_cartaoPF'])) ?>" >
				</div>
			</div>
			<hr>
			</div>
			<?php endforeach; 
			if(!$cards): ?>
				<div id="cloneDiv1" class="cartoes">
			<div class="form-group">
				<input type="hidden" class="id_cartaoPJ" name="id_cartaoPJ[]" value="" id="id_cartaoPJ1"/>
				<label for="numero_cartaoPJ" style="color: #797676;" class="col-sm-2 control-label">Número Cartão</label>
				<div class="col-sm-3">
				<input type="text" class="form-control numero_cartaoPJ" id="numero_cartaoPJ1" placeholder="Número Cartão" name="numero_cartaoPJ[]" />
				</div>
				
				<label for="codigo_seguranca_cartaoPF" style="color: #797676;" class="col-sm-2 control-label">Código Segurança</label>
				<div class="col-sm-3">
				<input type="text" class="form-control codigo_seguranca_cartaoPJ" id="codigo_seguranca_cartaoPJ1" placeholder="Número Cartão" name="codigo_seguranca_cartaoPJ[]" />
					</div>
			</div>
			
			<div class="form-group">
				 	<?php 
				  	foreach($cartao as $cart){
				  		$opt_cart[$cart['id_tipoCartao']] = $cart['titulo_tipoCartao'];
				  	}
				  	$form->select($opt_cart,'id_tipoCartao[]','Tipo Cartão',1,2,3);
				  	?>			
				  		
				  	<label for="dt_validade_cartaoPJ" style="color: #797676;" class="col-sm-2 control-label">Data Validade</label>
				<div class="col-sm-3">
				<input type="text" class="form-control dt_validade_cartaoPJ" id="dt_validade_cartaoPJ" placeholder="Data de Validade" name="dt_validade_cartaoPJ[]" />
				</div>
			</div>
			<hr>
			</div>
			<?php endif; ?>
			<div class="form-group">
				<div class="col-sm-offset-5 col-sm-10">
				<button type="button" style="padding: 5px 20px" id="bt_add_ct" title="Adicionar novo Cartão de Crédito" class="btn btn-warning bt_add_ct"><span class="glyphicon glyphicon-plus"></span></button>
				<button type="button" style="padding: 5px 20px" id="bt_del_ct" title="Remover Cartão de Crédito" class="btn btn-danger bt_del_ct" disabled="disabled"><span class="glyphicon glyphicon-remove"></span></button>
				</div>
				</div>
			
	</fieldset>
		<?php						
		echo '<hr>';						
		
		
		######### Nome responsavel	############
		foreach($classificacao as $class){
			$opt_class[$class['id_classificacao']] = $class['titulo_classificacao'];
		}	
		$form->groupOpen();
		$form->select($opt_class,'id_classificacao','Classificação',$clientes[0]['id_classificacao']);
		$form->groupClose();		
		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'nomeresponsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'Nome Responsável',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Nome Responsável',
						'value' =>$clientes[0]['nomeresponsavel_clientePJ'],
						'required' => true
						));
						$form->groupClose();
						
		$form->groupOpen();		
		$form->input(array(
						'name' =>'email_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'Email Responsável',
						'num_label' =>'2',
						'num_input' =>'8',
						'label' =>'* Email Responsável',
						'value' =>$clientes[0]['email_responsavel_clientePJ'],
						'required' => true
						));
		$form->groupClose();
		
		
		$form->groupOpen();		
		$form->input(array(
						'name' =>'rg_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'RG Responsável',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* RG Responsável',
						'value' =>$clientes[0]['rg_responsavel_clientePJ'],
						'required' => true
						));
		$form->input(array(
						'name' =>'cpf_responsavel_clientePJ',
						'type' =>'text',
						'placeholder' => 'CPF Responsável',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* CPF Responsável',
						'value' =>$clientes[0]['cpf_responsavel_clientePJ'],
						'required' => true
						));
		$form->groupClose();


		$form->groupOpen();	
		$form->input(array(
						'name' =>'credito_clientePJ',
						'type' =>'text',
						'placeholder' => 'Créditos R$:',
						'num_label' =>'2',
						'num_input' =>'3',
						'label' =>'* Créditos',
						'value' =>$clientes[0]['credito_clientePJ'],
						'required' => true
						));	
		$form->select(array('1' =>'Ativo','0' =>'Inativo'),'status_cliente','Status',$clientes[0]['status_cliente']);
		$form->groupClose();

		$form->groupOpen();		
		$form->textarea('descricao_cliente','Descrição',$clientes[0]['descricao_cliente'],'Descrição',2,8);
		$form->groupClose();

		
				
	echo str_repeat('<br />',3);

	$form->groupOpen();		
	$form->submit('Atualizar','style="padding:5% 13%"');
	$form->groupClose();		
	
	$form->close();	
	
?>
</fieldset>
</div>
<script>
	jQuery(function(){
		jQuery('#nomefantasia_clientePJ').css('text-transform','uppercase');
		
		jQuery("#credito_clientePJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#cep_clientePJ").mask('99999-999');
		jQuery("#telefone_clientePJ").mask('(99)9999-9999');
		jQuery("#telefone2_clientePJ").mask('(99)9999-9999');
		jQuery("#cnpj_clientePJ").mask('99.999.999/9999-99');
		jQuery("#rg_responsavel_clientePJ").mask('99.999.999-9');
		jQuery("#cpf_responsavel_clientePJ").mask('999.999.999-99');
		jQuery(".dt_validade_cartaoPJ").mask('99/99/9999');
		
		
		jQuery("#cep_clientePJ").blur(function(){
			if(jQuery(this).val() != ''){
				jQuery.ajax({
					url: '/cliente/findCep',
					type: 'post',
					dataType: 'json',
					data: {cep: jQuery(this).val()},
					beforeSend: function(){
						jQuery('#form_clientePJ').attr('disabled',true);
					},
					success: function(data){
						jQuery('#form_clientePJ').attr('disabled',false);
						jQuery('#endereco_clientePJ').val(data.endereco);
						jQuery('#bairro_clientePJ').val(data.bairro);
						jQuery('#cidade_clientePJ').val(data.cidade);
						jQuery('#uf_clientePJ').val(data.uf);
						jQuery('#pais_clientePJ').val('Brasil');
						jQuery('#numero_clientePJ').focus();
					}
				});
			}
		});
		
		
		
		jQuery('#bt_add_ct').click(function(){

				num = jQuery('.cartoes').length;
				newNum = new Number(num + 1);

				var newElem = jQuery('#cloneDiv'+num).clone().attr('id','cloneDiv'+newNum).fadeIn('slow');

				newElem.find('.id_cartaoPJ').attr('id','id_cartaoPJ'+newNum).val('');
				newElem.find('.numero_cartaoPJ').attr('id','numero_cartaoPJ'+newNum).val('');
				newElem.find('.codigo_seguranca_cartaoPJ').attr('id','codigo_seguranca_cartaoPJ'+newNum).val('');
				newElem.find('.id_tipoCartao').attr('id','id_tipoCartao'+newNum);
				newElem.find('.dt_validade_cartaoPJ').attr('id','dt_validade_cartaoPJ'+newNum).val('');

				
				jQuery('#cloneDiv'+num).after(newElem);
				jQuery('#bt_del_ct').attr('disabled',false);
				jQuery('#dt_validade_cartaoPJ'+newNum).mask('99/99/9999');
				
			});
			
			
			jQuery('#bt_del_ct').click(function(){
				if(confirm('Deseja realmente remover esse cartão ?')){
				var num = jQuery('.cartoes').length;
				
				id_cartaoPJ = jQuery('#cloneDiv'+num).find("#id_cartaoPJ"+num).val();
				
				jQuery.ajax({
					url: '/cliente/delAjaxCartaoPJ',
					type: 'post',
					dataType: 'html',
					data: {id_cartaoPJ : id_cartaoPJ},
					success: function(data){
						
					}
				});
				
				
				jQuery('#cloneDiv'+num).slideUp('slow',function(){
					jQuery('#cloneDiv'+num).remove();
					if(num - 1 === 1){
						jQuery('#bt_del_ct').attr('disabled',true);
					}else{
						jQuery('#bt_del_ct').attr('disabled',false);
						}
					});
				}
			});
			
			jQuery('#bt_del_ct').attr('disabled',false);
		
	});
</script>