<?php

foreach ($dependentes as $key => $value) {
	$opt_dependentes[$value['id_dependentePF']] = $value['nome_dependente'];
}

foreach ($agencia as $key => $value) {
	$opt_agencia[$value['id_agencia']] = $value['logotipo_agencia'];
}

foreach ($brokers as $key => $value) {
	$opt_brokers[$value['id_brokers']] = $value['nome_brokers'];
}

foreach ($dependentes as $key => $value) {
	$opt_dependente[$value['id_dependentePF']] = $value['nome_dependente'];
}

$logo =  null;
if($venda[0]['id_agencia'] == '0'){
	$logo = $empresa[0]['logotipo_empresa'];
}else{
	$logo = $opt_agencia[$venda[0]['id_agencia']];
}

$logo = explode('/', $logo);
$logo = array_slice($logo,4);
$logo = '/'.implode('/',$logo);

?>
<div class="container">
	<div class="alerta">
		<div id="information">BONAMAIL</div>
		<div id="brokers_info" style=" float: right; margin-top: -1.5%; "><?=$opt_brokers[$hotel[0]['id_brokers']]?></div>
	</div>
	<hr style=" border-top: 1px solid #000; margin: 0" />
	<div class="logo_agencia"><img src="<?=$logo?>" width="20%" /></div>
	<div class="imformation_default">
		<center>
		<p><h2 style="color: #990000">BONAIL VOUCHER</h2></p>
		<p><h2 style="color: #990000">TO BE HANDED OVER HOTEL</h2></p>
		<p>With the guarantee</p>
		</center>
	</div>
	<hr style=" border-top: 1px solid #000; " />
	<br />
	<table class="table">
		<tr>
			<td>Booking Refenrence</td>
			<td>: <?=$hotel[0]['codigo_hotel']?></td>
		</tr>
		<?php foreach ($hospedes as $key => $value): ?>
		<tr>
			<td>On behalf of</td>
			<td>:<?=$opt_dependente[$value['id_dependentePF']]?></td>
		</tr>
		<?php endforeach; ?>
		
		<tr>
			<td>Hotel</td>
			<td>:<?=$hotel[0]['nome_hotel']?></td>
		</tr>
		<tr>
			<td>Address</td>
			<td>:<?=$hotel[0]['endereco_hotel']?></td>
		</tr>
		<tr>
			<td>Town</td>
			<td>:<?=$hotel[0]['cidade_hotel']?></td>
		</tr>
		<tr>
			<td>Province</td>
			<td>:<?=$hotel[0]['uf_hotel']?></td>
		</tr>
		<tr>
			<td>Country</td>
			<td>:<?=$hotel[0]['pais_hotel']?></td>
		</tr>
		<tr>
			<td>Telephone</td>
			<td>:<?=$hotel[0]['telefone_hotel']?></td>
		</tr>
	</table>
	
	<br />
	<div class="alerta">
		<div id="information">Services</div>
	</div>
	<table class="table">
		<thead>
			<th>From</th>
			<th>TO</th>
			<th>Type of room</th>
			<th>NIGHTS</th>
			<th>BOARD BASE</th>
		</thead>
		<tr>
			<td><?=date('dM',strtotime($hotel[0]['data_de_hotel']))?></td>
			<td><?=date(' dM',strtotime($hotel[0]['data_ate_hotel']))?></td>
			<td><?=$hotel[0]['tipo_quartos']?></td>
			<td><?=$hotel[0]['noites_hotel']?></td>
			<td><?=$hotel[0]['servicos_hotel']?></td>
		</tr>
	</table>
	<br />
	<hr style=" border-top: 1px solid #000; " />
	Remarks: Brooked and payable by <?=$opt_brokers[$hotel[0]['id_brokers']]?> and 7Brasil&nbsp;&nbsp;&nbsp;&nbsp;Check in:&nbsp;&nbsp;<?=$hotel[0]['checkin_hotel']?>
	 &nbsp;&nbsp;&nbsp;&nbsp;Check out:&nbsp;&nbsp;<?=$hotel[0]['ckeckout_hotel']?> 
	
</div>
<?php 

	// $this->dump($hotel);
	// $this->dump($hospedes);
	// $this->dump($venda);

?>
<style>
	.alerta {
		padding: 5px;
		background-color: #33CCFF;
	}
</style>
<script>
	jQuery(function(){
		jQuery('#hr').css('border-top','1px solid #000 !important;');
		print();
	});
</script>