<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/grupo/cadGrupo" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<!-- <form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Teste" name="teste">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form> -->
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Titulo','Status','Editar','Remover'));
	foreach($grupos as $grup){
			$table->t_row(array(
					$grup['titulo_grupo'],
					$grup['status_grupo'] == 1 ? 'Ativo' : 'Inativo',
					'<center><a href="/grupo/cadGrupo/id/'.$grup['id_grupo'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
					'<center><a href="grupo/deleteGrupo/id/'.$grup['id_grupo'].'" onclick=" return confirm(\'Deseja realmente remover '.$grup['titulo_grupo'].'	?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
					));
	}
	$table->generate();
	?>
</div>
