<?php
		$form->init('form_destino','/destino/saveDestino');
		$id = isset($destinos) ? $destinos['id_destino'] : null;
		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_destino',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' => $id,
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'nome_destino',
			'type' =>'text',
			'placeholder' => 'Nome',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Nome',
			'value' => isset($destinos) ? $destinos['nome_destino'] : null,
			'required' => true
			));
		$form->groupClose();
		
		$form->textarea('descricao_destino','Descrição', isset($destinos) ? $destinos['descricao_destino'] : null,'Descrição',2,5);
		echo str_repeat('<br />',3);
		
		$form->groupOpen();		
		$form->submit('Salvar','style="padding:5% 13%"');
		$form->groupClose();

		$form->close();