<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/processos/cadProcessos" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
	<form class="navbar-form navbar-right" role="search" method="post" action="/processos/findProccess"> 
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Nº Processo" name="nm_processo_venda">
		</div>
		<div class="form-group">
			<input type="date" class="form-control" name="dt_de">
		</div>
		<div class="form-group">
			<input type="date" class="form-control" name="dt_ate">
		</div>
		<div class="form-group">
			<select name="id_usuario" class="form-control">
				<option value="0">--TODOS--</option>
				<option value="3">WESLEI ANDRADE</option>
			</select>
		</div>
		<div class="form-group">
			<select name="id_clientePJ" class="form-control">
				<option value="0">--TODAS--</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form>
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Teste','Teste','Teste','Teste','Teste','Status','<center>Editar</center>','<center>Remover</center>'));
	$table->t_row(array(
						'teste',
						'teste',
						'teste',
						'teste',
						'teste',
						'Ativo',
						'<center><a href="#"><span class="glyphicon glyphicon-pencil"></span></a></center>',
						'<center><a href="#" onclick=" return confirm(\'Deseja realmente remover ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
						));
	$table->generate();
	?>
</div>
