<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/usuario/cadUsuario" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<!-- <form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Teste" name="teste">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form> -->
	<?php 
	$table->t_init('class="table table-bordered" id="tbl_usuario"');
	$table->t_head(array('Nome','Login','Grupo','Status','Editar','Remover'));
	foreach($usuarios as $user){
		$table->t_row(array(
							$user['nome_usuario'],
							$user['login_usuario'],
							$user['titulo_grupo'],
							$user['status_usuario'] == 1 ? 'Ativo' : 'Inativo',
							'<center><a href="/usuario/cadUsuario/id/'.$user['id_usuario'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
							'<center><a href="/usuario/deleteUsuario/id/'.$user['id_usuario'].'" onclick=" return confirm(\'Deseja realmente remover '.$user['nome_usuario'].' ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
							));
	}
	$table->generate();
	?>
</div>
<script>
	jQuery(function(){
		// jQuery('#tbl_usuario').dataTable();
	});
</script>