<?php 
// $this->dump($_SESSION);
if(isset($_SESSION['success'])){
	echo '<div class="alert alert-success">'.$session->getFlashMessage('success').'</div>';
}

if(isset($_SESSION['error'])){
	echo '<div class="alert alert-danger">'.$session->getFlashMessage('error').'</div>';
}
?>
<div class="list_dependente_pf">
<h3 style="color: #C7187D">Cadastrado de Dependentes</h3>
<br />
	<a href="/dependente/cadDependentePF" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	<br />
	<br />
	<?php
	foreach ($cliente as $key => $value) {
		$opt_cliente[$value['id_clientePF']] = $value['nome_clientePF'];
	} 
	?>
<br>
	<?php
	$table->t_init('class="table table-bordered" id="tbl_dependente"');
	$table->t_head(array('Nome','CPF','Cliente','Editar','Excluir'));
	
	foreach($dependentes as $dep){
		if($dep['id_departamento'] == null){
		$table->t_row(array(
			$dep['nome_dependente'],
			$dep['cpf_dependente'],
			$opt_cliente[$dep['id_clientePF']],
			'<center><a href="/dependente/updateDependentePF/id/'.$dep['id_dependentePF'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
			'<center><a href="/dependente/deleteDependentePF/id/'.$dep['id_dependentePF'].'" onclick="return confirm(\'Deseja Realmente remover '.$dep['nome_dependente'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>')
			);
		}
	}
	$table->generate();
	?>
</div>
<script>
	jQuery(function(){
		jQuery('[name=cpf_dependente]').mask('999.999.999-99');
		jQuery('#tbl_dependente').dataTable();
	});
</script>