<?php 

if(isset($_SESSION['success'])){
	echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
}

if(isset($_SESSION['error'])){
	echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
}

?>

<a href="/tipoPagamento/cadTipoPagamento" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	<br />
	<br />
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Titúlo','Dias','Porcentagem','Status','Editar','Remover'));
	foreach($tipopagamentos as $tipo){
		$table->t_row(array(
					$tipo['titulo_tipoPagamento'],
					$tipo['dias_recebimento_tipoPagamento'],
					$tipo['porcentagem_tipoPagamento'],
					$tipo['status_tipoPagamento'] == 1? 'Ativo' : 'Inativo',
					'<center><a href="/tipoPagamento/cadTipoPagamento/id/'.$tipo['id_tipoPagamento'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
					'<center><a href="/tipoPagamento/deleteTipoPagamento/id/'.$tipo['id_tipoPagamento'].'" onclick=" return confirm(\'Deseja realmente remover '.$tipo['titulo_tipoPagamento'].' ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
					));
	}
	$table->generate();
	?>
</div>
