<h3>Cadastrar Departamento</h3>
<?php 

	foreach($clientes as $cli){
		$opt_cli[$cli['id_clientePJ']] = $cli['nomefantasia_clientePJ'];
	}
	$form->init('form_departamento','/departamento/saveDepartamento','post');
	
	
	$id = isset($deptos) ? $deptos[0]['id_departamento'] : null;
	
	echo '<input type="hidden" name="id_departamento" value="'.$id.'" />';
	
	$form->groupOpen();
	$form->select($opt_cli,'id_clientePJ','Empresa','1',2,3);
	$form->groupClose();
	
	
	$form->groupOpen();	
	$form->input(array(
					'name' =>'codigo_centrocusto',
					'type' =>'text',
					'placeholder' => 'Codigo Departamento',
					'num_label' =>'2',
					'num_input' =>'3',
					'label' =>'Codigo',
					'value' => isset($deptos) ? $deptos[0]['codigo_centrocusto'] : null,
					'required' => false
					));
	$form->groupClose();
	
	
	$form->groupOpen();	
	$form->input(array(
					'name' =>'nome_departamento',
					'type' =>'text',
					'placeholder' => 'Nome',
					'num_label' =>'2',
					'num_input' =>'5',
					'label' =>'Nome',
					'value' => isset($deptos) ? $deptos[0]['nome_departamento'] : null,
					'required' => true
					));
	$form->groupClose();
	
	
	$form->groupOpen();
	$form->select(array('1'=>'Ativo','0'=>'Inativo'),'status_departamento','Empresa',isset($deptos) ? $deptos[0]['status_departamento'] : '1',2,3);
	$form->groupClose();
	
	$form->textarea('descricao_departamento','Descrição',isset($deptos) ? $deptos[0]['descricao_departamento'] : null,'Descrição',2,5);
	echo '<br />';
	$form->groupOpen();
	$form->submit(isset($deptos) ? 'Atualiazar' : 'Salvar');
	$form->groupClose();
	
	$form->close();
?>