<?php 
if(isset($_SESSION['success'])){
	echo '<div class="alert alert-success">'.$session->getFlashMessage('success').'</div>';
}

if(isset($_SESSION['error'])){
	echo '<div class="alert alert-danger">'.$session->getFlashMessage('error').'</div>';
}
?>

<a href="/departamento/cadDepartamento" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>

<form class="navbar-form navbar-right" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Empresa" name="nome_empresa">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Departamento" name="nome_departameto">
  </div>
  <div class="form-group">
   <select name="id_cliente" class="form-control">
   	<option>TODOS</option>
   	<option value="3">ANDWES SOLUTION </option>   </select>
  </div>
  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
</form>

<br />
<?php 

$table->t_init('class="table table-bordered"');
$table->t_head(array('Departamento','Empresa','Status','Editar','Excluir'));
foreach($departamentos as $dep){
	$table->t_row(array(
			$dep['nome_departamento'],
			$dep['nomefantasia_clientePJ'],
			($dep['status_departamento'] == '1' ? 'Ativo' : 'Inativo'),
			'<center><a href="/departamento/cadDepartamento/id/'.$dep['id_departamento'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
			'<center><a href="/departamento/deleteDepartamento/id/'.$dep['id_departamento'].'" onclick=" return confirm(\'Deseja realmente remover '.$dep['nome_departamento'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'));
	
}
$table->generate();
?>