<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/agencia/cadAgencia" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	<form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Teste" name="teste">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form>
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','CNPJ','Telefone','Logo','Status','Editar','Remover'));
	foreach($agencias as $ag){
		$img = explode('/',$ag['logotipo_agencia']);
		$img = array_slice($img,4);
		$table->t_row(array(
					$ag['nomefantasia_agencia'],
					$ag['cnpj_agencia'],
					$ag['telefone_agencia'],
					"<center><img src='/".implode('/', $img)."' width='50' alt=\"Logotipo\" class=\"img-rounded\"></center>",
					$ag['status_agencia'] == 1 ? 'Ativo' : 'Inativo',
					'<center><a href="/agencia/cadAgencia/id/'.$ag['id_agencia'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
					'<center><a href="/agencia/deleteAgencia/id/'.$ag['id_agencia'].'" onclick=" return confirm(\'Deseja realmente remover '.$ag['nomefantasia_agencia'].' ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
					));
	}
	$table->generate();
	?>
</div>
