<div class="lista_locadora">
	<?php 
	if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
	?>
	<a href="/locadora/cadLocadora" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
	<form class="navbar-form navbar-right" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Nome" name="nome_funcionario">
		</div>
		<div class="form-group">
			<select name="id_cliente" class="form-control">
				<option>Locadora</option>
				<option value="3">ANDWES SOLUTION </option>
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-search"></span> Buscar
		</button>
	</form>
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','Telefone','Status','Editar','Remover'));
	foreach($locadoras as $loc){
		$table->t_row(array(
						$loc['nome_locadora'],
						$loc['telefone_locadora'],
						($loc['telefone_locadora'] != 1)? 'Ativo' : 'Inativo',
						'<center><a href="/locadora/cadLocadora/id/'.$loc['id_locadora'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
						'<center><a href="/locadora/deleteLocadora/id/'.$loc['id_locadora'].'" onclick=" return confirm(\'Deseja realmente remover '.$loc['nome_locadora'].'?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
						));
	}
	$table->generate();
	?>
</div>