<?php

	$id  = isset($tipocomps) ? $tipocomps[0]['id_tipocomp'] : null;
		$form->init('form_tipocomp','/tipoComp/saveTipoComp');
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'id_tipocomp',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $id,
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'titulo_tipocomp',
				'type' =>'text',
				'placeholder' => 'Titulo',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Titulo',
				'value' => isset($tipocomps) ? $tipocomps[0]['titulo_tipocomp'] : null,
				'required' => true
				));
		$form->groupClose();
		
		echo str_repeat('<br />',3);
		
		$form->groupOpen();		
		$form->submit('Salvar','style="padding:5% 13%"');
		$form->groupClose();
		
		$form->close();