<?php
		$id = isset($seguradoras) ? $seguradoras[0]['id_seguradora'] : null;
		$form->init('form_seguradora','/seguradora/saveSeguradora');
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'id_seguradora',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $id,
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'nome_seguradora',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Nome',
				'value' => isset($seguradoras) ? $seguradoras[0]['nome_seguradora'] : null,
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'logo_seguradora',
				'type' =>'file',
				'placeholder' => 'Logotipo',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Logotipo',
				'value' =>'',
				'required' => true
				));
			if(isset($seguradoras)){
				$img = explode('/',$seguradoras[0]['logo_seguradora']);
				$img = array_slice($img,4);
				echo "<img src='/".implode('/', $img)."' width='150' alt=\"Logotipo\" class=\"img-rounded\">";
			}
		$form->groupClose();
		
		$form->groupOpen();	
		$form->select(array('1'=>'Ativo','0'=>'Inativo'),'status_seguradora','Status',isset($seguradoras) ? $seguradoras[0]['status_seguradora'] : 1);		
		$form->groupClose();
		echo str_repeat('<br />',3);
		
		$form->groupOpen();		
		$form->submit('Salvar','style="padding:5% 13%"');
		$form->groupClose();
		
		$form->close();