<?php

foreach ($grupo as $key => $value) {
	$opt_grupo[$value['id_grupo']] = $value['titulo_grupo'];
}

$id = isset($subgrupos)? $subgrupos['id_subgrupo'] : null;
			$form->init('form_subgrupo','/subgrupo/saveSubgrupo');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_subgrupo',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $id,
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->select($opt_grupo,'id_grupo','Grupo',isset($subgrupos)? $subgrupos['id_grupo'] : 1,2,4);
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'titulo_subgrupo',
				'type' =>'text',
				'placeholder' => 'Título',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Título',
				'value' => isset($subgrupos)? $subgrupos['titulo_subgrupo'] : null,
				'required' => true
				));
			$form->groupClose();
			$form->textarea('descricao_subgrupo','Descrição',isset($subgrupos)? $subgrupos['descricao_subgrupo'] : null,'Descrição',2,5);
		
		echo str_repeat('<br />',3);
								
								
			$form->groupOpen();		
			$form->submit('Salvar','style="padding:5% 13%"');
			$form->groupClose();
			

			$form->close();