<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/subgrupo/cadSubgrupo" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Titulo','Status','Editar','Remover'));
	foreach ($subgrupos as $key => $value) {
		$table->t_row(array(
				$value['titulo_subgrupo'],
				$value['status_subgrupo'] == '1' ? 'Ativo' : 'Inativo',
				'<center><a href="/subgrupo/cadSubgrupo/id/'.$value['id_subgrupo'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
				'<center><a href="/subgrupo/deleteSubgrupo/id/'.$value['id_subgrupo'].'" onclick=" return confirm(\'Deseja realmente remover Subgrupo?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
				));
	}
		$table->generate();
	?>
</div>
