<?php
$date = new DateTime();
?>
<div class="row">
	<?php
	foreach($cambios as $cam){
		$opt_camb[$cam['id_cambio']] = $cam['titulo_cambio'];
	}
	
	 ?>
	
	<?php
	 foreach($moedas as $moe): ?>
	  <?php if(date('Y-m-d',strtotime($moe['dt_moeda'])) == date('Y-m-d')) { ?>
	<div class="col-md-4">
		<center>
		<h3><?=$opt_camb[$moe['id_cambio']]?></h3>
		<h3 style="color:#000;"><?=$moe['valor_moeda']?></h3>
		</center>
	</div>
	 <?php } ?>
	<?php endforeach; ?>
</div>
<div class="separator"></div>

