<div id="container">
	<div id="header">
		<div class="container">
			<div class="logged">
				<span>Olá Weslei</span><a href="#" class="sair">Logout</a>
			</div>
			<a href="/" title="7ete - System by 7brasil" class="logo"> <img src="/skin/img/logo-sys.png" alt="logo 7ete"> </a>
			<div class="menuNav">
				<ul>
					<li class="">
						<a href="#" title="Configurações">Configurações</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="/empresa" title="Empresa dententora do sistema">Empresa</a></li>
							<li class=""><a href="/cambio" title="Nome das moedas internacionais">Cambio</a></li>
							<li class=""><a href="/tipoPagamento" title="Tipos de Pagamento permitido pela empresa">Tipos de Pagamento</a></li>
							<li class=""><a href="/filial" title="Filiais da empresa">Filiais</a></li>
							<li class=""><a href="/grupo" title="Grupos de usuários">Grupos</a></li>
							<li class=""><a href="/usuario" title="Usuários">Usuários</a></li>
							<li class=""><a href="#" title="Permissões de usuário">Permissões</a></li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Cadastro">Cadastros</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="/cliente" title="Clientes">Clientes</a></li>
							<li class=""><a href="/locadora" title="Locadoras">Locadoras</a></li>
							<li class=""><a href="/brokers" title="Sites de reservas de Hotéis">Brokers</a></li>
							<li class=""><a href="#" title="Vendas">Vendas</a></li>
							<li class=""><a href="/agencia" title="Agências">Agências</a></li>
							<li class=""><a href="#" title="Fornecedores">Tickets</a></li>
							<li class=""><a href="#" title="Nome dos continentes das viajens">Continentes</a></li>
							<li class=""><a href="#" title="Tipo de Compania se nacional ou internacional">Tipo de Compania</a></li>
							<li class=""><a href="#" title="Seguradora">Seguradora</a></li>
							<li class=""><a href="#" title="Tipo de Seguro">Tipo de Seguro</a></li>
							<li class=""><a href="#" title="Participação do cliente na venda - Ex: Pagante ou pagante e participante">Participação</a></li>

						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Controles">Relatórios</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="#" title="Embarques">Embarques</a></li>
							<li><a href="#" title="Compromissos">Compromissos</a></li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Gerenciamento">Finaceiro</a>
						<ul class="submenu" style="display: none;">
							<li>
								<a href="#" title="Ranking de Clientes">Ranking de Clientes</a>
							</li>
							<li>
								<a href="#" title="Ranking de Fornecedores">Ranking de Fornecedores</a>
							</li>
							<li>
								<a href="#" title="Vendas Consultor">Vendas Consultor</a>
							</li>
							<li>
								<a href="#" title="Vendas Representantes">Vendas Representantes</a>
							</li>
							<li>
								<a href="#" title="Logs">Logs</a>
							</li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Financeiro">Agencias</a>
						<ul class="submenu">
							<li>
								<a href="#" title="Faturamento">Faturamento</a>
							</li>
							<li>
								<a href="#" title="Emissão de Vouchers">Emissão de Voucher</a>
							</li>
							<li>
								<a href="#" title="A Pagar">A Pagar</a>
							</li>
							<li>
								<a href="#" title="A Receber">A Receber</a>
							</li>
						</ul
					</li>
				</ul>
			</div>

		</div>
	</div>
	<div class="container">
		<div class="">
			<div class="wrapper">
