<div id="container">
	<div id="header">
		<div class="container">
			<div class="logged">
				
				<span>Olá <?=$_SESSION['user']['nome_usuario'];?></span><a href="/login/logout" class="sair">Logout</a>
			</div>
			<a href="/" title="7ete - System by 7brasil" class="logo"> <img src="/skin/img/logo-sys.png" alt="logo 7ete"> </a>
			<div class="menuNav">
				<ul>
					<li class="">
						<a href="#" title="Configurações">Configurações</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="/empresa" title="Empresa dententora do sistema">Empresa</a></li>
							<li class=""><a href="/cambio" title="Nome das moedas internacionais">Moeda</a></li>
							<li class=""><a href="/moeda" title="Cambio do dia">Cambio</a></li>
							<li class=""><a href="/tipoPagamento" title="Tipos de Pagamento permitido pela empresa">Tipos de Pagamento</a></li>
							<li class=""><a href="/tipoCartao" title="Nomes dos cartões de crédito permitido pela empresa">Tipos de cartões</a></li>
							<li class=""><a href="/filial" title="Filiais da empresa">Filiais</a></li>
							<li class=""><a href="/usuario" title="Usuários">Usuários</a></li>
							<li class=""><a href="#" title="Permissões de usuário">Permissões</a></li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Cadastro">Cadastros</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="/cliente" title="Clientes">Clientes</a></li>
							<li class=""><a href="/locadora" title="Locadoras">Locadoras</a></li>
							<li class=""><a href="/brokers" title="Sites de reservas de Hotéis">Brokers</a></li>
							<li class=""><a href="/agencia" title="Agências">Agências</a></li>
							<li class=""><a href="/agente" title="Agentes de agências parceiras">Agentes</a></li>
							<li class=""><a href="/ticket" title="Fornecedores">Tickets</a></li>
							<li class=""><a href="/continente" title="Nome dos continentes das viajens">Continentes</a></li>
							<li class=""><a href="/compania" title="Companias aéreas">Companias Aérea</a></li>
							<li class=""><a href="/classe" title="Classe de passagens aérea">Classe de Voo</a></li>
							<li class=""><a href="/origem" title="Origem de passagens aérea">Origem Passagens</a></li>
							<li class=""><a href="/destino" title="Destino de passagens aérea">Destino Passagens</a></li>
							<li class=""><a href="/tipoComp" title="Tipo de Compania se nacional ou internacional">Tipo de Compania</a></li>
							<li class=""><a href="/seguradora" title="Seguradora">Seguradora</a></li>
							<li class=""><a href="/tipoSeguro" title="Tipo de Seguro">Tipo de Seguro</a></li>
							<li class=""><a href="/companiaCruzeiro" title="Nome de campanias de cruzeiro">Companias de Cruzeiro</a></li>
							<!-- <li class=""><a href="/participacao" title="Participação do cliente na venda - Ex: Pagante ou pagante e participante">Participação</a></li> -->

						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Controles">Relatórios</a>
						<ul class="submenu" style="display: none;">
							<li class=""><a href="/passageiro" title="Lista de Passageiros">Passageiros</a></li>
							<li class=""><a href="/resultado" title="Demonstrativo de Resultado">Resultado</a></li>
							<li><a href="#" title="Compromissos">Compromissos</a></li>
							<li><a href="#" title="Compromissos">Vendedor</a></li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Gerenciamento">Finaceiro</a>
						<ul class="submenu" style="display: none;">
							<li><a href="/processosPJ" title="Processos de vendas">Processos</a></li>
							<li><a href="/contas" title="Cadastro de contas a pagar">Contas à Pagar</a></li>
							<li><a href="/receber" title="Contas à Receber">Contas à Receber</a></li>
							<li class=""><a href="/grupo" title="Grupos de usuários">Grupos</a></li>
							<li><a href="/subgrupo" title="Subgrupos de despesas">Subgrupos</a></li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class=""><a href="#" title="Vendas">Vendas</a>
						<ul class="submenu" style="display: none;">
							<li><a href="/venda/cadVendaPF" title="cadastro de venda para pessoa física">Pessoa Física</a></li>
							<li><a href="/vendaPJ/cadVendaPJ" title="cadastro de venda para pessoa jurídica">Pessoa Jurídica</a></li>
						</ul>
					</li>
			</div>

		</div>
	</div>
	<div class="container">
		<div class="">
			<div class="wrapper">
