<div id="container">
	<div id="header">
		<div class="container">
			<div class="logged">
				<span>Olá Weslei</span><a href="#" class="sair">Logout</a>
			</div>
			<a href="/" title="7ete - System by 7brasil" class="logo"> <img src="/skin/img/logo-sys.png" alt="logo 7ete"> </a>
			<div class="menuNav">
				<ul>
					<li class="">
						<a href="#" title="Configurações">Configurações</a>
						<ul class="submenu" style="display: none;">
							<li class="">
								<a href="#" title="Usuários">Usuários</a>
							</li>
							<li class="">
								<a href="#" title="Departamentos">Departamentos</a>
							</li>
							<li class="">
								<a href="#" title="Condições Gerais">Condições Gerais</a>
							</li>
							<li class="">
								<a href="#" title="Contrato">Contrato</a>
							</li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Cadastro">Cadastros</a>
						<ul class="submenu" style="display: none;">
							<li class="">
								<a href="/cliente" title="Clientes">Clientes</a>
							</li>
							<li class="">
								<a href="/locadora" title="Locadoras">Locadoras</a>
							</li>
							<li class="">
								<a href="#" title="Hotéis">Hotéis</a>
							</li>
							<li class="">
								<a href="#" title="Carros">Carros</a>
							</li>
							<li class="">
								<a href="#" title="Seguros">Seguros</a>
							</li>
							<li class="">
								<a href="#" title="Vendas">Vendas</a>
							</li>
							<li class="">
								<a href="#" title="Agências">Agências</a>
							</li>
							<li class="">
								<a href="#" title="Fornecedores">Fornecedores</a>
							</li>
							<li class="">
								<a href="#;" title="Pacotes">Pacotes</a>
							</li>

						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Controles">Relatórios</a>
						<ul class="submenu" style="display: none;">
							<li class="">
								<a href="#" title="Embarques">Embarques</a>
							</li>
							<li>
								<a href="#" title="Compromissos">Compromissos</a>
							</li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Gerenciamento">Finaceiro</a>
						<ul class="submenu" style="display: none;">
							<li>
								<a href="#" title="Ranking de Clientes">Ranking de Clientes</a>
							</li>
							<li>
								<a href="#" title="Ranking de Fornecedores">Ranking de Fornecedores</a>
							</li>
							<li>
								<a href="#" title="Vendas Consultor">Vendas Consultor</a>
							</li>
							<li>
								<a href="#" title="Vendas Representantes">Vendas Representantes</a>
							</li>
							<li>
								<a href="#" title="Logs">Logs</a>
							</li>
						</ul>
					</li>
					<li class="separador">
						&nbsp;
					</li>
					<li class="">
						<a href="#" title="Financeiro">Agencias</a>
						<ul class="submenu">
							<li>
								<a href="#" title="Faturamento">Faturamento</a>
							</li>
							<li>
								<a href="#" title="Emissão de Vouchers">Emissão de Voucher</a>
							</li>
							<li>
								<a href="#" title="A Pagar">A Pagar</a>
							</li>
							<li>
								<a href="#" title="A Receber">A Receber</a>
							</li>
						</ul
					</li>
				</ul>
			</div>

		</div>
	</div>
	<div class="container">
		<div class="">
			<div class="wrapper">
