<!DOCTYPE html>
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php echo $title ?></title>
		
		
	<link href="http://7brasil.local/favicon.ico" type="image/x-icon" rel="icon">
	<link href="http://7brasil.local/favicon.ico" type="image/x-icon" rel="shortcut icon">
	<link rel="stylesheet" type="text/css" href="/skin/css/nivo.css">
	<link rel="stylesheet" type="text/css" href="/skin/css/style.css">
	<link rel="stylesheet" type="text/css" href="/skin/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/skin/css/bootstrap-theme.css">
	<link rel="stylesheet" href="/skin/css/jquery-ui.css" />
	<link rel="stylesheet" href="/skin/css/jquery.dataTables.css" />
	<link rel="stylesheet" href="/skin/css/SampleForPrint.css" />
	
	<script type="text/javascript" src="/skin/js/jquery-1.10.1.min.js"></script>
	<script type="text/javascript" src="/skin/js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="/skin/js/nivo.js"></script>
	<script type="text/javascript" src="/skin/js/scripts.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.maskedinput.min.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.maskMoney.js"></script>
	<script type="text/javascript" src="/skin/js/bootstrap.js"></script>
	<script src="/skin/js/jquery-ui.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.dataTables.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.printElement.js"></script>
	
	
</head>
<body>
	