<?php
if(isset($_SESSION['success'])){
		echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
	}
	
	if(isset($_SESSION['error'])){
		echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
	}
?>
<a href="/agente/cadAgente" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Novo</a>
<br />
<br />
	<?php 
	$table->t_init('class="table table-bordered"');
	$table->t_head(array('Nome','Agencia','Status','Editar','Remover'));

	foreach($agencias as $key => $value){
		$opt_agenc[$value['id_agencia']] = $value['nomefantasia_agencia'];
	}
	foreach($agentes as $key => $value){
		$table->t_row(array(
				$value['nome_agente'],
				// ceil($value['porcentagem_agente']).' %',
				$opt_agenc[$value['id_agencia']],
				$value['status_agente'] == 1 ? 'Ativo' : 'Inativo',
				'<center><a href="/agente/cadAgente/id/'.$value['id_agente'].'"><span class="glyphicon glyphicon-pencil"></span></a></center>',
				'<center><a href="/agente/deleteAgente/id/'.$value['id_agente'].'" onclick=" return confirm(\'Deseja realmente remover Agente ?\')"><span class="glyphicon glyphicon-remove"></span></a></center>'
				));
	}
	$table->generate();
	?>
</div>
