<div class="venda">
	<?php 
	if(isset($_SESSION['success'])){
       	echo '<div class="alert alert-success">'.$this->session->getFlashMessage('success').'</div>';
       }
	   
	    if(isset($_SESSION['error'])){
       	echo '<div class="alert alert-danger">'.$this->session->getFlashMessage('error').'</div>';
       }
	?>

       <form method="post" action="/vendaPJ/findClientePJ" id="form_addClientePJ" role="form" class="form-horizontal">
       		<label for="cnpj_clientePJ" style="color: #797676;" class="col-sm-1 control-label">CNPJ</label>
       		<div class="col-sm-3">
       			<input type="text" class="form-control" id="cnpj_clientePJ" placeholder="CNPJ da Empresa" name="cnpj_clientePJ" value="">
       			</div>
       			<button type="button" id="bt_findClientePJ" data-toggle="modal" data-target="#myModal" class="btn btn-primary" disabled="disabled">
       				<span class="glyphicon glyphicon-search"></span> Buscar</button> 
       			<a href="/cliente/cadjuridica" type="button" id="bt_addNewPJ" class="btn btn-primary"><i class="glyphicon glyphicon-user"></i> Novo</a>
       	</form>
</div>       
      
      
      <?php $this->dump($_SESSION); ?>
      
      <?php foreach ($departamento->list_all() as $key => $value) {
          $opt_departamento[$value['id_departamento']] = $value['nome_departamento'];
      } 
      
	  foreach($locadoras as $key => $value){
	  	$opt_locadora[$value['id_locadora']] = $value['nome_locadora'];
	  }
      
	  foreach ($brokers as $key => $value) {
		  $opt_brokers[$value['id_brokers']] = $value['nome_brokers'];
	  }
	  
	  foreach ($cambios as $key => $value) {
		  $opt_cambio[$value['id_cambio']] = $value['titulo_cambio'];
	  }
	  
	  foreach ($seguradora as $key => $value) {
		  $opt_seguradora[$value['id_seguradora']] = $value['nome_seguradora'];
	  }
	  
	  foreach ($tipoSeguro as $key => $value) {
		  $opt_tipoSeguro[$value['id_tipoSeguro']] = $value['nome_tipoSeguro'];
	  }
	  
	  foreach ($continente as $key => $value) {
		  $opt_continente[$value['id_continente']] = $value['nome_continente'];
	  }
	  
	  foreach ($ticket as $key => $value) {
		  $opt_ticket[$value['id_ticket']] = $value['nome_ticket'];
	  }
	  
	  foreach ($companiaCruzeiro as $key => $value) {
		  $opt_companiaCruzeiro[$value['id_compania_cruzeiro']] = $value['nome_compania_cruzeiro'];
	  }
	  
	  foreach ($compania as $key => $value) {
		  $opt_compania[$value['id_compania']] = $value['nome_compania'];
	  }
	  
	  foreach ($classe as $key => $value) {
		  $opt_classe[$value['id_classe']] = $value['titulo_classe'];
	  }
	  
	  foreach ($origem as $key => $value) {
		  $opt_origem[$value['id_origem']] = $value['nome_origem'].' - '.$value['codigo_origem'];
	  }
	  
	  foreach ($destino as $key => $value) {
		  $opt_destino[$value['id_destino']] = $value['nome_destino'].' - '.$value['codigo_destino'];
	  }
	  
	  foreach ($tipoCartao as $key => $value) {
		  $opt_tipoCartao[$value['id_tipoCartao']] = $value['titulo_tipoCartao'];
	  }
	  
	  foreach ($tipoPagamento as $key => $value) {
		  $opt_tipoPagamento[$value['id_tipoPagamento']] = $value['titulo_tipoPagamento'];
	  }
      ?>
      
      	<!-- Modal cliente Pessoa Júridica -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						×
					</button>
					<h4 class="modal-title" id="myModalLabel">Empresa Cadastrada</h4>
				</div>
				<div class="modal-body">
						<form method="post" action="/vendaPJ/addClientePJ">
						<input id="id_PJ" name="id_PJ" type="hidden">
						
						<div id="nomefantasia_PJ"></div>
						<div id="cnpj_PJ"></div>
						<div id="endereco_PJ"></div>
						<div id="cidade_PJ"></div>
						<div id="uf_PJ"></div>
						<div id="telefone_PJ"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
					<button type="submit" id="bt_incluir" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				</form>
					
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	
	  	<!-- Modal Funcionarios -->
	<div class="modal fade" id="modalFuncionario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content" style=" width: 115%;">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title" id="myModalLabel">Funcionários</h4>
				</div>
				<div class="modal-body">
					<form action="/vendaPJ/addDependentePJ" method="post">
					<!-- <input type="checkbox" id="todos" /> Todos -->
					<?php if(isset($_SESSION['empresa'])): ?>
						<?php foreach ($departamento->list_all() as $key => $value): ?>
							<p><label><strong><?=$value['nome_departamento']?></strong></label></p>
						<?php  foreach ($funcionarios->getDependentePJ($_SESSION['empresa']['id']) as $chave => $valor) {
								if($value['id_departamento'] == $valor['id_departamento']){ ?>
								<p><input type="checkbox" name="id_dependentePJ[]" value="<?=$valor['id_dependentePJ']?>" class="marcar" /> <?=$valor['nome_dependentePJ']?>  -  CPF: <?=$valor['cpf_dependentePJ']?></p>
						
						<?php
								}
							 } 
						 ?>
						<?php endforeach; ?>
						
					<?php endif; ?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirFuncionario" class="btn btn-primary" ><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					</form>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	  	<!-- Modal Passagens -->
	
	
	
	   	<!-- Modal dependente cliente -->
	<div class="modal fade" id="modalDependente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						×
					</button>
					<h4 class="modal-title" id="myModalLabel">Dependentes</h4>
				</div>
				<div class="modal-body">
				<form method="post" action="/venda/addDependente">
				<div class="dependentePF">	</div>
						
				</form></div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirDependente" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
					
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
		   
	
	<br>
	<br>
	<br>
	
	   	<!-- Modal de aluguel de carros -->
	<div class="modal fade" id="modalCarros" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Aluguel de Carros</h4>
				</div>
				<div class="modal-body">
					<div class="carroPF">	
						<?php 
						$form->init('formAddCarro','/carro/saveCarroPJ','post');
						
						$form->groupOpen();
						$form->select($opt_locadora,'id_locadora','Locadora',1,2,5);
						$form->groupClose();

						$form->groupOpen();
						foreach($cambios as $key => $value){
							$op_cambio[$value['id_cambio']] = $value['titulo_cambio'];
						}
						$op_cambio['0'] = 'REAL BR';
						$form->select($op_cambio,'id_moeda','Moeda',0,2,5);
						$form->input(array(
							'name' =>'valor_cambio',
							'type' =>'text',
							'placeholder' => '',
							'num_label' =>'1',
							'num_input' =>'2',
							'label' =>'Valor',
							'value' => '',
							'required' => true
							));						$form->groupClose();
						
						
						echo "<input type='hidden' name='id_clientePJ' value='".$_SESSION['empresa']['id']."'>";
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'dt_inicio_carroPJ',
							'type' =>'date',
							'placeholder' => 'Data de início',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Início',
							'value' => '',
							'required' => true
							));
							
						$form->input(array(
							'name' =>'hora_inicio_carroPJ',
							'type' =>'time',
							'placeholder' => 'Horário de início',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Início',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();	
						$form->input(array(
							'name' =>'dt_devolucao_carroPJ',
							'type' =>'date',
							'placeholder' => 'Data de Devolução',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Fim',
							'value' => '',
							'required' => true
							));	
							
							$form->input(array(
							'name' =>'hora_devolucao_carroPJ',
							'type' =>'time',
							'placeholder' => 'Horário de Devolução',
							'num_label' =>'2',
							'num_input' =>'3',
							'label' =>'Hora Fim',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_inicio_carroPJ',
							'type' =>'text',
							'placeholder' => 'Local de retirada',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Retirada',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'local_devolucao_carroPJ',
							'type' =>'text',
							'placeholder' => 'Local de Devolução',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Devolução',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'voucher_carroPJ',
							'type' =>'file',
							'placeholder' => '',
							'num_label' =>'2',
							'num_input' =>'8',
							'label' =>'Voucher',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_carroPJ',
							'type' =>'text',
							'placeholder' => 'Valor do Aluguel',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Aluguel',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'valor_casa_carroPJ',
							'type' =>'text',
							'placeholder' => 'Comissão da Casa',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Comissão',
							'value' => '',
							'required' => true
							));	
						$form->groupClose();
						
						$form->groupOpen();
						$form->input(array(
							'name' =>'taxa_carroPJ',
							'type' =>'text',
							'placeholder' => 'Taxas Extras',
							'num_label' =>'2',
							'num_input' =>'4',
							'label' =>'Taxas',
							'value' => '',
							'required' => false
							));	
						$form->groupClose();
						 ?>
						 <label>Descrição</label>
						 <textarea name="descricao_carroPJ" class="form-control" rows="3"></textarea>
					</div><!-- div carroPF-->
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirCarro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	   	<!-- Modal de aluguel de carros -->
	   	
	   	
	   	
	   		
	   		<!-- Modal Hotel -->
	<div class="modal fade" id="modalHotel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Hotel</h4>
				</div>
				<div class="modal-body">
		<?php
			$form->init('form_hotel','/hotel/saveHotelPJ');
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_hotelPJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => '',
				'required' => false
				));
			$form->groupClose();
			
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_clientePJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $_SESSION['empresa']['id'],
				'required' => false
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->select($opt_brokers,'id_brokers','Brokers',0,2,8);
			$form->groupClose();


			$form->groupOpen();	
			$opt_cambio['0'] = 'Real BR';
			$form->select($opt_cambio,'id_moeda','Moeda',0,2,4);
			$form->input(array(
				'name' =>'valor_cambio_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'2',
				'label' =>'Cambio',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'nome_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Nome',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Nome',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();
			echo ' <div id="checkbox" class="checkbox"><input type="checkbox" name="is_br" id="is_br" value="nothing"><span>Internacional</span></div>';
			$form->groupClose();
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'cep_hotelPJ',
				'type' =>'text',
				'placeholder' => 'CEP',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'CEP',
				'value' =>'',
				'required' => false
				));
				echo '<div id="msg_cep"></div>';
			$form->groupClose();
		
			$form->groupOpen();	
			$form->input(array(
				'name' =>'endereco_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Endereço',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Endereço',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'numero_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Número',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Número',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();


			$form->groupOpen();	
			$form->input(array(
				'name' =>'cidade_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Cidade',
				'num_label' =>'2',
				'num_input' =>'6',
				'label' =>'Cidade',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'uf_hotelPJ',
				'type' =>'text',
				'placeholder' => 'UF',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'UF',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'telefone_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Telefone',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Telefone',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'email_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Email',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Email',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_hotelPJ',
				'type' =>'file',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'7',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
			
			$form->input(array(
				'name' =>'valor_casa_hotelPJ',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
		<label>Descrição</label>
		<textarea name="descricao_hotelPJ" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirHotel" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	<!-- Modal Hotel -->
	   		
	   		
	   		
	   		
	
	
		   <!-- Modal Seguro -->
	<div class="modal fade" id="modalSeguro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Seguros</h4>
				</div>
				<div class="modal-body">
			<?php
		$form->init('form_seguro','/seguro/saveSeguroPJ');
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'id_seguroPJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => false
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_clientePJ',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' => $_SESSION['empresa']['id'],
			'required' => false
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_seguradora,'id_seguradora','Seguradora',1,2,8);
		$form->groupClose();

		$form->groupOpen();
		$form->select($opt_tipoSeguro,'id_tipoSeguro','Tipo',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_continente,'id_continente','Continente',1,2,5);
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_cambio,'id_moeda','Moeda',0,2,5);
		$form->input(array(
				'name' =>'valor_cambio_seguroPJ',
				'type' =>'text',
				'placeholder' => '',
				'num_label' =>'1',
				'num_input' =>'2',
				'label' =>'valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
				'name' =>'dt_inicio_seguroPJ',
				'type' =>'date',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Inicio',
				'value' =>'',
				'required' => true
				));

		$form->input(array(
				'name' =>'dt_fim_seguroPJ',
				'type' =>'date',
				'placeholder' => '',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Fim',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_seguroPJ',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_casa_seguroPJ',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'voucher_seguroPJ',
				'type' =>'file',
				'placeholder' => 'Voucher',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
		
		?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirSeguro" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		   	<!-- Modal Seguro -->
		   
		   
		   
		   
		   
		   <!-- Modal Tickets -->
	<div class="modal fade" id="modalTicket" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Tickets</h4>
				</div>
				<div class="modal-body">
						<?php
			$form->init('form_compraticket','/compraTicket/saveCompraTicketPJ');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_compraTicketPJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => true
				));
			$form->input(array(
				'name' =>'id_clientePJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $_SESSION['empresa']['id'],
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();
			$form->select($opt_ticket,'id_ticket','Ticket',1,2,8);
			$form->groupClose();


			$form->groupOpen();	
			$form->select($opt_cambio,'id_moeda','Moeda',0,2,5);
			$form->input(array(
				'name' =>'valor_cambio_compraTicketPJ',
				'type' =>'text',
				'placeholder' => 'Cambio',
				'num_label' =>'1',
				'num_input' =>'2',
				'label' =>'Valor',
				'value' =>'',
				'required' => false
				));
			$form->groupClose();


			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_compraTicketPJ',
				'type' =>'text',
				'placeholder' => 'Valor da compra',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'comissao_compraTicketPJ',
				'type' =>'text',
				'placeholder' => 'Comissão em porcentagem',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();
			
			$form->groupOpen();	
			$form->input(array(
				'name' =>'voucher_compraTicketPJ',
				'type' =>'file',
				'placeholder' => 'Voucher',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Voucher',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'fornecedor_compraTicketPJ',
				'type' =>'text',
				'placeholder' => 'Nome Fornecedor',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Fornecedor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
						?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirTicket" class="btn btn-primary">
						<i class="glyphicon glyphicon-plus-sign"></i> Incluir
					</button>
					<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

		   	<!-- Modal Tickets -->
		   	
		   	
		   	
		   	<!-- Modal Cruzeiros -->
	<div class="modal fade" id="modalCruzeiro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Cruzeiro</h4>
				</div>
				<div class="modal-body">
				<?php
				
			$form->init('form_cruzeiro','/cruzeiro/saveCruzeiroPJ');
			$form->groupOpen();	
			$form->input(array(
				'name' =>'id_cruzeiroPJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' =>'',
				'required' => true
				));
			$form->input(array(
				'name' =>'id_clientePJ',
				'type' =>'hidden',
				'placeholder' => '',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'',
				'value' => $_SESSION['empresa']['id'],
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->select($opt_companiaCruzeiro,'id_compania_cruzeiro','Companias',0,2,8);
			$form->groupClose();

			$form->groupOpen();	
			$form->select($opt_cambio,'id_moeda','Moeda',0,2,4);
			$form->input(array(
				'name' =>'valor_cambio_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Cambio',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
			$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'navio_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Navio',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'navio',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'dt_inicio_cruzeiroPJ',
				'type' =>'date',
				'placeholder' => 'Inicio',
				'num_label' =>'2',
				'num_input' =>'4',
				'label' =>'Início',
				'value' =>'',
				'required' => true
				));
				
				
		$form->input(array(
				'name' =>'dt_fim_cruzeiroPJ',
				'type' =>'date',
				'placeholder' => 'Fim',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Fim',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'rota_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Rota',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Rota',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'nm_confirmacao_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Número de Confirmação',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Número',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'tipo_cabine_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Tipo de Cabine',
				'num_label' =>'2',
				'num_input' =>'8',
				'label' =>'Cabine',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'valor_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Valor do Cruzeiro',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
				'name' =>'comissao_cruzeiroPJ',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'5',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
				$form->groupClose();
				
				
			$form->groupOpen();	
			$form->input(array(
					'name' =>'voucher_cruzeiroPJ',
					'type' =>'file',
					'placeholder' => 'Voucher',
					'num_label' =>'2',
					'num_input' =>'8',
					'label' =>'Voucher',
					'value' =>'',
					'required' => false
					));
				$form->groupClose();
				
				?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirCruzeiro" class="btn btn-primary">
						<i class="glyphicon glyphicon-plus-sign"></i> Incluir
					</button>
					<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

		   	<!-- Modal Cruzeiros -->
		   	
		   	
		   	
	<!-- Modal Outros Produtos -->
	<div class="modal fade" id="modalProdutos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Outros Produtos</h4>
				</div>
				<div class="modal-body">
		<?php 
		$form->init('form_produtooutros','/produtoOutros/saveProdutoOutrosPJ');
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_produtoPJ',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' =>'',
			'required' => true
			));
		$form->input(array(
			'name' =>'id_clientePJ',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' => $_SESSION['empresa']['id'],
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->select($opt_cambio,'id_moeda','Moeda',0,2,4);
		$form->input(array(
			'name' =>'valor_cambio_produtoPJ',
			'type' =>'text',
			'placeholder' => 'Cambio',
			'num_label' =>'2',
			'num_input' =>'2',
			'label' =>'Valor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'titulo_produtoPJ',
			'type' =>'text',
			'placeholder' => 'Título',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Título',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'valor_produtoPJ',
			'type' =>'text',
			'placeholder' => 'Valor',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Valor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
				
		$form->groupOpen();	
		$form->input(array(
			'name' =>'comissao_produtoPJ',
			'type' =>'text',
			'placeholder' => 'Comissão',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Comissão',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'fornecedor_produtoPJ',
			'type' =>'text',
			'placeholder' => 'Fornecedor',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Fornecedor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'dt_inicio_produtoPJ',
			'type' =>'date',
			'placeholder' => 'Início',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Início',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		$form->groupOpen();	
		$form->input(array(
			'name' =>'dt_final_produtoPJ',
			'type' =>'date',
			'placeholder' => 'Final',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'Final',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
				?>
				<label>Descrição</label>
					<textarea name="descricao_produtoPJ" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirProdutos" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		<!-- Modal Outros Produtos -->
		
		
		<!-- Modal Passagens -->
	<div class="modal fade" id="modalPassagens" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						&times;
					</button>
					<h4 class="modal-title" id="myModalLabel">Passagem Aérea</h4>
				</div>
				<div class="modal-body">
				<?php
		$form->init('form_passagens','/passagens/savePassagensPJ');
		$form->groupOpen();	
		$form->input(array(
			'name' =>'id_passagensPJ',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' =>'',
			'required' => true
			));
		$form->input(array(
			'name' =>'id_clientePJ',
			'type' =>'hidden',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'5',
			'label' =>'',
			'value' => $_SESSION['empresa']['id'],
			'required' => true
			));
		$form->groupClose();
		


		$form->groupOpen();	
		$form->select($opt_compania,'id_compania','Compania',1,2,8);
		echo '<td><a href="/compania/cadCompania" title="Adicionar nova Compania caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();


		$form->groupOpen();	
		$form->select($opt_classe,'id_classe','Classe',1,2,8);
		echo '<td><a href="/classe/cadClasse" title="Adicionar nova classe caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();

		
		
		$form->groupOpen();	
		$form->select($opt_origem,'id_origem','Origem',1,2,6);	
		echo '<td><a href="/origem/cadOrigem" title="Adicionar novo origem caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
		$form->groupClose();
		
		
		
		$form->groupOpen();	
		$form->select($opt_destino,'id_destino','Destino',1,2,6);
		echo '<td><a href="/destino/cadDestino" title="Adicionar novo destino caso não exista" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span></a></td>';
				
		$form->groupClose();


		$form->groupOpen();	
		$form->select($opt_cambio,'id_moeda','Moeda',0,2,4);
		$form->input(array(
			'name' =>'valor_cambio_passagensPJ',
			'type' =>'text',
			'placeholder' => 'Cambio',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Valor',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

		echo '<input type="checkbox" id="somente_ida" /> <strong>Somente ida</strong>';
		echo '<fieldset id="fs_ida">';
		echo '<legend><strong>IDA</strong></legend>';
		$form->groupOpen();	
		$form->input(array(
			'name' =>'dataIda_passagensPJ',
			'type' =>'date',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'4',
			'label' =>'Data',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'saidaIda_passagensPJ',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Saida',
			'value' =>'',
			'required' => true
			));

		$form->input(array(
			'name' =>'chegadaIda_passagensPJ',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Chegada',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		echo '</fieldset>';
		
		
		echo '<fieldset id="fs_volta">';
		echo '<legend><strong>Volta</strong></legend>';
		$form->groupOpen();	
		$form->input(array(
			'name' =>'dataVolta_passagensPJ',
			'type' =>'date',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'4',
			'label' =>'Data',
			'value' =>'',
			'required' => false
			));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'saidaVolta_passagensPJ',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Saida',
			'value' =>'',
			'required' => false
			));
			
		$form->input(array(
			'name' =>'chegadaVolta_passagensPJ',
			'type' =>'time',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Chegada',
			'value' =>'',
			'required' => false
			));
		$form->groupClose();
		echo '</fieldset>';
		echo '<hr>';

		$form->groupOpen();	
		$form->input(array(
			'name' =>'voo_passagensPJ',
			'type' =>'text',
			'placeholder' => 'Voo',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Voo',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();
		
		$form->groupOpen();	
		$form->input(array(
			'name' =>'bagagem_passagensPJ',
			'type' =>'text',
			'placeholder' => '',
			'num_label' =>'2',
			'num_input' =>'3',
			'label' =>'Bagagem',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();


		$form->groupOpen();	
		$form->input(array(
			'name' =>'voucher_passagensPJ',
			'type' =>'file',
			'placeholder' => 'Voucher',
			'num_label' =>'2',
			'num_input' =>'8',
			'label' =>'Voucher',
			'value' =>'',
			'required' => true
			));
		$form->groupClose();

			 $form->groupOpen();	
			 $form->input(array(
				'name' =>'tarifa_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Valor',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Valor',
				'value' =>'',
				'required' => true
				));
		
			$form->input(array(
				'name' =>'ticket_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Ticket',
				'num_label' =>'1',
				'num_input' =>'4',
				'label' =>'Ticket',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'valor_casa_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Comissão',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Comissão',
				'value' =>'',
				'required' => true
				));
				
			$form->input(array(
				'name' =>'tx_embarque_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Taxa de Enbarque',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Embarque',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();

			$form->groupOpen();	
			$form->input(array(
				'name' =>'tx_outras_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Taxa Extra',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Extra',
				'value' =>'',
				'required' => false
				));
				
			$form->input(array(
				'name' =>'tx_repasse_passagensPJ',
				'type' =>'text',
				'placeholder' => 'Taxa de Repasse',
				'num_label' =>'2',
				'num_input' =>'3',
				'label' =>'Repasse',
				'value' =>'',
				'required' => true
				));
		$form->groupClose();
				?>
				</div>
				<div class="modal-footer">
					<button type="submit" id="bt_incluirPassagens" class="btn btn-primary"><i class="glyphicon glyphicon-plus-sign"></i> Incluir</button>
				<?php $form->close(); ?>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	  	<!-- Modal Passagens -->
		   	
		   	
	
	
	
		<!-- Modal Finalização de Venda -->
	<div class="modal fade" id="modalFinaliza" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog" style="width: 50%;">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
					<h4 class="modal-title" id="myModalLabel">Finalizar Venda</h4>
				</div>
				<div class="modal-body">
					<label style="color: #797676;width: 90%" class="col-sm-2 control-label">Agencia</label> 
					<form method="post" action="/vendaPJ/saveVendaPJ">
						<select class="form-control" name="id_agencia" style="width: 70%">
							<option value="0">7 Brasil</option>
							<?php foreach ($agencia as $key => $value): ?>
								<option value="<?=$value['id_agencia']?>"><?=$value['nomefantasia_agencia']?></option>
							<?php endforeach; ?>
						</select>
						<br />
						<label id="lb_valor_agencia" style="color: rgb(121, 118, 118);width: 90%" class="col-sm-2 control-label">Valor Agência</label> 
						<input type="text" class="form-control" style="width: 30%" id="valor_agencia" placeholder="Valor da Agência" name="valor_agencia" />
						<br>
						<label id="lb_agente" style="color: rgb(121, 118, 118);width: 90%" class="col-sm-2 control-label">Agente</label> 
						<select class="form-control" name="id_agente" id="id_agente" style="width: 70%"></select>
						<br />
						<label id="lb_valor_agente" style="color: rgb(121, 118, 118);width: 90%" class="col-sm-2 control-label">Valor Agente</label> 
						<input type="text" class="form-control" style="width: 30%" id="valor_agente" placeholder="Valor da Agência" name="valor_agente" />
						<br>
						<br>
					
					    <div id="painel_cliente">
					<div class="panel-group" id="accordion">
					
					<?php $total_tudo = 0; 
						  $total_comissao = 0;
					?>
					
					
					
					<!-- Aba de cliente-->
					<?php if(isset($empresa)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="collapsed">Empresa</a>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading"><?=$empresa[0]['nomefantasia_clientePJ']?></h4>
							    <p class="list-group-item-text">CNPJ: <?=$empresa[0]['cnpj_clientePJ']?></p>
							    <p class="list-group-item-text">EMAIL: <?=$empresa[0]['email_clientePJ']?></p>
							    <p class="list-group-item-text">TELEFONE: <?=$empresa[0]['telefone_clientePJ']?></p>
							    <p class="list-group-item-text">RESPONSÁVEL: <?=$empresa[0]['nomeresponsavel_clientePJ']?></p>
							    <p class="list-group-item-text">CPF: <?=$empresa[0]['cpf_responsavel_clientePJ']?></p>
							    <p class="list-group-item-text">TELFONE: <?=$empresa[0]['telefone_responsavel_clientePJ']?></p>
							    <p class="list-group-item-text">EMAIL: <?=$empresa[0]['email_responsavel_clientePJ']?></p>
							  </a>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					  <!-- Aba de cliente-->
					  
					  <!-- Aba de Funcionarios-->
					<?php if(isset($dependentes)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed">Funcionários</a>
					      </h4>
					    </div>
					    <div id="collapseTwo" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($dependentes as $key => $value): ?>
							  <a href="#" class="list-group-item">
							    <h4 class="list-group-item-heading"><?=$value['nome_dependentePJ']?></h4>
							    <p class="list-group-item-text">DEPARTAMENTO: <strong><?=$opt_departamento[$value['id_departamento']]?></strong></p>
							    <p class="list-group-item-text">CPF: <strong><?=$value['cpf_dependentePJ']?></strong></p>
							    <p class="list-group-item-text">EMAIL: <strong><?=$value['email_dependentePJ']?></strong></p>
							    <p class="list-group-item-text">TELEFONE: <strong><?=$value['telefone_dependentePJ']?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					  <!-- Aba de Funcionarios-->
					  
					  <!-- Todos Produtos -->
					  <div id="todos_produtos">
					  	
				  <?php if(isset($carros)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" class="collapsed">Carros</a>
					      </h4>
					    </div>
					    <div id="collapseThree" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($carros as $key => $value): 
					       		$total_carro = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">LOCADORA: <strong><?=$opt_locadora[$value['id_locadora']]?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_carroPJ']))?></strong></p>
							    <p class="list-group-item-text">FINAL: <strong><?=date('d/m/Y',strtotime($value['dt_devolucao_carroPJ']))?></strong></p>
							    <?php $total_carro += $value['valor_carroPJ'] + $value['valor_casa_carroPJ'] + $value['taxa_carroPJ'];
							    	$total_tudo += $total_carro;
									$total_comissao += $value['valor_casa_carroPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_carro,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					
					<!-- Hotel-->
					 <?php if(isset($hotels)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour" class="collapsed">Hotel</a>
					      </h4>
					    </div>
					    <div id="collapseFour" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($hotels as $key => $value): 
					       		$total_hotel = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">BROKERS: <strong><?=$opt_brokers[$value['id_brokers']]?></strong></p>
							    <p class="list-group-item-text">NOME: <strong><?=$value['nome_hotelPJ']?></strong></p>
							    <p class="list-group-item-text">LOCALIDADE: <strong><?=$value['cidade_hotelPJ'].' - '.$value['uf_hotelPJ']?></strong></p>
							    <p class="list-group-item-text">TELEFONE: <strong><?=$value['telefone_hotelPJ']?></strong></p>
							    <p class="list-group-item-text">EMAIL: <strong><?=$value['email_hotelPJ']?></strong></p>
							    <?php $total_hotel += $value['valor_hotelPJ'] + $value['valor_casa_hotelPJ'];
							    	  $total_tudo += $total_hotel;
									  $total_comissao += $value['valor_casa_hotelPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_hotel,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					<!-- Hotel-->
					
					
					<!-- Seguro -->
					 <?php if(isset($seguros)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive" class="collapsed">Seguro</a>
					      </h4>
					    </div>
					    <div id="collapseFive" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($seguros as $key => $value): 
					       		$total_seguro = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">SEGURADORA: <strong><?=$opt_seguradora[$value['id_seguradora']]?></strong></p>
							    <p class="list-group-item-text">TIPO: <strong><?=$opt_tipoSeguro[$value['id_tipoSeguro']]?></strong></p>
							    <p class="list-group-item-text">CONTINENTE: <strong><?=$opt_continente[$value['id_continente']]?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_seguroPJ']))?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($value['dt_fim_seguroPJ']))?></strong></p>
							    <?php $total_seguro += $value['valor_seguroPJ'] + $value['valor_casa_seguroPJ'];
							    	  $total_tudo += $total_seguro;
									  $total_comissao += $value['valor_casa_seguroPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_seguro,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					
					  <!-- TIckets -->
					   <?php if(isset($compTicket)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix" class="collapsed">Tickets</a>
					      </h4>
					    </div>
					    <div id="collapseSix" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($compTicket as $key => $value): 
					       		$total_ticket = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">TICKET: <strong><?=$opt_ticket[$value['id_ticket']]?></strong></p>
							    <p class="list-group-item-text">FORNECEDOR: <strong><?=$value['fornecedor_compraTicketPJ']?></strong></p>
							    <?php $total_ticket += $value['valor_compraTicketPj'] + $value['comissao_compraTicketPJ'];
							    	  $total_tudo += $total_ticket;
									  $total_comissao += $value['comissao_compraTicketPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_ticket,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					  
					  
					  <!-- Cruzeiro -->
					     <?php if(isset($cruzeiro)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" class="collapsed">Cruzeiro</a>
					      </h4>
					    </div>
					    <div id="collapseSeven" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($cruzeiro as $key => $value): 
					       		$total_cruzeiro = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">COMPANIA: <strong><?=$opt_companiaCruzeiro[$value['id_compania_cruzeiro']]?></strong></p>
							    <p class="list-group-item-text">NAVIO: <strong><?=$value['navio_cruzeiroPJ']?></strong></p>
							    <p class="list-group-item-text">NÚMERO: <strong><?=$value['nm_confirmacao_cruzeiroPJ']?></strong></p>
							    <p class="list-group-item-text">CABINE: <strong><?=$value['tipo_cabine_cruzeiroPJ']?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_cruzeiroPJ']))?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($value['navio_cruzeiroPJ']))?></strong></p>
							    <?php $total_cruzeiro += $value['valor_cruzeiroPJ'] + $value['comissao_cruzeiroPJ'];
							    	  $total_tudo += $total_cruzeiro;
									  $total_comissao += $value['comissao_cruzeiroPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_cruzeiro,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					  
					  
					  <!-- Outros Produtos -->
					  <?php if(isset($produto)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseEigth" class="collapsed">Outros Produtos</a>
					      </h4>
					    </div>
					    <div id="collapseEigth" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($produto as $key => $value): 
					       		$total_produto = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">TITULO: <strong><?=$value['titulo_produtoPJ']?></strong></p>
							    <p class="list-group-item-text">FORNECEDOR: <strong><?=$value['fornecedor_produtoPJ']?></strong></p>
							    <p class="list-group-item-text">INÍCIO: <strong><?=date('d/m/Y',strtotime($value['dt_inicio_produtoPJ']))?></strong></p>
							    <p class="list-group-item-text">FIM: <strong><?=date('d/m/Y',strtotime($value['dt_final_produtoPJ']))?></strong></p>
							    <?php $total_produto += $value['valor_produtoPJ'] + $value['comissao_produtoPJ'];
							   		  $total_tudo += $total_produto; 
									  $total_comissao += $value['comissao_produtoPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_produto,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					
					
					
					 <!-- Outros Passagens -->
					  <?php if(isset($passagens)): ?>
					<div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseNine" class="collapsed">Passagens</a>
					      </h4>
					    </div>
					    <div id="collapseNine" class="panel-collapse collapse" style="height: 0px;">
					      <div class="panel-body">
					       <div class="list-group">
					       	<?php foreach ($passagens as $key => $value): 
					       		$total_passagens = 0;
					       		?>
							  <a href="#" class="list-group-item">
							    <p class="list-group-item-text">CÓDIGO RESERVA: <strong><?=$value['codigo_reserva_pasagensPJ']?></strong></p>
							    <p class="list-group-item-text">COMPANIA: <strong><?=$opt_compania[$value['id_compania']]?></strong></p>
							    <p class="list-group-item-text">CLASSE: <strong><?=$opt_classe[$value['id_classe']]?></strong></p>
							    <p class="list-group-item-text">ORIGEM: <strong><?=$opt_origem[$value['id_origem']]?></strong></p>
							    <p class="list-group-item-text">DESTINO: <strong><?=$opt_destino[$value['id_destino']]?></strong></p>
							    <p class="list-group-item-text">VOO: <strong><?=$value['voo_passagensPJ']?></strong></p>
							    <p class="list-group-item-text">DATA DE IDA: <strong><?=date('d/m/Y',strtotime($value['dataIda_passagensPJ']))?></strong></p>
							    <p class="list-group-item-text">HORA DE PARTIDA: <strong><?=date('H:i',strtotime($value['saidaIda_passagensPJ']))?></strong></p>
							    <p class="list-group-item-text">HORA DE CHEGADA: <strong><?=date('H:i',strtotime($value['chegadaIda_passagensPJ']))?></strong></p>
							    <?php if(date('Y',strtotime($value['dataVolta_passagensPJ'])) > date('Y')){ ?>
							    <p class="list-group-item-text">DATA DE VOLTA: <strong><?=date('d/m/Y',strtotime($value['dataVolta_passagensPJ']))?></strong></p>
							    <p class="list-group-item-text">HORA DE PARTIDA: <strong><?=date('H:i',strtotime($value['saidaVolta_passagensPJ']))?></strong></p>
							    <p class="list-group-item-text">HORA DE CHEGADA: <strong><?=date('H:i',strtotime($value['chegadaVolta_passagensPJ']))?></strong></p>
							    <?php } ?>
							    <?php $total_passagens += $value['tarifa_passagensPJ'] + $value['valor_casa_passagensPJ'] + $value['tx_embarque_passagensPJ'] + $value['tx_outras_passagensPJ'] + $value['tx_repasse_passagensPJ'];
							    	   $total_tudo += $total_passagens;
									   $total_comissao += $value['valor_casa_passagensPJ'];
							    ?>
							    <p class="list-group-item-text">TOTAL: <strong>R$ <?=number_format($total_passagens,2,',','.')?></strong></p>
							  
							  </a>
					       	<?php endforeach; ?>
							</div>
							
							
					      </div>
					    </div>
					  </div>
					<?php endif; ?>
					  
					  
					  
					 </div> <!-- Todos Produtos -->
					  
					</div>
				</div>
				<br />
				<br />
					    
					    <label>Descrição de venda</label>
						<textarea name="descricao_venda" class="form-control" rows="3"></textarea>
				</div>
				<div class="modal-footer">
					<input type="hidden" name="total_venda" value="<?=$total_tudo?>">
					<input type="hidden" name="total_comissao" value="<?=$total_comissao?>">
					<button type="button" data-dismiss="modal" id="bt_cancel" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-down"></i> Cancelar</button>
					<button type="submit" id="bt_finalizaVenda" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-up"></i> Confirmar</button>
				</form>
					
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	   
		   	<!-- Modal Finalização de Venda -->
	
	
	
		   	<!-- Modal Rateio Venda -->
	<div class="modal fade" id="modalRateio" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title" id="myModalLabel">Rateio Venda   -   <strong>R$ <?=number_format($total_tudo,2,',','.') ?></strong></h4>
				</div>
				<div class="modal-body">
				<form method="post" name="rateio" action="/vendaPJ/cadTipoPagamentoPJ">
				<input type="hidden" name="id_clientePJ" value="<?= $_SESSION['empresa']['id']; ?>">
				<p class="list-group-item-text"></p>
				<table class="table">
						<tbody>
							<?php if($empresa[0]['credito_clientePJ'] > 0): ?>
							<tr>
								<td><label>CRÉDITO DA EMPRESA</label></td>
								<td><input type="checkbox" name="creadito_empresa" value="<?=$total_tudo?>"/> <strong><?=number_format($empresa[0]['credito_clientePJ'],2,',','.');  ?></strong></td>
							</tr>
							<?php endif; ?>
							<div class="formas_pagamento">
							
							<?php foreach($tipoPagamento as $key => $value): ?>
								<?php if($value['id_tipoPagamento'] != 3):?>
							<tr>
							<td><label><?=$value['titulo_tipoPagamento']?></label></td>
							<td>
								<input type="text" class="formPGTO" name="tipo_<?=$value['id_tipoPagamento']?>" />
								X <input type="text" style="width: 10%" maxlength="2" name="vezes_<?=$value['id_tipoPagamento']?>" />
							</td>
							</tr>							    			
								<?php else: ?>
									<!-- Cartões de crédito -->
										<?php foreach ($cartaoPJ->listCartCli($_SESSION['empresa']['id']) as $chave => $valor) { ?>
										<tr>
											<td><label><?=$opt_tipoCartao[$valor['id_tipoCartao']]?></label></td>
											<td>
												<input type="text" class="formPGTO" name="tipo_3_<?=$valor['id_tipoCartao']?>"/>
												X <input type="text" name="vezes_3_<?=$valor['id_tipoCartao']?>" style="width: 10%" maxlength="2" />
											</td>
										</tr>
									<!-- Cartões de crédito -->
								<?php 
										}
								endif; ?>
							<?php endforeach; ?>
								</div> <!-- End formas_pagamento -->
						</tbody>
				</table>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
							</form>
								
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
		   	<!-- Modal Rateio Venda -->
	
	
	
	
	<!-- Tela de botoes de produtos-->
	<div class="venda_produtos">
		<div class="vend_produtos_left">
			<br>
			<br>
			<p><a href="#" title="Reserva de Hoteis" data-toggle="modal" data-target="#modalHotel" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> HOTEIS</a></p>
			<br>
			<p><a href="#" data-toggle="modal" data-target="#modalCarros" title="Aluguel de carros" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CARROS</a></p>
			<br>
			<p><a href="#" data-toggle="modal" data-target="#modalPassagens" title="Reservar passagens aéreas" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> PASSAGENS</a></p>
		</div>
		
		<div class="vend_produtos_right">
			<br>
			<br>
			<p><a href="#" data-toggle="modal" data-target="#modalSeguro" title="Contratar Seguro para viagem" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> SEGURO</a></p>
			<br>
			<p><a href="#" title="Compra de tickets" data-toggle="modal" data-target="#modalTicket" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> TICKETS</a></p>
			<br>
			<p><a href="#" data-toggle="modal" data-target="#modalCruzeiro" title="Compra de cruzeiros atlânticos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> CRUZEIROS</a></p>
			<br>
			<p><a href="#" data-toggle="modal" data-target="#modalProdutos" title="Outros Produtos" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus-sign"></i> Outros</a></p>
		</div>
	</div>
	<!-- Tela de botoes de produtos-->
	<hr>
	
	<hr>
	<br>
	<table class="table table-condensed">
	<!-- Cliente da Lista de venda -->
		<tbody>
			<?php $total_tudo = 0;
				  
			
			 ?>
			<!-- Empresa selecionada -->
			<?php if(isset($_SESSION['empresa'])): ?>
				<?php foreach($empresa as $key => $value): ?>
					<tr class="warning" id="empresa">
						<td>EMPRESA: <?=$value['nomefantasia_clientePJ']?></td>
						<td><?=$value['cidade_clientePJ']?></td>
						<td><a href="#" class="btn btn-success" data-toggle="modal" data-target="#modalFuncionario" id_clientePJ="<?=$value['id_clientePJ']?>" id="bt_addFunc">Funcionário</a></td>
						<td><a href="/vendaPJ/removeClientePJ" onclick="return confirm('Deseja realmente remover empresa da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			
			
			<!-- Funcionarios selecionados -->
			<?php if(isset($_SESSION['funcionarios'])): ?>
				<?php foreach ($dependentes as $key => $value): ?>
					<tr class="warning">
					<td><?=$value['nome_dependentePJ']?></td>						
					<td><?=$opt_departamento[$value['id_departamento']]?></td>						
					<td><?=$value['cpf_dependentePJ']?></td>						
					<td><a href="/vendaPJ/removeDependentePJ/id/<?=$value['id_dependentePJ']?>" onclick="return confirm('Deseja realmente remover funcionário da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			<!-- Aluguel de carro -->
			<?php if(isset($carros)): 
				?>
				<?php foreach ($carros as $key => $value): 
					
				$total_carro = 0;
					?>
					<tr class="warning prod">
						<td>Locadora: <?=$opt_locadora[$value['id_locadora']]?></td>
						<td><?=date('d/m/Y',strtotime($value['dt_inicio_carroPJ']))?> à <?=date('d/m/Y',strtotime($value['dt_devolucao_carroPJ']))?></td>
						<?php $total_carro += $value['valor_carroPJ'] + $value['valor_casa_carroPJ'] + $value['taxa_carroPJ'];
							  $total_tudo += $total_carro;
						?>
						<td>Total: R$ <?=number_format($total_carro,2,',','.')?></td>
						<td><a href="/carro/removeCarroPJ/id/<?=$value['id_carroPJ']?>" onclick="return confirm('Deseja realmente remover Carro da lista de Venda?')" class="btn btn-danger">Remover</a></td></td>
						
					</tr>
				<?php endforeach; ?>
			<?php endif;  ?>
			
			
			<!-- Lista de Hotel -->
			<?php if(isset($hotels)): ?>
				<?php foreach ($hotels as $key => $value): 
					$valor_hotel = 0;
					?>
					<tr class="warning prod">
						<td>HOTEL: <?=$value['nome_hotelPJ']?></td>
						<td><?=$opt_brokers[$value['id_brokers']]?></td>
						<?php $valor_hotel += $value['valor_hotelPJ'] + $value['valor_casa_hotelPJ'];
							  $total_tudo += $valor_hotel;
						 ?>
						<td>TOTAL: R$ <?=number_format($valor_hotel,2,',','.')?></td>
						<td><a href="/hotel/removeHotelPJ/id/<?=$value['id_hotelPJ']?>" onclick="return confirm('Deseja realmente remover Hotel da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach;  ?>
			<?php endif; ?>
			
			
			<!-- listando Seguro --> 
			<?php if(isset($seguros)): ?>
			<?php foreach ($seguros as $key => $value): 
				$total_seguro = 0;
				?>
				<tr class="warning prod">
					<td>SEGURO: <?=$opt_seguradora[$value['id_seguradora']]?></td>
					<td><?=$opt_tipoSeguro[$value['id_tipoSeguro']]?></td>
					<?php  $total_seguro += $value['valor_seguroPJ'] + $value['valor_casa_seguroPJ'];
							$total_tudo += $total_seguro;
					?>
					<td>TOTAL: R$ <?=number_format($total_seguro,2,',','.')?></td>
					<td><a href="/seguro/removeSeguroPJ/id/<?=$value['id_seguroPJ']?>" onclick="return confirm('Deseja realmente remover Seguro da lista de Venda?')" class="btn btn-danger">Remover</a></td>
				</tr>
			<?php endforeach; ?>
			<?php endif; ?>
			
			
			<!-- listando Ticket --> 
			<?php if(isset($compTicket)): ?>
				<?php foreach ($compTicket as $key => $value): 
					$total_ticket = 0;
					?>
					<tr class="warning prod">
						<td>TICKET: <?=$opt_ticket[$value['id_ticket']]?></td>
						<td><?=$value['fornecedor_compraTicketPJ']?></td>
						<?php $total_ticket += $value['valor_compraTicketPj'] + $value['comissao_compraTicketPJ']; 
						$total_tudo += $total_ticket;
						?>
						<td>TOTAL: R$ <?=number_format($total_ticket,2,',','.')?></td>
						<td><a href="/compraTicket/removeCompraTicketPJ/id/<?=$value['id_compraTicketPJ']?>" onclick="return confirm('Deseja realmente remover funcionário da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			
			
			<!-- listando Cruzeiro --> 
			<?php if(isset($cruzeiro)): ?>
				<?php foreach ($cruzeiro as $key => $value): 
					$total_cruzeiro = 0;
					?>
					<tr class="warning prod">
						<td>CRUZEIRO: <?=$opt_companiaCruzeiro[$value['id_compania_cruzeiro']]?></td>
						<td><?=$value['navio_cruzeiroPJ']?></td>
						<?php $total_cruzeiro += $value['valor_cruzeiroPJ'] + $value['comissao_cruzeiroPJ']; 
						$total_tudo += $total_cruzeiro;
						?>
						<td>TOTAL: R$ <?=number_format($total_cruzeiro,2,',','.')?></td>
						<td><a href="/cruzeiro/removeCruzeiroPJ/id/<?=$value['id_cruzeiroPJ']?>" onclick="return confirm('Deseja realmente remover funcionário da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			
			
			<!-- listando Produto --> 
			<?php if(isset($produto)): ?>
				<?php foreach ($produto as $key => $value): 
					$total_produto = 0;
					?>
					<tr class="warning prod">
						<td>PRODUTO: <?=$value['titulo_produtoPJ']?></td>
						<td><?=$value['fornecedor_produtoPJ']?></td>
						<?php $total_produto += $value['valor_produtoPJ'] + $value['comissao_produtoPJ']; 
						$total_tudo += $total_produto;
						?>
						<td>TOTAL: R$ <?=number_format($total_produto,2,',','.')?></td>
						<td><a href="/ProdutoOutros/removeProdutoOutrosPJ/id/<?=$value['id_produtoPJ']?>" onclick="return confirm('Deseja realmente remover Produto da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			<!-- listando Passagem --> 
			<?php if(isset($passagens)): ?>
				<?php foreach ($passagens as $key => $value): 
					$total_passagem = 0;
					?>
					<tr class="warning prod">
						<td>PASSAGEM: <?=$opt_compania[$value['id_compania']].' - '.$opt_classe[$value['id_classe']]?></td>
						<td>ORIGEM: <?=$opt_origem[$value['id_origem']].' - DESTINO: '.$opt_destino[$value['id_destino']]?></td>
						<?php $total_passagem += $value['tarifa_passagensPJ'] + $value['valor_casa_passagensPJ'] + $value['tx_embarque_passagensPJ'] + $value['tx_outras_passagensPJ'] + $value['tx_repasse_passagensPJ']; 
						$total_tudo += $total_passagem;
						?>
						<td>TOTAL: R$ <?=number_format($total_passagem,2,',','.')?></td>
						<td><a href="/passagens/removePassagensPJ/id/<?=$value['id_passagensPJ']?>" onclick="return confirm('Deseja realmente remover Produto da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			
			
			<!-- listando Forma pagamento --> 
			<?php if(isset($formaPagamento)): ?>
				<?php foreach ($formaPagamento as $key => $value): ?>
					
					<tr class="warning prod">
						<?php if($value['id_tipoPagamento'] == null){ ?>
							<td>RATEIO: Crédito da empresa</td>
						<?php }else{ ?>
							<td>RATEIO: <?=$opt_tipoPagamento[$value['id_tipoPagamento']]?></td>
						<?php } ?>
							<td><?=$value['vezes_formaPagamentoPJ']?> X</td>
							<td>TOTAL: R$ <?=number_format($value['valor_formaPagamentoPJ'],2,',','.')?></td>
							<td><a href="/vendaPJ/removeFormaPagamentoPJ/id/<?=$value['id_formaPagamentoPJ']?>" onclick="return confirm('Deseja realmente remover Forma de pagamento da lista de Venda?')" class="btn btn-danger">Remover</a></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			
			<tr class="success">
			<td><strong style="font-size: 20px;">Total Geral:</strong></td>
			<td></td>
			<td></td>
			<td><strong style="font-size: 20px;">R$ <?=number_format($total_tudo,2,',','.')?></strong></td>
			</tr>
		</tbody>
	</table>
       <button id="btn_finaliza_venda" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalFinaliza" >Finalizar Venda</button>
       <button id="btn_rateio_venda" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalRateio">Rateio</button>
<br />
<br />

<script>
	jQuery(function(){
		
		//Mascarando campos
		jQuery('#cnpj_clientePJ').mask('99.999.999/9999-99');
		
		
		//Validando valor vázio de campo de cnpj
		jQuery('#cnpj_clientePJ').keypress(function() {
			if(jQuery('#cnpj_clientePJ').val().length > 17){
				jQuery('#bt_findClientePJ').attr('disabled',false);
			}else{
				jQuery('#bt_findClientePJ').attr('disabled',true);
				
			}
		});
		
		
		if(jQuery('#empresa').length){
			jQuery('#cnpj_clientePJ').attr('disabled',true);
			jQuery('.btn-lg').attr('disabled',false);
		}else{
			jQuery('#cnpj_clientePJ').attr('disabled',false);
			jQuery('.btn-lg').attr('disabled',true);
		}
		
		if(jQuery('.prod').length){
			jQuery('#btn_finaliza_venda').attr('disabled',false);
			jQuery('#btn_rateio_venda').attr('disabled',false);
		}else{
			jQuery('#btn_finaliza_venda').attr('disabled',true);
			jQuery('#btn_rateio_venda').attr('disabled',true);
		}
		
		//Populando empresa buscada pelo CNPJ
		jQuery('#bt_findClientePJ').click(function(){
			if(jQuery('#cnpj_clientePJ').val().length < 18){
				alert('Digite corretamente o CNPJ da Empresa!');
				return false;
			}else{
				jQuery.ajax({
					url: '/vendaPJ/findClientePJ',
					type: 'post',
					dataType: 'json',
					data: {cnpj : jQuery('#cnpj_clientePJ').val()},
					success: function(data){
						if(data){
							jQuery('#id_PJ').val(data.id_clientePJ);
							jQuery('#nomefantasia_PJ').html('<strong>NOME FANTASIA:</strong> '+data.nomefantasia_clientePJ);
							jQuery('#cnpj_PJ').html('<strong>CNPJ: </strong>' + data.cnpj_clientePJ);
							jQuery('#endereco_PJ').html('<strong>ENDEREÇO: </strong>' +data.endereco_clientePJ);
							jQuery('#cidade_PJ').html('<strong>CIDADE:</strong> ' +data.cidade_clientePJ);
							jQuery('#uf_PJ').html('<strong>UF: ' + data.uf_clientePJ);
							jQuery('#telefone_PJ').html('<strong>TELEFONE:</strong> '+data.telefone_clientePJ);
						}else{
							jQuery('.modal-body').html('<h2>Empresa não encontrada!</h2>');
							jQuery('#bt_incluir').attr('disabled',true);
							setTimeout(function(){
								location.href="/vendaPJ/cadVendaPJ"
							},3000);
						}
					}
				});
			}
			
		});
		
		//Funções ao modal Carros
		jQuery("#valor_cambio").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_carroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_carroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#taxa_carroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery('#valor_cambio').attr('disabled',true);
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() == '0'){
				jQuery('#valor_cambio').val('');
				jQuery('#valor_cambio').attr('disabled',true);
			}else{
				jQuery('#valor_cambio').attr('disabled',false);
			}
		});
		
		
		//Funções para o modal Hotel
		jQuery('#cep_hotelPJ').mask('99999-999');
		jQuery("#valor_hotelPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_hotelPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_cambio_hotelPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery('#is_br').click(function(){
			if(jQuery(this).attr('checked')){
				jQuery('#cep_hotelPJ').attr('disabled',true);
			}else{
				jQuery('#cep_hotelPJ').attr('disabled',false);
			}
		});
		
		jQuery('#valor_cambio_hotelPJ').attr('disabled',true);
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() == '0'){
				jQuery('#valor_cambio_hotelPJ').attr('disabled',true);
			}else{
				jQuery('#valor_cambio_hotelPJ').attr('disabled',false);
			}
		});
		
		
		
		
		//Funções para o model Seguro
		jQuery("#valor_cambio_seguroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_seguroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_seguroPJ").maskMoney({thousands:'', decimal:'.'});
		
		jQuery("#valor_cambio_seguroPJ").attr('disabled',true);
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery("#valor_cambio_seguroPJ").attr('disabled',false);
			}else{
				jQuery("#valor_cambio_seguroPJ").attr('disabled',true);
				
			}
		});
		
		
		//Funções do modal Ticket
		jQuery("#valor_cambio_compraTicketPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_compraTicketPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#comissao_compraTicketPJ").maskMoney({thousands:'', decimal:'.'});
		
		jQuery("#valor_cambio_compraTicketPJ").attr('disabled',true);
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery("#valor_cambio_compraTicketPJ").attr('disabled',false);
			}else{
				jQuery("#valor_cambio_compraTicketPJ").attr('disabled',true);
				
			}
		});
		
		
		//Funções do modal Cruzeiro
		jQuery("#valor_cambio_cruzeiroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_cruzeiroPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#comissao_cruzeiroPJ").maskMoney({thousands:'', decimal:'.'});
		
		jQuery("#valor_cambio_cruzeiroPJ").attr('disabled',true);
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery("#valor_cambio_cruzeiroPJ").attr('disabled',false);
			}else{
				jQuery("#valor_cambio_cruzeiroPJ").attr('disabled',true);
				
			}
		});
		
		
		
		//Funçoes do modal Produtos
		jQuery("#valor_cambio_produtoPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_produtoPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#comissao_produtoPJ").maskMoney({thousands:'', decimal:'.'});
		
		jQuery("#valor_cambio_produtoPJ").attr('disabled',true);
		
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery("#valor_cambio_produtoPJ").attr('disabled',false);
			}else{
				jQuery("#valor_cambio_produtoPJ").attr('disabled',true);
			}
		});
		
		//Funções do modal passagens
		jQuery("#valor_cambio_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#tarifa_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_casa_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#tx_embarque_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#tx_outras_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		jQuery("#tx_repasse_passagensPJ").maskMoney({thousands:'', decimal:'.'});
		
		jQuery("#valor_cambio_passagensPJ").attr('disabled',true);
		
		jQuery('[name=id_moeda]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery("#valor_cambio_passagensPJ").attr('disabled',false);
			}else{
				jQuery("#valor_cambio_passagensPJ").attr('disabled',true);
			}
		});
		
		jQuery('#somente_ida').attr('checked',true);
		jQuery('#fs_volta').hide('slow');
		jQuery('#somente_ida').click(function(){
			if(jQuery(this).attr('checked')){
				jQuery('#fs_volta').hide('slow');
			}else{
				jQuery('#fs_volta').show('slow');
			}
		});
		
		
		
		
		//fUNÇÕES MODAL FINALIZA VENDA
		jQuery("#valor_agencia").maskMoney({thousands:'', decimal:'.'});
		jQuery("#valor_agente").maskMoney({thousands:'', decimal:'.'});
		
		jQuery('#lb_valor_agencia').hide();
		jQuery('#valor_agencia').hide();
		
		
		jQuery('#lb_agente').hide();
		jQuery('#id_agente').hide();
		
		jQuery('#lb_valor_agente').hide();
		jQuery('#valor_agente').hide();
		
		
		jQuery('[name=id_agencia]').change(function(){
			if(jQuery(this).val() != '0'){
				jQuery.ajax({
					url: '/vendaPJ/findAgencia',
					type: 'post',
					dataType: 'json',
					data: {id_agencia: jQuery(this).val()},
					success: function(data){
						if(data){
							jQuery('#lb_valor_agencia').show();
							jQuery('#valor_agencia').show();
							
							jQuery('#lb_agente').show();
							jQuery('#id_agente').show();
							
							jQuery('#lb_valor_agente').show();
							jQuery('#valor_agente').show();
							
							jQuery('#id_agente').html('');
							for(var i = 0; i < data.length; i++){
								jQuery('#id_agente').append('<option value="'+data[i].id_agente+'">'+data[i].nome_agente+'</option>');
							}
						}
					}
				});
			}else{
				jQuery('#lb_valor_agencia').hide();
				jQuery('#valor_agencia').hide();
				jQuery('#valor_agencia').val('');
				
				
				jQuery('#lb_agente').hide();
				jQuery('#id_agente').hide();
				
				jQuery('#lb_valor_agente').hide();
				jQuery('#valor_agente').hide();
				jQuery('#valor_agente').val('');
			}
		});
		
		
		
		//formas_pagamento
		//Funções do modal Rateio
		jQuery(".formPGTO").maskMoney({thousands:'', decimal:'.'});
		var total = 0;
		jQuery('.formPGTO :text').each(function(){
			jQuery(this).attr('disabled',true);
		});
		
		
// 		
});
</script>